### ISSUE TITLE
Saving a model and loading it with Python script

### ISSUE THREAD

**Issue by kyu899** [Microsoft/CNTK#1002]
I am trying to practice saving and loading a model
So I slightly modified the already existing example, FeedForwardNet.py located in repos\CNTK\bindings\python\examples\NumpyInterop

The below is my full script.

# My FeedForwardNet.py
import numpy as np
import sys
import os
from cntk.device import cpu, set_default_device
from cntk import Trainer, persist
from cntk.learner import sgd
from cntk.ops import input_variable, cross_entropy_with_softmax, classification_error, sigmoid
from cntk.utils import ProgressPrinter
from cntk.models import *
from cntk.layers import *

abs_path = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.join(abs_path, "..", ".."))
# from examples.common.nn import fully_connected_classifier_net

# make sure we get always the same "randomness"
np.random.seed(0)

def generate_random_data(sample_size, feature_dim, num_classes):
    # Create synthetic data using NumPy.
    Y = np.random.randint(size=(sample_size, 1), low=0, high=num_classes)

    # Make sure that the data is separable
    X = (np.random.randn(sample_size, feature_dim) + 3) * (Y + 1)
    X = X.astype(np.float32)
    # converting class 0 into the vector "1 0 0",
    # class 1 into vector "0 1 0", ...
    class_ind = [Y == class_number for class_number in range(num_classes)]
    Y = np.asarray(np.hstack(class_ind), dtype=np.float32)
    return X, Y

def ffnet():
    input_dim = 2
    num_output_classes = 2
    num_hidden_layers = 2
    # hidden_layers_dim = 50

    # Input variables denoting the features and label data
    input = input_variable((input_dim), np.float32)
    label = input_variable((num_output_classes), np.float32)

    # Instantiate the feedforward classification model
    # netout = fully_connected_classifier_net(
        #input, num_output_classes, hidden_layers_dim, num_hidden_layers, sigmoid)

    h = Dense(32, activation=sigmoid)
    v = Dense(32, activation=sigmoid)(h)
    k = Dense(32, activation=sigmoid)(v)
    netout = Dense(num_output_classes, activation=None)(k)

    netout = netout(input)

    ce = cross_entropy_with_softmax(netout, label)
    pe = classification_error(netout, label)

    # Instantiate the trainer object to drive the model training
    trainer = Trainer(netout, ce, pe, sgd(netout.parameters, lr=0.02))

    # Get minibatches of training data and perform model training
    minibatch_size = 25

    pp = ProgressPrinter(128)
    for i in range(1024):
        features, labels = generate_random_data(
            minibatch_size, input_dim, num_output_classes)
        # Specify the mapping of input variables in the model to actual
        # minibatch data to be trained with
        trainer.train_minibatch({input: features, label: labels})
        pp.update_with_trainer(trainer)
    pp.epoch_summary()
    test_features, test_labels = generate_random_data(
        minibatch_size, input_dim, num_output_classes)
    avg_error = trainer.test_minibatch(
        {input: test_features, label: test_labels})

    persist.save_model(netout, "temp.dnn")
    another = persist.load_model("temp.dnn")

    ce = cross_entropy_with_softmax(another, label)
    pe = classification_error(another, label)

    # Instantiate the trainer object to drive the model training
    trainer = Trainer(another, ce, pe, sgd(another.parameters, lr=0.02))

    pp = ProgressPrinter(128)
    for i in range(1024):
        features, labels = generate_random_data(
            minibatch_size, input_dim, num_output_classes)
        # Specify the mapping of input variables in the model to actual
        # minibatch data to be trained with
        trainer.train_minibatch({input: features, label: labels})
        pp.update_with_trainer(trainer)
    pp.epoch_summary()
    test_features, test_labels = generate_random_data(
        minibatch_size, input_dim, num_output_classes)
    avg_error = trainer.test_minibatch(
        {input: test_features, label: test_labels})

    return avg_error

if __name__ == '__main__':
    # Specify the target device to be used for computing, if you do not want to
    # use the best available one, e.g.
    # set_default_device(cpu())

    error = ffnet()
    print(" error rate on an unseen minibatch %f" % error)

The script from start to save_model, load_model, and preparing to train the model again works well.
However, the script "trainer.train_minibatch({input: features, label: labels})" returns error.
Please note that there exist two "trainer.train_minibatch(~)" in my script. The second one returns error.

Below are the full output messages:
 Minibatch[   1- 128]: loss = 0.734827 * 3200
 Minibatch[ 129- 256]: loss = 0.531333 * 3200
 Minibatch[ 257- 384]: loss = 0.361054 * 3200
 Minibatch[ 385- 512]: loss = 0.299077 * 3200
 Minibatch[ 513- 640]: loss = 0.247677 * 3200
 Minibatch[ 641- 768]: loss = 0.236826 * 3200
 Minibatch[ 769- 896]: loss = 0.229991 * 3200
 Minibatch[ 897-1024]: loss = 0.215998 * 3200
Finished Epoch [1]: loss = 0.357098 * 25600
Traceback (most recent call last):
  File "C:/repos/CNTK/bindings/python/examples/NumpyInterop/FeedForwardNet.py", line 114, in <module>
    error = ffnet()
  File "C:/repos/CNTK/bindings/python/examples/NumpyInterop/FeedForwardNet.py", line 99, in ffnet
    trainer.train_minibatch({input: features, label: labels})
  File "C:\Python34\lib\site-packages\cntk\trainer.py", line 92, in train_minibatch
    updated = super(Trainer, self).train_minibatch(arguments, device)
  File "C:\Python34\lib\site-packages\cntk\cntk_py.py", line 1512, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: Function::Forward: Required argument's () value that the requested output(s) depend on has not been provided 

I want to know what I've done wrong and get your feedback.

Thank you.

**Comment by n17s** [comment]
The reason train_minibatch fails is that (currently) "input" is a variable that belongs to the original model. The new model is not connected to "input", it has a different variable on which data can be fed. There are different ways of getting access to that variable. One is to tag the original inputs with a tag e.g.
input = input_variable((input_dim), np.float32, name = 'features')
label  = input_variable((input_dim), np.float32, name = 'labels')
and call train_minibatch({'features': features, 'labels': labels})
or 
you can use a utility function like [in this example](https://github.com/Microsoft/CNTK/blob/master/bindings/python/examples/Sequence2Sequence/Sequence2Sequence.py#L34) (there's an example toward the end of the file where a model is being saved and loaded).

**Comment by kyu899** [comment]
Dear Nikos Karampatziakis:
Thank you for your answer. Now It works.

**Comment by edwardcho** [comment]
Hello All,
I also modified below code. But still i met some error... 
...
    lr_per_minibatch = learning_rate_schedule(0.5, UnitType.minibatch)
    # Instantiate the trainer object to drive the model training
    learner = sgd(another.parameters, lr=lr_per_minibatch)
    pp = ProgressPrinter(128)
    trainer = Trainer(another, (ce, pe), learner, pp)

    input = input_variable((input_dim), np.float32, name = 'features')
    label = input_variable((input_dim), np.float32, name = 'labels')

    for i in range(1024):
        features, labels = generate_random_data(minibatch_size, input_dim, num_output_classes)
        # Specify the mapping of input variables in the model to actual
        # minibatch data to be trained with
        trainer.train_minibatch({input: features, label: labels})
        #trainer.train_minibatch({'features': features, 'labels': labels})
        pp.update_with_trainer(trainer)
    pp.epoch_summary()
    test_features, test_labels = generate_random_data(minibatch_size, input_dim, num_output_classes)
    avg_error = trainer.test_minibatch({input: test_features, label: test_labels})
....

How to solve it??
