### ISSUE TITLE
while running the detection example，some problems occurs

### ISSUE THREAD

**Issue by sydtest** [Microsoft/CNTK#1107]
PS D:\CNTK-2-0-beta3-0-Windows-64bit-CPU-Only\cntk\Examples\Image\Detection\FastRCNN> python A1_GenerateInputROIs.py
Traceback (most recent call last):
  File "A1_GenerateInputROIs.py", line 5, in <module>
    import PARAMETERS
  File "D:\CNTK-2-0-beta3-0-Windows-64bit-CPU-Only\cntk\Examples\Image\Detection\FastRCNN\PARAMETERS.py", line 2, in <mo
dule>
    from cntk_helpers import *
  File "D:\CNTK-2-0-beta3-0-Windows-64bit-CPU-Only\cntk\Examples\Image\Detection\FastRCNN\cntk_helpers.py", line 5, in <
module>
    import selectivesearch
  File "D:\CNTK-2-0-beta3-0-Windows-64bit-CPU-Only\cntk\Examples\Image\Detection\FastRCNN\selectivesearch\__init__.py",
line 1, in <module>
    from .selectivesearch import selective_search
  File "D:\CNTK-2-0-beta3-0-Windows-64bit-CPU-Only\cntk\Examples\Image\Detection\FastRCNN\selectivesearch\selectivesearc
h.py", line 5, in <module>
    import skimage.feature
  File "D:\SoftWare\Anaconda3\lib\site-packages\skimage\feature\__init__.py", line 1, in <module>
    from ._canny import canny
  File "D:\SoftWare\Anaconda3\lib\site-packages\skimage\feature\_canny.py", line 16, in <module>
    import scipy.ndimage as ndi
  File "D:\SoftWare\Anaconda3\lib\site-packages\scipy\ndimage\__init__.py", line 172, in <module>
    from .filters import *
  File "D:\SoftWare\Anaconda3\lib\site-packages\scipy\ndimage\filters.py", line 37, in <module>
    from scipy.misc import doccer
  File "D:\SoftWare\Anaconda3\lib\site-packages\scipy\misc\__init__.py", line 47, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "D:\SoftWare\Anaconda3\lib\site-packages\scipy\special\__init__.py", line 586, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found

**Comment by sydtest** [comment]
uninstall numpy scipy skimage，download the whl file from http://www.lfd.uci.edu/~gohlke/pythonlibs/....use the command "pip install ***.whl" to install numpy scipy skimage.
