### ISSUE TITLE
CNTK_202_Language_Understanding sample (training error): NameError: name 'method' is not defined

### ISSUE THREAD

**Issue by malexan123** [Microsoft/CNTK#1123]
Hi, 

I set up CNTK on my Windows machine and I am trying to run the language understanding sample. https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_202_Language_Understanding.ipynb

I ran up to the do_train() call and I get the following. Can someone tell what might be going on based on the callstack? I am a new CNTK user.

Traceback (most recent call last):
  File "test.py", line 122, in <module>
    do_train()
  File "test.py", line 120, in do_train
    train(reader, model)
  File "test.py", line 77, in train
    lr_schedule = learning_rate_schedule(lr_per_minibatch, UnitType.minibatch, epoch_size)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\utils\swig_helper.py", line 56, in wrapper
    result = f(*args, **kwds)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\learner.py", line 189, in learning_rate_schedule
    return training_parameter_schedule(lr, epoch_size, unit)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\utils\swig_helper.py", line 56, in wrapper
    result = f(*args, **kwds)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\learner.py", line 151, in training_parameter_schedule
    str(method))
NameError: name 'method' is not defined

**Comment by raaaar** [comment]
This was fixed a while ago. Could you please update to the latest release?

**Comment by malexan123** [comment]
Yes, it fixed the issue. Forgot to close the issue earlier.
