### ISSUE TITLE
Evaluate dynamic axis in python.

### ISSUE THREAD

**Issue by simra** [Microsoft/CNTK#1162]
Hi all,
Is there a python example for scoring an LSTM with a dynamic label axis?  
I found this Brainscript example: https://github.com/Microsoft/CNTK/wiki/Express-a-softmax-over-a-dynamic-axis

When I score my data using conventional iteration over a test minibatch, I get this error:
````
Test data from file Test.txt successfully read
Traceback (most recent call last):
  File "\\tsclient\c\data_rsim\repex\dnnTrain2\20161206_URLEmbed\trainEvalSequenceEx.py", line 157, in <module>
    eval_sequence_classifier(input_dim,num_output_classes,trainer,classifier_output,label)
  File "\\tsclient\c\data_rsim\repex\dnnTrain2\20161206_URLEmbed\trainEvalSequenceEx.py", line 135, in eval_sequence_classifier
    eval_error = trainer.test_minibatch(arguments)
  File "e:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\trainer.py", line 126, in test_minibatch
    arguments = sanitize_var_map(self.model.arguments, arguments)
  File "e:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\utils\__init__.py", line 534, in sanitize_var_map
    sample_sizes = [len(v) for v in arguments.values()]
  File "e:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\utils\__init__.py", line 534, in <listcomp>
    sample_sizes = [len(v) for v in arguments.values()]
TypeError: object of type 'StreamInformation' has no len()
````

arguments:
````
arguments = {
                input: test_mb_source.streams.features,
                label: test_mb_source.streams.labels
            }
````
where features and label are defined in the trainer as 
````
features = input_variable(shape=input_dim, is_sparse=True)
    label = input_variable(num_output_classes, dynamic_axes=[
                           Axis.default_batch_axis()])
````

I'm not 100% confident that I'm setting up the arguments correctly- should the 'label' field in the arguments match an input node name?  If I don't have the label node from the trainer on hand, I get a different error:
````
Traceback (most recent call last):
  File "\\tsclient\c\data_rsim\repex\dnnTrain2\20161206_URLEmbed\trainEvalSequenceEx.py", line 157, in <module>
    eval_sequence_classifier(input_dim,num_output_classes,trainer,classifier_output)
  File "\\tsclient\c\data_rsim\repex\dnnTrain2\20161206_URLEmbed\trainEvalSequenceEx.py", line 133, in eval_sequence_classifier
    label: test_mb_source.streams.labels
NameError: name 'label' is not defined
````

**Comment by eldakms** [comment]
Please try on the latest master (or v2 official release). If you still have a problem there feel free to reopen. Please also provide more information (attaching the script would be nice). THanks!
