### ISSUE TITLE
no module named cntk._cntk_py on Arch Linux

### ISSUE THREAD

**Issue by RatanRSur** [Microsoft/CNTK#1194]
Using manual linux install, I took the following steps seeing as I already have g++ installed and openmpi installed with v>1.10:

* install anaconda from their website
* use anaconda's pip to pip install cpu only binary of cntk (I skipped the env setup because of something I saw in an email by @n17s 

I tried to run the FeedForward Tutorial test and got the following:
```
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.5/site-packages/cntk/cntk_py.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/opt/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'cntk._cntk_py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Tutorials/NumpyInterop/FeedForwardNet.py", line 10, in <module>
    from cntk.device import cpu, set_default_device
  File "/opt/anaconda/lib/python3.5/site-packages/cntk/__init__.py", line 11, in <module>
    from . import ops
  File "/opt/anaconda/lib/python3.5/site-packages/cntk/ops/__init__.py", line 8, in <module>
    from . import sequence
  File "/opt/anaconda/lib/python3.5/site-packages/cntk/ops/sequence/__init__.py", line 6, in <module>
    from ...utils import sanitize_input, sanitize_shape, get_data_type, typemap
  File "/opt/anaconda/lib/python3.5/site-packages/cntk/utils/__init__.py", line 14, in <module>
    from .. import cntk_py
  File "/opt/anaconda/lib/python3.5/site-packages/cntk/cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "/opt/anaconda/lib/python3.5/site-packages/cntk/cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "/opt/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /opt/anaconda/lib/python3.5/site-packages/scipy/sparse/../../../../libstdc++.so.6: version `CXXABI_1.3.8'not found (required by /usr/lib/openmpi/libmpi_cxx.so.1)
```

**Comment by alhabshi3k** [comment]
The same problem in Windows. I am running cntk-2.0 (beta9.0) on Python 3.5.2 Windows 7.
The installation process using PIP is Ok, where i am using WinPython distribution. but , i tried to run tutorials  Python Jupyter notebooks, specifically the first tutorial "CNTK_101_LogisticRegression.ipynb" and its first cell , then the error come out. 
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
I:\WinPython-64bit-3.5\python-3.5.2.amd64\lib\site-packages\cntk\cntk_py.py in swig_import_helper()
     17         try:
---> 18             return importlib.import_module(mname)
     19         except ImportError:

I:\WinPython-64bit-3.5\python-3.5.2.amd64\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

I:\WinPython-64bit-3.5\python-3.5.2.amd64\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

I:\WinPython-64bit-3.5\python-3.5.2.amd64\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

I:\WinPython-64bit-3.5\python-3.5.2.amd64\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

ImportError: No module named 'cntk._cntk_py'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-f0d76e7ab131> in <module>()
      5 import os
      6 # from cntk import Trainer, learning_rate_schedule, UnitType
----> 7 from cntk.learner import sgd
      8 from cntk.ops import *
      9 # Select the right target device when this notebook is being tested:

I:\WinPython-64bit-3.5\python-3.5.2.amd64\lib\site-packages\cntk\__init__.py in <module>()
      9 import numpy as np
     10 
---> 11 from .core import *
     12 from . import ops
     13 from . import cntk_py

I:\WinPython-64bit-3.5\python-3.5.2.amd64\lib\site-packages\cntk\core.py in <module>()
      8 from scipy import sparse
      9 
---> 10 from . import cntk_py
     11 from .device import use_default_device, cpu
     12 from .utils.swig_helper import typemap

I:\WinPython-64bit-3.5\python-3.5.2.amd64\lib\site-packages\cntk\cntk_py.py in <module>()
     19         except ImportError:
     20             return importlib.import_module('_cntk_py')
---> 21     _cntk_py = swig_import_helper()
     22     del swig_import_helper
     23 elif _swig_python_version_info >= (2, 6, 0):

I:\WinPython-64bit-3.5\python-3.5.2.amd64\lib\site-packages\cntk\cntk_py.py in swig_import_helper()
     18             return importlib.import_module(mname)
     19         except ImportError:
---> 20             return importlib.import_module('_cntk_py')
     21     _cntk_py = swig_import_helper()
     22     del swig_import_helper

I:\WinPython-64bit-3.5\python-3.5.2.amd64\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

ImportError: DLL load failed: The specified module could not be found.`

**Comment by yaronyg** [comment]
Please see the fix I mentioned in #1549. I fixed this issue for me.

**Comment by noraAAAAA** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cntk/cntk_py.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/qw/PycharmProjects/CNTK1/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cntk._cntk_py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qw/PycharmProjects/CNTK1/303/303.py", line 8, in <module>
    import cntk as C
  File "/usr/lib/python3.6/site-packages/cntk/__init__.py", line 13, in <module>
    from . import cntk_py
  File "/usr/lib/python3.6/site-packages/cntk/cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "/usr/lib/python3.6/site-packages/cntk/cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "/home/qw/PycharmProjects/CNTK1/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libmpi_cxx.so.1: cannot open shared object file: No such file or directory

**Comment by vamsinaveen** [comment]
I finally got this to work. Just had to add "C:\...\conda\envs" to my environment variables path. That did it!
Here's another post talking about it - https://stackoverflow.com/questions/45196010/import-cntk-works-from-command-line-but-not-in-pycharm
