### ISSUE TITLE
CUDNN error

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/CNTK#1218]
while running resnet with cifar I got this error:

```bash
cuDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=3 ; hostname=hoaphumanoid4gpulinux2 ; expr=cudnnSetTensorNdDescriptor(m_tensor, dataType, nbDims, dims, strides)
cuDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=2 ; hostname=hoaphumanoid4gpulinux2 ; expr=cudnnSetTensorNdDescriptor(m_tensor, dataType, nbDims, dims, strides)cuDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=1 ; hostname=hoaphumanoid4gpulinux2 ; expr=cudnnSetTensorNdDescriptor(m_tensor, dataType, nbDims, dims, strides)

Traceback (most recent call last):
  File "TrainResNet_CIFAR10_Distributed.py", line 181, in <module>
    train_and_evaluate(create_train_reader, test_reader, network_name, epochs, create_dist_learner, scale_up)
  File "TrainResNet_CIFAR10_Distributed.py", line 121, in train_and_evaluate
    updated=trainer.train_minibatch(data)                                 # update model with it
  File "/home/hoaphumanoid/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/cntk/trainer.py", line 90, in train_minibatch
    updated = super(Trainer, self).train_minibatch(arguments, device)
  File "/home/hoaphumanoid/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/cntk/cntk_py.py", line 1768, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: cuDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=1 ; hostname=hoaphumanoid4gpulinux2 ; expr=cudnnSetTensorNdDescriptor(m_tensor, dataType, nbDims, dims, strides)
Traceback (most recent call last):
  File "TrainResNet_CIFAR10_Distributed.py", line 181, in <module>
    train_and_evaluate(create_train_reader, test_reader, network_name, epochs, create_dist_learner, scale_up)
  File "TrainResNet_CIFAR10_Distributed.py", line 121, in train_and_evaluate
    updated=trainer.train_minibatch(data)                                 # update model with it
  File "/home/hoaphumanoid/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/cntk/trainer.py", line 90, in train_minibatch
    updated = super(Trainer, self).train_minibatch(arguments, device)
  File "/home/hoaphumanoid/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/cntk/cntk_py.py", line 1768, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: cuDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=3 ; hostname=hoaphumanoid4gpulinux2 ; expr=cudnnSetTensorNdDescriptor(m_tensor, dataType, nbDims, dims, strides)
Traceback (most recent call last):
  File "TrainResNet_CIFAR10_Distributed.py", line 181, in <module>
    train_and_evaluate(create_train_reader, test_reader, network_name, epochs, create_dist_learner, scale_up)
  File "TrainResNet_CIFAR10_Distributed.py", line 121, in train_and_evaluate
    updated=trainer.train_minibatch(data)                                 # update model with it
  File "/home/hoaphumanoid/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/cntk/trainer.py", line 90, in train_minibatch
    updated = super(Trainer, self).train_minibatch(arguments, device)
  File "/home/hoaphumanoid/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/cntk/cntk_py.py", line 1768, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: cuDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=2 ; hostname=hoaphumanoid4gpulinux2 ; expr=cudnnSetTensorNdDescriptor(m_tensor, dataType, nbDims, dims, strides)
```
any idea?

**Comment by miguelgfierro** [comment]
Found the problem:
```bash
sudo ln -s /usr/local/cudnn/include/cudnn.h /usr/local/cuda/include/cudnn.h
```
