### ISSUE TITLE
Error when running Text/CharacterLM of CNTK Examples

### ISSUE THREAD

**Issue by Alan-Lee123** [Microsoft/CNTK#1225]
I ran the char-rnn.py file in Text/CharacterLM of CNTK Examples but got an error.
ValueError: Invalid Value object; the data and mask are incompatible. The trailing dimensions of the data with shape [1 x 65] do not match the dimensions of the mask with shape [1 x 1]
I use windows 10 and cntk 2.0 beta7.0 with python 3.4
I tried to figure out the bug. Only to find that an error will always be triggered on the following situation.
`rnn.eval(([x], [False]))`
`rnn` means a Function representing a rnn.  `x` means the value of  parameters of `rnn`.

However, `rnn.eval(([x], [True]))` will not trigger an error.

Would you kindly tell me how to fix this error?

The code
https://github.com/Microsoft/CNTK/blob/master/Examples/Text/CharacterLM/char-rnn.py

 The whole error:
Traceback (most recent call last):
  File "<cntk folder>/Examples/Text/CharacterLM/char-rnn.py", line 231, in <module>
    train_lm("data/tinyshakespeare.txt")
  File "<cntk folder>/Examples/Text/CharacterLM/char-rnn.py", line 207, in train_lm
    print(sample(z, ix_to_char, vocab_dim, char_to_ix))
  File "<cntk folder>/Examples/Text/CharacterLM/char-rnn.py", line 92, in sample
    p = root.eval(arguments)
  File "<cntk-py34 folder>\lib\site-packages\cntk\ops\functions.py", line 199, in eval
    _, output_map = self.forward(arguments, self.outputs, device=device)
  File"<cntk-py34 folder>\lib\site-packages\cntk\utils\swig_helper.py", line 58, in wrapper
    result = f(*args, **kwds)
  File "<cntk-py34 folder>\lib\site-packages\cntk\ops\functions.py", line 272, in forward
    None, device)
  File ""<cntk-py34 folder>\lib\site-packages\cntk\utils\__init__.py", line 434, in sanitize_var_map
    batch = sanitize_batch(var, batch, seq_starts, device)
  File "<cntk-py34 folder>\lib\site-packages\cntk\utils\swig_helper.py", line 58, in wrapper
    result = f(*args, **kwds)
  File "<cntk-py34 folder>\lib\site-packages\cntk\utils\__init__.py", line 259, in sanitize_batch
    return Value.create(var, batch, seq_starts, device)
  File "<cntk-py34 folder>\lib\site-packages\cntk\utils\swig_helper.py", line 58, in wrapper
    result = f(*args, **kwds)
  File "<cntk-py34 folder>\lib\site-packages\cntk\utils\__init__.py", line 593, in create
    read_only)
ValueError: Invalid Value object; the data and mask are incompatible. The trailing dimensions of the data with shape [1 x 65] do not match the dimensions of the mask with shape [1 x 1]

**Comment by Alocaly** [comment]
Actually, there are more than this issue...
If you comment the print ( that is just a log ), there is another dimension match issue.
As you proposed, I could launch the program with always setting the mask to True ( and that is probably just plain wrong ).
But then it failed because it created epoch files from 1 to X, and try to read the epoch file number 0 :(
This is probably an easy issue to fix...
for the other ones, I really don't know :(

**Comment by Alocaly** [comment]
Note that actually the problems come with the beta 7.
The code is ok with beta 6 ( at least the training, I couldn't finish it, but the sample part should be easy to fix ).

**Comment by StephieX** [comment]
I had the same problem with beta 7.  I installed Windows beta 9 and it works now.
