### ISSUE TITLE
Load model trained by BS from Python interface

### ISSUE THREAD

**Issue by weixsong** [Microsoft/CNTK#1241]
Hi, 

I have trained a CNTK model by BS, and now I want to load the model by CNTK python interface, is that available? or python interface could only load model trained by python interface?

my  python code is: 
```python
from cntk import load_model

model_path = "E:\\ConvLACE_simple.dnn.91"
loaded_model = load_model(model_path, 'float')
```

But I got some error:
```
Traceback (most recent call last):
  File "load_model.py", line 4, in <module>
    loaded_model = load_model(model_path, 'float')
  File "E:\cntk\bindings\python\cntk\utils\swig_helper.py", line 58, in wrapper
    result = f(*args, **kwds)
  File "E:\cntk\bindings\python\cntk\ops\functions.py", line 573, in load_model
    return cntk_py.Function.load_model(filename, device)
NotImplementedError: Wrong number or type of arguments for overloaded function '
  Possible C/C++ prototypes are:
    CNTK::Function::LoadModel(std::wstring const &,CNTK::DeviceDescriptor const
    CNTK::Function::LoadModel(std::wstring const &)
```

And I see the load model function is empty:
```python
def Function_load_model(*args, **kwargs): # real signature unknown
    pass
```

thanks very much.

**Comment by cha-zhang** [comment]
You should be able to load BS trained models with Python. Have you tried just do: 
```
loaded_model = load_model(model_path)
```
The second argument of the function should be device, not type 'float'.

**Comment by mahilleb-msft** [comment]
This should be resolved. @weixsong - please re-open if the issue persists for you.

Thanks, Mark
