### ISSUE TITLE
char-rnn example is broken in Beta 10

### ISSUE THREAD

**Issue by ram3ai** [Microsoft/CNTK#1386]
Running Examples/Text/CharacterLM/char-rnn.py fails with

```
Traceback (most recent call last):
  File "char-rnn.py", line 229, in <module>
    train_lm("data/tinyshakespeare.txt")
  File "char-rnn.py", line 205, in train_lm
    print(sample(z, ix_to_char, vocab_dim, char_to_ix))
  File "char-rnn.py", line 92, in sample
    p = root.eval(arguments)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\ops\functions.py", line 214, in eval
    _, output_map = self.forward(arguments, self.outputs, device=device)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\utils\swig_helper.py", line 62, in wrapper
    result = f(*args, **kwds)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\ops\functions.py", line 295, in forward
    output_map[k] = variable_value_to_seq(output_map[k], k)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\utils\__init__.py", line 586, in variable_value_to_seq
    value_sequences = value.unpack_variable_value(variable, cpu())
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\cntk_py.py", line 1182, in unpack_variable_value
    return _cntk_py.Value_unpack_variable_value(self, *args)
RuntimeError: Value::UnpackVariableValue: Only Value objects containing the entire sequence (no segments) are supported.
```

It used to work in Beta 9.

**Comment by zhouwangzw** [comment]
Thanks for reporting the issue. It is now fixed in master. It will also available in next release (Beta 11).
Sorry for the inconvenience!

**Comment by tangyuq** [comment]
I am closing this issue for now. Please feel free to reopen it if you have further comments.
