### ISSUE TITLE
libmpi.so.12 not found

### ISSUE THREAD

**Issue by slaweku** [Microsoft/CNTK#1429]
Hi,
I have installed the v2b10 on Debian 8, apparently successfully. I activated my environment, again, it looked good. But when I run
python FeedForwardNet.py
I am getting:
Traceback (most recent call last):
  File "FeedForwardNet.py", line 10, in <module>
    from cntk.device import cpu, set_default_device
  File "/home/uber/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/__init__.py", line 11, in <module>
    from .core import *
  File "/home/uber/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/core.py", line 10, in <module>
    from . import cntk_py
  File "/home/uber/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "/home/uber/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "/home/uber/anaconda3/envs/cntk-py27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: libmpi.so.12: cannot open shared object file: No such file or directory

Regards,
Slawek

**Comment by slaweku** [comment]
Update: It turned out that the Open MPI was not installed by the installation script. When I did it manually (as per https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux#open-mpi) things started to work.
