### ISSUE TITLE
How to get to stream of composite MinibatchSource (in Python API)?

### ISSUE THREAD

**Issue by nSeck** [Microsoft/CNTK#1469]
Hey there,

I'm working on a regression problem with image input. Therefore I need in my CNTK-reader a composite MinibatchSource (shown in [(https://github.com/Microsoft/CNTK/wiki/Understanding-and-Extending-Readers#configuring-a-reader-minibatch-source-in-python)]) like
```
def create_reader(image_file, label_file, train):
    if not os.path.exists(image_file) or not os.path.exists(label_file):
        raise RuntimeError("One of the data files is missing!.")

    # transformation pipeline for the features
    transforms = []
    transforms += [
        ImageDeserializer.scale(width=image_width, height=image_height, channels=num_channels, interpolations='linear'),
    ]

    # deserializer Image + Regression Labels
    image_source = ImageDeserializer(image_file)
    image_source.ignore_labels()
    image_source.map_features('image', transforms)

    label_source = CTFDeserializer(label_file)
    label_source.map_input('labels', dim=num_labels, format="dense")
    
    # define a composite reader
    rc = ReaderConfig([image_source, label_source])
    reader = rc.minibatch_source()

    return reader
```
Now the question is, how do I get to the feature and label streams?
If I initialize the above defined reader with
```
reader_train = create_reader(image_file, label_file, True)
```
and try to call the streams
```
input_map = {
        input_var: reader_train.streams.features,
        label_var: reader_train.streams.labels
    }
```
following error is shown
```
Traceback (most recent call last):
  File "Images-landmarks_Kaggle.py", line 240, in <module>
    pred = train_and_evaluate(reader_train, reader_test, max_epochs=10, model_func=create_basic_model)
  File "Images-landmarks_Kaggle.py", line 137, in train_and_evaluate
    input_var: reader_train.streams.features,
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\cntk_py.py", line 2031, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, MinibatchSource, name)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\cntk_py.py", line 83, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'MinibatchSource' object has no attribute 'streams'
```

Is there an example where this is shown? And am I missing something or is there a bug?

**Comment by raaaar** [comment]
Hello,

The wiki article on the composite readers cites a FastRCNN example, which proceeds [as follows](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FastRCNN/A2_RunCntk_py3.py#L137):

 ```
   input_map = {
        image_input: minibatch_source[features_stream_name],
        roi_input: minibatch_source[roi_stream_name],
        label_input: minibatch_source[label_stream_name]
    }
```
In your case that would be:

```
input_map = {
        input_var: reader_train['image'],
        label_var: reader_train['labels']
    }
```

Alternatively, you could replace
```
rc = ReaderConfig([image_source, label_source])
reader = rc.minibatch_source()
return reader
```
with 
```
return MinibatchSource([image_source, label_source])
```

then, you should be able to create an input map as follows:
```
input_map = {
        input_var: reader.streams.image,
        label_var: reader.streams.labels
    }
```

**Comment by nSeck** [comment]
Thank you so much!
I tested both versions. I had to adjust the second one to my own reader like:
```
input_map = {
        input_var: reader_train.streams.image,
        label_var: reader_train.streams.labels
    }
```
Both alternatives work perfectly. I will also look into the given example asap.
