### ISSUE TITLE
How to set gpu_id on multi-GPU service(ValueError: Specified GPU device id (0) is invalid)

### ISSUE THREAD

**Issue by XiaotaoChen** [Microsoft/CNTK#1555]
i installed cntk(installation ways according  #1550 ) on my service with 4 Tesla  k40. i ran my code as follow steps:
```
1.source activate-cntk
2.python solver.py train,,,,,,,(with some other parameters)
``` 
then it broke with this info:`ValueError: Specified GPU device id (0) is invalid.`
due to my code:'set_default_device(gpu(0))'
To be honest,i don't know its' mean.looking for explaination on its' official Documents, But i can't find the explaination.can you tell me how to set gpu's id on my multi-GPU? my service detail info is listed in the end.

then i commented this line of`set_default_device(gpu(0))'.it broke with this info:
```
Traceback (most recent call last):
  File "solver.py", line 268, in <module>
    sys.exit(main())
  File "solver.py", line 256, in main
    train()
  File "solver.py", line 57, in train
    trainer.train_minibatch(data)  # update model with it
  File "/home/cxt/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/trainer.py", line 114, in train_minibatch
    device)
  File "/home/cxt/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 1993, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: Batch normalization training on CPU is not yet implemented.
```
it seems that i have to use gpu to run,what should i do to solve the two questions as shows above.
```

1. how to select gpu id on my multi-GPU service with api:set_default_device();

2.without this code:set_default_device(gpu(0))
will cntk use gpu wisely?how to solve the problem with'RuntimeError: Batch normalization training on CPU is not yet  implemented.'?
```
@Ark-kun 
the detail as follows:
```
root@stack24-51:~# nvidia-smi
Fri Mar  3 15:19:54 2017       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          Off  | 0000:02:00.0     Off |                  Off |
| N/A   29C    P8    19W / 235W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K40m          Off  | 0000:03:00.0     Off |                  Off |
| N/A   40C    P8    21W / 235W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K40m          Off  | 0000:82:00.0     Off |                  Off |
| N/A   29C    P8    19W / 235W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K40m          Off  | 0000:83:00.0     Off |                  Off |
| N/A   32C    P8    20W / 235W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by cha-zhang** [comment]
There is nothing wrong using set_default_device(gpu(0)). 

Could you please try the code here: 
https://cntk.ai/pythondocs/gettingstarted.html 
and see if everything works?

**Comment by XiaotaoChen** [comment]
i tried those codes as follows:
```
(/home/cxt/anaconda3/envs/cntk-py35) root@stack24-51:/home/cxt/cntk# python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cntk.device import set_default_device, gpu
>>> set_default_device(gpu(0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cxt/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/device.py", line 76, in gpu
    return cntk_py.DeviceDescriptor.gpu_device(device_id)
ValueError: Specified GPU device id (0) is invalid.
>>>
```
cuda7.5 was installed on my service, i use the latest cntk with GPU version. which compiled with cuda8. can you help me to solve this problem?

**Comment by savvyGirl30** [comment]
I am getting the same error as XiaotaoChen

**Comment by cha-zhang** [comment]
Is it possible you installed CPU-only version of CNTK?

**Comment by youssefhb** [comment]
I'm getting the same issue. I have compiled the a CNTK GPU  build.
I'm getting this error : 
ValueError: Specified GPU device id (0) is invalid

**Comment by raaaar** [comment]
The latest master has new functionality to log all available GPU devices. Could somebody please try building the GPU version of the master and report the output of `python -c "import cntk; cntk.logging.set_trace_level(2); cntk.all_devices()"` here? It should look similar to this:

```
-------------------------------------------------------------------
GPU info:

                Device[0]: cores = 192; computeCapability = 3.0; type = "Quadro K600"; total memory = 1024 MB; free memory = 125 MB
-------------------------------------------------------------------
```

**Comment by Sadler2** [comment]
@XiaotaoChen 352.39 video driver is not recommended to use with CUDA 8.

**Comment by wolfma61** [comment]
no follow-up for a long time, please open a new issue if you experience this in a more recent CNTK installation
