### ISSUE TITLE
Construction of Learner fails when working with sequences/LSTMs

### ISSUE THREAD

**Issue by nSeck** [Microsoft/CNTK#1611]
I'm working on a regression problem on video/image sequence data with Python API.
Input data is a (minibatch_size x sequence_length x channel x height x width)-tensor with (at this time) fixed minibatch_size = 1, sequence_length = 3 and only 1 channel.
My train function is constructed as follows:

```
    # Input variables denoting the features and label data
    input_var = input_variable((num_channels, image_height, image_width), np.float32)
    label_var = input_variable(num_output_classes, np.float32)

    # Instantiate 2D Convolution network with LSTM
    z = model_func(input_var, out_dims=num_output_classes)

    # loss and metric
    loss = squared_error(z, label_var)
    error = squared_error(z, label_var)
    
    ################
    # Train Action #
    ################

    # training config
    epoch_size     = 50                             # epoch size = size of train set
    minibatch_size = 1                              # each minibatch holds one sequence
    
    # Set training parameters
    lr_per_minibatch       = learning_rate_schedule(0.5, UnitType.minibatch)
    
    # trainer object
    learner  = sgd(z.parameters, lr_per_minibatch)
    trainer  = Trainer(z, (loss, error), [learner], progress_printer)
```
But the construction of the learner seems to fail. From the Call Stack I suspect that there is some problem with getting the sequence length, but how does this affect the learner construction?
```
Traceback (most recent call last):
  File "Conv2D_300VW_v9.py", line 516, in <module>
    reset_model   = True)
  File "Conv2D_300VW_v9.py", line 371, in train_and_evaluate
    learner = sgd(z.parameters,lr_per_minibatch)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\utils\swig_helper.py", line 62, in wrapper
    result = f(*args, **kwds)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\learner.py", line 416, in sgd
    return cntk_py.sgd_learner(parameters, lr, additional_options)

ValueError: Cannot create an NDArrayView using a view shape that has unknown dimensions for any of its axes!

[CALL STACK]
    > CNTK::NDArrayView::  DeepClone
    - CNTK::NDArrayView::NDArrayView<double>
    - CNTK::NDArrayView::  NDArrayView
    - CNTK::Value::  GetSequenceStartsAndLengths
    - CNTK::Value::  GetSequenceStartsAndLengths
    - CNTK::Variable::operator std::shared_ptr<CNTK::Function>
    - CNTK::Value::  GetSequenceStartsAndLengths
    - RtlRunOnceExecuteOnce
    - InitOnceExecuteOnce
    - _crtInitOnceExecuteOnce
    - CNTK::Value::  GetSequenceStartsAndLengths
    - CNTK::Variable::  Value
    - CNTK::Internal::  SaveAsLegacyModel
    - CNTK::  AdamLearner
    - CNTK::Internal::  ZeroesWithDynamicAxesLike
    - CNTK::Internal::  ZeroesWithDynamicAxesLike
```
Adding one dynamic axis for batch construction  and one dynamic axis for sequence dimension has the same result.

```
input_axes = [Axis.default_batch_axis(), Axis.default_dynamic_axis()]
input_var = input_variable((num_channels, image_height, image_width), dynamic_axes=input_axes, dtype=np.float32)

 # Instantiate 2D Convolution network with LSTM
z = model_func(input_var, out_dims = num_output_classes)
label_var = input_variable(num_output_classes, dynamic_axes=z.dynamic_axes, dtype=np.float32)
```

Any help would be appreciated.
Thanks!

PS: The whole network definition and input method is attached (in Python).
[Conv2D_300VW_v9.txt](https://github.com/Microsoft/CNTK/files/844723/Conv2D_300VW_v9.txt)

**Comment by nSeck** [comment]
Still struggling with this issue. Is there no one who can give me a hint on that? Besides, in beta 15 the error message changed to 
` ValueError: Cannot create an NDArrayView using a view shape '[? x 26]' that has unknown dimensions for any of its axes.`
where `num_output_classes = 26`.

**Comment by nSeck** [comment]
Got it finally on my own.
Following/Similar code snippets have to be added for LSTMs in general:

```
# Define create_criterion_function
def create_criterion_function(model):
    labels = Placeholder(name='labels')
    loss   = squared_error(model, labels)
    error = sqrt(constant(1/num_landmarks) * loss)

    return combine ([loss, error]) # (features, labels) -> (loss, metric)

    batch_axis = Axis.default_batch_axis()
    input_seq_axis = Axis.default_dynamic_axis()
```
```
# construct input variables
input_dynamic_axes = [batch_axis, input_seq_axis]

input_var = input_variable(shape=(video_channel_count, video_height, video_width),
                                dynamic_axes=input_dynamic_axes, dtype=np.float32)
label_var = input_variable(shape=(num_landmarks),
                                dynamic_axes=input_dynamic_axes, dtype=np.float32)

z = model_func(input_var, out_dims = num_landmarks)
```
```
criterion = create_criterion_function(z)

# replace criterion placeholders
criterion.replace_placeholders({criterion.placeholders[0]: input_var,
                                criterion.placeholders[1]: label_var})
```
In this example time steps / sequence length are the same for input and output, and therefore get the same dynamic axis.
