### ISSUE TITLE
Cannot import cntk after update to cntk-2.0.beta15.0

### ISSUE THREAD

**Issue by aFuerst** [Microsoft/CNTK#1615]
When importing cntk it throws this ImportError. It started after I updated cntk to the newest version. Running on Windows 10 both in powershell and pyscripter

Traceback (most recent call last):
  File "c:\repos\cntk\bindings\python\cntk\cntk_py.py", line 15, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'cntk._cntk_py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\repos\cntk\bindings\python\cntk\__init__.py", line 10, in <module>
    from .core import *
  File "c:\repos\cntk\bindings\python\cntk\core.py", line 11, in <module>
    from . import cntk_py
  File "c:\repos\cntk\bindings\python\cntk\cntk_py.py", line 18, in <module>
    _cntk_py = swig_import_helper()
  File "c:\repos\cntk\bindings\python\cntk\cntk_py.py", line 17, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by mahilleb-msft** [comment]
Hi @aFuerst, I think you may have the PYTHONPATH environment variable set up from previously setting up CNTK build from source. Can you try unsetting? Unfortunately, PYTHONPATH, if it's there, it will take precedence over the CNTK version installed through binary installation.

Thanks, Mark

**Comment by aFuerst** [comment]
Removing that from the path solved it, thank you!

**Comment by zsong** [comment]
Same error. I installed everything under Python 3.5 virtual environment. I got same error when I tried to install the samples. I can see the modules are installed in the correct folder

myenv3.5\Lib\site-packages

03/27/2017  05:07 PM    <DIR>          cntk
03/27/2017  05:07 PM    <DIR>          cntk-2.0.beta15.0.dist-info
03/27/2017  05:07 PM        30,961,664 _cntk_py.cp35-win_amd64.pdb
03/27/2017  05:07 PM         4,692,992 _cntk_py.cp35-win_amd64.pyd

**Comment by Swordsemperor** [comment]
Hey @mahilleb-msft   I met the same error. But there  is no PYTHONPATH environment variable in my system. Could you help me? 
Thank you. 
![Uploading environmentVariable.PNG…]()
![error](https://cloud.githubusercontent.com/assets/25994638/24498394/ed6a0584-1570-11e7-8b89-f101a7a909bc.PNG)
