### ISSUE TITLE
cuDNN failure 9: CUDNN_STATUS_NOT_SUPPORTED  in Resnet

### ISSUE THREAD

**Issue by xuegedeng** [Microsoft/CNTK#1659]
I use CNTK with my speech recognition work. I build an acoustic model with the Resnet , in the training step, I set the  minibatchsize as 256, it works well.  But when I use the  write command to write the posterior for kaldi decode , it reads the whole utterance one time. thus, for long utterance like 1028 frames , it will fail with this log:

evaluate: reading 1028 frames of AMI_EN2002a_H01_FEO070_0100130_0101160
cuDNN failure 9: CUDNN_STATUS_NOT_SUPPORTED ; GPU=1 ; hostname=g10 ; expr=cudnnBatchNormalizationForwardInference(*m_cudnn, mode, &C::One, &C::Zero, m_inOutCuDnnT, ptr(in), m_inOutCuDnnT, ptr(out), m_scaleBiasCuDnnT, ptr(scale), ptr(bias), ptr(runMean), ptr(runVariance), epsilon)
Closed Kaldi writer

Adding minibatchSize=256 in the write config doesn't seem to work.
I try to run the write command on CPU by setting the deviceId=-1, but it will still use GPU and fail the same way, why is this happen?
Anyone can help me ? Thank you very much.

**Comment by sebastiankochman** [comment]
Not sure if it's directly related, but I see a similar error when I add MaxPooling or GlobalMaxPooling layer to my model, after a Convolution layer... the input of the network is a sequence of sparse matrices (representing utterances). Convolution/MaxPooling is per utterance, which is fed later into an LSTM.

I couldn't find any workaround to get rid of this error. Any recommendations?

  [...]
  File "C:\Program Files\Python35\lib\site-packages\cntk\cntk_py.py", line 2327, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: cuDNN failure 9: CUDNN_STATUS_NOT_SUPPORTED ; GPU=1 ; hostname=[...] ; expr=cudnnPoolingForward(*m_cudnn, *(m_pool), &C::One, m_inT, ptr(in),
 &C::Zero, m_outT, ptr(out))

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::DataTransferer::  operator=
    - Microsoft::MSR::CNTK::DataTransferer::  operator=
    - CNTK::DeviceDescriptor::  UseDefaultDevice
    - Microsoft::MSR::CNTK::DataTransferer::  operator=
    - CNTK::DeviceDescriptor::  UseDefaultDevice
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfSamplesSeen
    - CNTK::Trainer::  TrainMinibatch
    - PyInit__cntk_py
    - PyInit__cntk_py
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx

**Comment by yuxiaoguo** [comment]
Hi, @sebastiankochman 
Have you ever tried to use AveragePooling instead of MaxPolling? Does the network report the identity error? And also, can you check the parameter **include_pad** is true or false?

**Comment by sebastiankochman** [comment]
@yuxiaoguo I'm getting the same error for both Max and AveragePooling, both with **pad** set to true or false (either in Convolution or *Pooling layer). I also experimented with various filter sizes, always resulting in the same error.

Note that my scenario is NLP, so the result of a single Convolution filter is a matrix of shape 1xN (if padding is enabled and stride is 1, then N is the number of tokens). So then in MaxPooling I was trying filter shapes like (1,3). Just mentioning it in case the shape of the matrix is somehow relevant to this bug...

**Comment by yuxiaoguo** [comment]
@sebastiankochman Thanks for your feedback. At first glance, I thought it might relate to the include/exclude parameter of Pooling (for Max pooling could not use include padding.) However, it seems no relationship between them from your description. Hope others could help you to target the exception.

**Comment by ivannp** [comment]
I am getting the same stack when I use a GPU. Tried switching to average pooling - same result.

cuDNN failure 9: CUDNN_STATUS_NOT_SUPPORTED ; GPU=0 ; hostname=cntk ; expr=cudnnPoolingForward(*m_cudnn, *(m_pool), &C::One, m_inT, ptr(in), &C::Zero, m_outT, ptr(out))
Traceback (most recent call last):
  File "wfl_cntk.py", line 428, in <module>
    main()            # Save results to a database or somewhere else
  File "wfl_cntk.py", line 425, in main
    returns_wfl()
  File "wfl_cntk.py", line 418, in returns_wfl
    ml.run(features, response, fl, verbose=False, pool_size=1)
  File "wfl_cntk.py", line 188, in run
    self.run_step(ii)
  File "wfl_cntk.py", line 99, in run_step
    fore = self.cntk_fit_predict(xx, yy, fore_xx)
  File "wfl_cntk.py", line 267, in cntk_fit_predict
    trainer.train_minibatch({input : features, label : labels})
  File "/home/ivannp/anaconda3/envs/cntk36/lib/python3.6/site-packages/cntk/train/trainer.py", line 171, in train_minibatch
    device)
  File "/home/ivannp/anaconda3/envs/cntk36/lib/python3.6/site-packages/cntk/cntk_py.py", line 2327, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: cuDNN failure 9: CUDNN_STATUS_NOT_SUPPORTED ; GPU=0 ; hostname=cntk ; expr=cudnnPoolingForward(*m_cudnn, *(m_pool), &C::One, m_inT, ptr(in), &C::Zero, m_outT, ptr(out))

[CALL STACK]
[0x7fe0b34dc4ec]                                                       + 0x4be4ec
[0x7fe0b081039f]    Microsoft::MSR::CNTK::CuDnnConvolutionEngine<float>::  ForwardPoolingCore  (Microsoft::MSR::CNTK::Matrix<float> const&,  Microsoft::MSR::CNTK::Matrix<float>&) + 0x11f
[0x7fe0b36bed61]    Microsoft::MSR::CNTK::PoolingNode<float>::  ForwardProp  (Microsoft::MSR::CNTK::FrameRange const&) + 0x61
[0x7fe0b37c4464]    Microsoft::MSR::CNTK::ComputationNetwork::PARTraversalFlowControlNode::  ForwardProp  (std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&,  Microsoft::MSR::CNTK::FrameRange const&) + 0xc4
[0x7fe0b366ffd5]    std::_Function_handler<void (std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&),void Microsoft::MSR::CNTK::ComputationNetwork::ForwardProp<std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>>>(std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>> const&)::{lambda(std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&)#1}>::  _M_invoke  (std::_Any_data const&,  std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&) + 0x35
[0x7fe0b3695edd]    void Microsoft::MSR::CNTK::ComputationNetwork::  TravserseInSortedGlobalEvalOrder  <std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>>>(std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>> const&,  std::function<void (std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&)> const&) + 0x3ed
[0x7fe0b3666e98]    CNTK::CompositeFunction::  Forward  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&) + 0x7d8
[0x7fe0b362db61]    CNTK::Function::  Forward  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&) + 0x81
[0x7fe0b36cf950]    CNTK::Trainer::  ExecuteForwardBackward  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&) + 0x250
[0x7fe0b36d04b3]    CNTK::Trainer::  TrainLocalMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  bool,  CNTK::DeviceDescriptor const&) + 0xd3
[0x7fe0b36d1174]    CNTK::Trainer::  TrainMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&) + 0x44
[0x7fe0b36d1270]    CNTK::Trainer::  TrainMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  CNTK::DeviceDescriptor const&) + 0xa0
[0x7fe0b3fc21e7]                                                       + 0x1981e7
[0x7fe0bd9aa179]    PyCFunction_Call                                   + 0x119
[0x7fe0bda35cc2]    _PyEval_EvalFrameDefault                           + 0x6262
[0x7fe0bda2da60]                                                       + 0x146a60
[0x7fe0bda2f48a]                                                       + 0x14848a
[0x7fe0bda3215d]    _PyEval_EvalFrameDefault                           + 0x26fd
[0x7fe0bda2da60]                                                       + 0x146a60
[0x7fe0bda2f48a]                                                       + 0x14848a
[0x7fe0bda3215d]    _PyEval_EvalFrameDefault                           + 0x26fd
[0x7fe0bda2ce74]                                                       + 0x145e74
[0x7fe0bda2f5e8]                                                       + 0x1485e8
[0x7fe0bda3215d]    _PyEval_EvalFrameDefault                           + 0x26fd
[0x7fe0bda2da60]                                                       + 0x146a60
[0x7fe0bda2f48a]                                                       + 0x14848a
[0x7fe0bda3215d]    _PyEval_EvalFrameDefault                           + 0x26fd
[0x7fe0bda2da60]                                                       + 0x146a60
[0x7fe0bda2f48a]                                                       + 0x14848a
[0x7fe0bda318dd]    _PyEval_EvalFrameDefault                           + 0x1e7d
[0x7fe0bda2ce74]                                                       + 0x145e74
[0x7fe0bda2f5e8]                                                       + 0x1485e8
[0x7fe0bda3215d]    _PyEval_EvalFrameDefault                           + 0x26fd
[0x7fe0bda2ce74]                                                       + 0x145e74
[0x7fe0bda2f5e8]                                                       + 0x1485e8
[0x7fe0bda3215d]    _PyEval_EvalFrameDefault                           + 0x26fd
[0x7fe0bda2da60]                                                       + 0x146a60
[0x7fe0bda2dee3]    PyEval_EvalCodeEx                                  + 0x63
[0x7fe0bda2df2b]    PyEval_EvalCode                                    + 0x3b
[0x7fe0bda606c0]    PyRun_FileExFlags                                  + 0x130
[0x7fe0bda61c83]    PyRun_SimpleFileExFlags                            + 0x173
[0x7fe0bda7d0b5]    Py_Main                                            + 0xe25
[0x400c1d]          main                                               + 0x16d
[0x7fe0bca09830]    __libc_start_main                                  + 0xf0
[0x4009e9]

**Comment by n17s** [comment]
CuDNN does not support pooling over vectors (1d tensors). This is probably the root cause for everyone reporting issues on this thread.

A simple workaround is to reshape the input to have an additional axis with size 1. This axis will need to be a spatial axis. So if you have an input of shape `(dim, number_of_spatial_positions)`, where `dim` is the dimension of the vector you want to have for each position, you need to reshape it to `(dim, number_of_spatial_positions, 1)`, apply pooling, and then reshape back to get rid of the trailing axis.

Feel free to reopen if you have additional questions.
