### ISSUE TITLE
TransferLearning missing unix_text (probably solved) & exception while training

### ISSUE THREAD

**Issue by roger77** [Microsoft/CNTK#1661]
` python install_data_and_model.py` results in `FileNotFoundError: [Errno 2] No such file or directory: '/home/user/cntk/Examples/Image/DataSets/Grocery/../grocery/test_unix.txt'`

to fix it I had manually rename test.txt as test_unix.txt

Now while running ` python TransferLearning.py` I got the following error:

`user@ggpu1:~/cntk/Examples/Image/TransferLearning$ python TransferLearning.py
-------------------------------------------------------------------
Build info:

                Built time: Mar 15 2017 10:46:23
                Last modified date: Wed Mar 15 10:45:35 2017
                Build type: release
                Build target: GPU
                With 1bit-SGD: yes
                With ASGD: yes
                Math lib: mkl
                CUDA_PATH: /usr/local/cuda-8.0
                CUB_PATH: /usr/local/cub-1.4.1
                CUDNN_PATH: /usr/local/cudnn-5.1
                Build Branch: HEAD
                Build SHA1: 5afa98d8fff696cf7bcf041b75efb744a489b47e
                Built by Source/CNTK/buildinfo.h$$0 on 84ac7e3c2906
                Build Path: /home/philly/jenkins/workspace/CNTK-Build-Linux
                MPI distribution: Open MPI
                MPI version: 1.10.3
-------------------------------------------------------------------
Training transfer learning model for 20 epochs (epoch_size = 6149).
Training 15949478 parameters in 68 parameter tensors.
Processed 5000 samples
Finished Epoch[1 of 20]: [Training] loss = 1.911448 * 6149, metric = 44.12% * 6149 32.835s (187.3 samples/s);
Processed 5000 samples
Finished Epoch[2 of 20]: [Training] loss = 0.394768 * 6149, metric = 11.47% * 6149 27.636s (222.5 samples/s);
^CTraceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.5/site-packages/cntk/cntk_py.py", line 2087, in __hash__
    return _cntk_py.StreamInformation___hash__(self)
TypeError: in method 'StreamInformation___hash__', argument 1 of type 'CNTK::StreamInformation *'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TransferLearning.py", line 214, in <module>
    max_epochs, freeze=freeze_weights)
  File "TransferLearning.py", line 126, in train_model
    data = minibatch_source.next_minibatch(min(mb_size, epoch_size-sample_count), input_map=input_map)
  File "/home/user/anaconda3/lib/python3.5/site-packages/cntk/internal/swig_helper.py", line 63, in wrapper
    result = f(*args, **kwds)
  File "/home/user/anaconda3/lib/python3.5/site-packages/cntk/io/__init__.py", line 213, in next_minibatch
    minibatch_size_in_samples, num_data_partitions, partition_index, device)
  File "/home/user/anaconda3/lib/python3.5/site-packages/cntk/cntk_py.py", line 2229, in get_next_minibatch
    return _cntk_py.MinibatchSource_get_next_minibatch(self, *args)
SystemError: <built-in function MinibatchSource_get_next_minibatch> returned a result with an error set`

Any idea?

Thanks

**Comment by roger77** [comment]
Not sure what happened. I simply rerun the training command and now it works without problem.

`user@ggpu1:~/cntk/Examples/Image/TransferLearning$ python TransferLearning.py
-------------------------------------------------------------------
Build info:

                Built time: Mar 15 2017 10:46:23
                Last modified date: Wed Mar 15 10:45:35 2017
                Build type: release
                Build target: GPU
                With 1bit-SGD: yes
                With ASGD: yes
                Math lib: mkl
                CUDA_PATH: /usr/local/cuda-8.0
                CUB_PATH: /usr/local/cub-1.4.1
                CUDNN_PATH: /usr/local/cudnn-5.1
                Build Branch: HEAD
                Build SHA1: 5afa98d8fff696cf7bcf041b75efb744a489b47e
                Built by Source/CNTK/buildinfo.h$$0 on 84ac7e3c2906
                Build Path: /home/philly/jenkins/workspace/CNTK-Build-Linux
                MPI distribution: Open MPI
                MPI version: 1.10.3
-------------------------------------------------------------------
Training transfer learning model for 20 epochs (epoch_size = 6149).
Training 15949478 parameters in 68 parameter tensors.
Processed 5000 samples
Finished Epoch[1 of 20]: [Training] loss = 1.873004 * 6149, metric = 43.15% * 6149 32.932s (186.7 samples/s);
Processed 5000 samples
Finished Epoch[2 of 20]: [Training] loss = 0.365612 * 6149, metric = 10.94% * 6149 27.808s (221.1 samples/s);
Processed 5000 samples
Finished Epoch[3 of 20]: [Training] loss = 0.120651 * 6149, metric = 3.29% * 6149 27.824s (221.0 samples/s);
Processed 5000 samples
Finished Epoch[4 of 20]: [Training] loss = 0.042951 * 6149, metric = 1.09% * 6149 27.842s (220.9 samples/s);
Processed 5000 samples
Finished Epoch[5 of 20]: [Training] loss = 0.016274 * 6149, metric = 0.39% * 6149 27.791s (221.3 samples/s);
Processed 5000 samples
Finished Epoch[6 of 20]: [Training] loss = 0.006539 * 6149, metric = 0.10% * 6149 27.862s (220.7 samples/s);
Processed 5000 samples
Finished Epoch[7 of 20]: [Training] loss = 0.002508 * 6149, metric = 0.03% * 6149 27.853s (220.8 samples/s);
Processed 5000 samples
Finished Epoch[8 of 20]: [Training] loss = 0.002363 * 6149, metric = 0.05% * 6149 27.867s (220.7 samples/s);
Processed 5000 samples
Finished Epoch[9 of 20]: [Training] loss = 0.001662 * 6149, metric = 0.02% * 6149 27.886s (220.5 samples/s);
Processed 5000 samples
Finished Epoch[10 of 20]: [Training] loss = 0.001630 * 6149, metric = 0.02% * 6149 27.899s (220.4 samples/s);
Processed 5000 samples
Finished Epoch[11 of 20]: [Training] loss = 0.001648 * 6149, metric = 0.02% * 6149 27.919s (220.2 samples/s);
Processed 5000 samples
Finished Epoch[12 of 20]: [Training] loss = 0.001316 * 6149, metric = 0.02% * 6149 27.871s (220.6 samples/s);
Processed 5000 samples
Finished Epoch[13 of 20]: [Training] loss = 0.001518 * 6149, metric = 0.03% * 6149 27.865s (220.7 samples/s);
Processed 5000 samples
Finished Epoch[14 of 20]: [Training] loss = 0.001506 * 6149, metric = 0.02% * 6149 27.822s (221.0 samples/s);
Processed 5000 samples
Finished Epoch[15 of 20]: [Training] loss = 0.001424 * 6149, metric = 0.02% * 6149 27.768s (221.4 samples/s);
Processed 5000 samples
Finished Epoch[16 of 20]: [Training] loss = 0.001344 * 6149, metric = 0.02% * 6149 27.876s (220.6 samples/s);
Processed 5000 samples
Finished Epoch[17 of 20]: [Training] loss = 0.001553 * 6149, metric = 0.03% * 6149 27.846s (220.8 samples/s);
Processed 5000 samples
Finished Epoch[18 of 20]: [Training] loss = 0.001490 * 6149, metric = 0.02% * 6149 27.863s (220.7 samples/s);
Processed 5000 samples
Finished Epoch[19 of 20]: [Training] loss = 0.001526 * 6149, metric = 0.02% * 6149 27.820s (221.0 samples/s);
Processed 5000 samples
Finished Epoch[20 of 20]: [Training] loss = 0.001369 * 6149, metric = 0.02% * 6149 27.774s (221.4 samples/s);
Stored trained model at /home/user/cntk/Examples/Image/TransferLearning/Output/TransferLearning.model
Evaluating model output node prediction for 1020 images.
Processed 100 samples (0.87 correct)
Processed 200 samples (0.895 correct)
Processed 300 samples (0.91 correct)
Processed 400 samples (0.915 correct)
Processed 500 samples (0.916 correct)
Processed 600 samples (0.9266666666666666 correct)
Processed 700 samples (0.9257142857142857 correct)
Processed 800 samples (0.93 correct)
Processed 900 samples (0.9355555555555556 correct)
Processed 1000 samples (0.936 correct)
956 of 1020 prediction were correct 0.9372549019607843.
Done. Wrote output to /home/user/cntk/Examples/Image/TransferLearning/Output/predOutput.txt`
