### ISSUE TITLE
Can not run CNTK transferlearning example　

### ISSUE THREAD

**Issue by yuanweilei** [Microsoft/CNTK#1668]
When I run TransferLearning.py, error messages are shown as follow:
Traceback (most recent call last):
  File "TransferLearning.py", line 198, in <module>
    set_default_device(gpu(0))
  File "C:\Anaconda3\lib\site-packages\cntk\device.py", line 76, in gpu
    return cntk_py.DeviceDescriptor.gpu_device(device_id)
ValueError: Specified GPU device id (0) is invalid.

Does CNTK-GPU version is necessary for running this sample?
(I only install CNTK-CPU-v2beta12 and I do not have a GPU device in my compute.)

**Comment by thilow** [comment]
Please try:
set_default_device(cpu())

**Comment by yuanweilei** [comment]
@thilow Thank you! But when I use set_default_device(cpu()), error message as follow:

Traceback (most recent call last):
  File "TransferLearning.py", line 199, in <module>
    set_default_device(cpu())
NameError: name 'cpu' is not defined

**Comment by yuanweilei** [comment]
@thilow Thank you! But when I use set_default_device(cpu()), error message as follow:
    RuntimeError: Batch normalization training on CPU is not yet implemented.

Traceback (most recent call last):
  File "TransferLearning.py", line 216, in <module>
    max_epochs, freeze=freeze_weights)
  File "TransferLearning.py", line 127, in train_model
    trainer.train_minibatch(data)                                    # update model with it
  File "C:\Anaconda3\lib\site-packages\cntk\trainer.py", line 120, in train_minibatch
    arguments, device)
  File "C:\Anaconda3\lib\site-packages\cntk\cntk_py.py", line 2022, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
RuntimeError: Batch normalization training on CPU is not yet implemented.

**Comment by yuanweilei** [comment]
I rent a NC6 Azure VM to run transferlearning example and successed.
