### ISSUE TITLE
Can I train TransferLearning model by CPU-only using a AlexNet base model?

### ISSUE THREAD

**Issue by yuanweilei** [Microsoft/CNTK#1680]
You can use [AlexNet](https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Classification/AlexNet#pre-trained-models) model as a base model to train TransferLearning, error messages as follow:
(I use  ` set_default_device(cpu())` because I want to use CPU-only if possible.)

Traceback (most recent call last):
  File "TransferLearning_Extended.py", line 87, in <module>
    len(class_mapping), train_map_file, num_epochs=30, freeze=True)
  File "C:\CNTK\cntk\Examples\Image\TransferLearning\TransferLearning.py", line 110, in train_model
    tl_model = create_model(base_model_file, feature_node_name, last_hidden_node_name, num_classes, image_input, freeze)
  File "C:\CNTK\cntk\Examples\Image\TransferLearning\TransferLearning.py", line 73, in create_model
    base_model   = load_model(base_model_file)
  File "C:\Anaconda3\lib\site-packages\cntk\utils\swig_helper.py", line 62, in wrapper
    result = f(*args, **kwds)
  File "C:\Anaconda3\lib\site-packages\cntk\ops\functions.py", line 753, in load_model
    return Function.load(filename, device)
  File "C:\Anaconda3\lib\site-packages\cntk\utils\swig_helper.py", line 62, in wrapper
    result = f(*args, **kwds)
  File "C:\Anaconda3\lib\site-packages\cntk\ops\functions.py", line 746, in load
    return cntk_py.Function.load_model(filename, device)
RuntimeError: Reading a DictionaryValue as the wrong type; Reading as type class CNTK::Axis when actual type is Vector

[CALL STACK]
    > CNTK::NDMask::  MaskedCount
    - CNTK::NDMask::  MaskedCount
    - CNTK::Function::  ~Function
    - CNTK::  MPICommunicator
    - RtlRunOnceExecuteOnce
    - InitOnceExecuteOnce
    - _crtInitOnceExecuteOnce
    - CNTK::  MPICommunicator
    - CNTK::Function::  RawOutputs
    - CNTK::DeviceDescriptor::  UseDefaultDevice
    - CNTK::Function::  Deserialize
    - CNTK::Function::  LoadModel
    - PyInit__cntk_py
    - PyInit__cntk_py
    - PyCFunction_Call
    - PyEval_GetFuncDesc

**Comment by pkranen** [comment]
Please try with this version of AlexNet: [https://www.cntk.ai/Models/AlexNet/AlexNet.model](https://www.cntk.ai/Models/AlexNet/AlexNet.model). Thanks.

**Comment by yuanweilei** [comment]
@pkranen Thank you very much!
Now I can run TransferLearning.py with AlexNet: https://www.cntk.ai/Models/AlexNet/AlexNet.model.
