### ISSUE TITLE
No Permission for /var/lock Runtime Error

### ISSUE THREAD

**Issue by Energyquantum** [Microsoft/CNTK#1719]
Hi, 

I was trying to run the example "[FeedForwardNet.py](https://github.com/Microsoft/CNTK/blob/master/Tutorials/NumpyInterop/FeedForwardNet.py)" under "CNTK-Samples-2-0rc1/Tutorials/NumpyInterop" by "python FeedForwardNet.py" on a cluster. But the following errors occurred.

```
Traceback (most recent call last):
  File "FeedForwardNet.py", line 85, in <module>
    error = ffnet()
  File "FeedForwardNet.py", line 52, in ffnet
    feature, num_output_classes, hidden_layers_dim, num_hidden_layers, sigmoid)
  File "/home/jason/CNTK-Samples-2-0rc1/Tutorials/NumpyInterop_1/../../Examples/common/nn.py", line 30, in fully_connected_classifier_net
    r = fully_connected_layer(input, hidden_layer_dim, nonlinearity)
  File "/home/jason/CNTK-Samples-2-0rc1/Tutorials/NumpyInterop_1/../../Examples/common/nn.py", line 23, in fully_connected_layer
    p = linear_layer(input, output_dim)
  File "/home/jason/CNTK-Samples-2-0rc1/Tutorials/NumpyInterop_1/../../Examples/common/nn.py", line 15, in linear_layer
    times_param = parameter(shape=(list(input_var.shape)+[output_dim]), init=glorot_uniform())
  File "/home/jason/anaconda3/lib/python3.5/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/home/jason/anaconda3/lib/python3.5/site-packages/cntk/ops/__init__.py", line 2702, in parameter
    return Parameter(shape, init, dtype, device, name)
  File "/home/jason/anaconda3/lib/python3.5/site-packages/cntk/variables.py", line 296, in __init__
    device = use_default_device()
  File "/home/jason/anaconda3/lib/python3.5/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/home/jason/anaconda3/lib/python3.5/site-packages/cntk/device.py", line 119, in use_default_device
    return cntk_py.DeviceDescriptor.use_default_device()
RuntimeError: Acquire: Failed to open lock file /var/lock/CNTK_device_allocation_lock: Read-only file system.
```

I do not have the permission for "/var/lock/" since the code is ran on a cluster. Could someone help me with that?

Thank you.

Jason

**Comment by svml** [comment]
I have the same problem with CNTK-2.0.rc2

**Comment by hrasadi** [comment]
CNTK 2.0 is released and the issue persists. I had the same problem with older versions of CNTK and had to build everything from source (so to change the lock path to /tmp). Is there any technical considerations about this decision?

**Comment by wolfma61** [comment]
see also #62
