### ISSUE TITLE
zip library truncates names of files with '@'s in it

### ISSUE THREAD

**Issue by bebosudo** [Microsoft/CNTK#1831]
Playing around with Example/Image/TransferLearning/, I've encountered this issue:

```python
Traceback (most recent call last):
  File "/CNTK/Examples/Image/TransferLearning/TransferLearning_Extended.py", line 107, in <module>
    len(class_mapping), train_map_file, num_epochs=30, freeze=True)
  File "/CNTK/Examples/Image/TransferLearning/TransferLearning.py", line 100, in train_model
    minibatch_source = create_mb_source(train_map_file, image_width, image_height, num_channels, num_classes)
  File "/CNTK/Examples/Image/TransferLearning/TransferLearning.py", line 68, in create_mb_source
    randomize=randomize)
  File "/root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/io/__init__.py", line 255, in __init__
    source = cntk_py.create_composite_minibatch_source(config)
RuntimeError: Failed to open /images/category1/image_with_at_symbol_in, zip library error: No such file
```

If I have an image like: `/images/category1/image_with_at_symbol_in@the_middle.jpg`, the script truncates the file name at the 'at' symbol, therefore not finding it anymore and raising an exception.

A workaround I found is to rename the images with:
```bash
for im in /images/*/*@*; do mv $im $(echo $im |sed 's/@/_/g') ; done
```

**Comment by spandantiwari** [comment]
Renaming seems like a good idea here. If you have a fix could you please submit a PR for this?
