### ISSUE TITLE
No module named 'fastRCNN.utils.cython_bbox' Windows Anaconda Python 3.4.3

### ISSUE THREAD

**Issue by awscodu** [Microsoft/CNTK#1848]
I followed the instructions in the readme and set up a python 3.4 environment in anaconda. After installing all of the required packages, I have encountered this error trying to run A1_GenerateInputROIs.py. I understand people using Linux have had this problem but I'm running windows 10 so the '.pyd's should be working.

```
(cntk) C:\cntk\Examples\Image\Detection\FastRCNN\fastRCNN\utils>python  C:/cntk/Examples/Image/Detection/FastRCNN/A1_GenerateInputROIs.py
Traceback (most recent call last):
  File "C:/cntk/Examples/Image/Detection/FastRCNN/A1_GenerateInputROIs.py", line 5, in <module>
    import PARAMETERS
  File "C:\cntk\Examples\Image\Detection\FastRCNN\PARAMETERS.py", line 2, in <module>
    from cntk_helpers import *
  File "C:\cntk\Examples\Image\Detection\FastRCNN\cntk_helpers.py", line 7, in <module>
    from fastRCNN.nms import nms as nmsPython
  File "C:\cntk\Examples\Image\Detection\FastRCNN\fastRCNN\__init__.py", line 7, in <module>
    from .imdb import imdb
  File "C:\cntk\Examples\Image\Detection\FastRCNN\fastRCNN\imdb.py", line 16, in <module>
    from .utils.cython_bbox import bbox_overlaps
ImportError: No module named 'fastRCNN.utils.cython_bbox'
```

**Comment by awscodu** [comment]
The solution is to use Windows Powershell to run the python script and not the anaconda prompt itself.

**Comment by Imir** [comment]
It worked for me after renaming "Examples\Image\Detection\FastRCNN\fastRCNN\utils\**cython_bbox.cp34-win_amd64.pyd**" to "Examples\Image\Detection\FastRCNN\fastRCNN\utils\**cython_bbox.pyd**"
