### ISSUE TITLE
A3_ParseAndEvaluateOutput

### ISSUE THREAD

**Issue by UTTAM2311** [Microsoft/CNTK#1870]
PARAMETERS: datasetName = spam
PARAMETERS: cntk_nrRois = 100
Parsing CNTK output for image set: test
Parsing cntk output file, image 0 of 3
Traceback (most recent call last):
  File "A3_ParseAndEvaluateOutput.py", line 35, in <module>
    saveCompressed = True, skipCheck = True)
  File "/home/uttam/projects/CNTK/Examples/Image/Detection/FastRCNN/cntk_helpers.py", line 224, in parseCntkOutput
    assert len(values) == cntkNrRois * outputDim, "ERROR: expected dimension of {} but found {}".format(cntkNrRois * outputDim, len(values))
AssertionError: ERROR: expected dimension of 300 but found 1700

similar to the [issue](https://github.com/Microsoft/CNTK/issues/1732)   but isn't resolved

**Comment by UTTAM2311** [comment]
Using the predefined model initially build with grocery dataset .
at A2_RunCntk_py3.py 


    if os.path.exists(model_path):
        print("Loading existing model from %s" % model_path)
        trained_model = load_model(model_path)
    else:
        trained_model = train_fast_rcnn()
        trained_model.save(model_path)
        print("Stored trained model at %s" % model_path)

    # Evaluate the test set
    test_fast_rcnn(trained_model)
  
remove the model at /Output/frcn_py.model and run A2_RunCntk_py3.py again .
