### ISSUE TITLE
New Installation Cannot import CNTK

### ISSUE THREAD

**Issue by mohamedmansour** [Microsoft/CNTK#1896]
Hello, what could be wrong?

```
conda create --name cntk python=3.5.2 numpy scipy h5py jupyter
activate cntk
pip install https://cntk.ai/PythonWheel/GPU/cntk-2.0rc1-cp35-cp35m-win_amd64.whl
```

No failures:

```
(cntk) d:\Experiments>pip install https://cntk.ai/PythonWheel/GPU/cntk-2.0rc1-cp35-cp35m-win_amd64.whl
Requirement already satisfied: cntk==2.0rc1 from https://cntk.ai/PythonWheel/GPU/cntk-2.0rc1-cp35-cp35m-win_amd64.whl in c:\users\mmansour\appdata\local\conda\conda\envs\cntk\lib\site-packages
Requirement already satisfied: scipy>=0.17 in c:\users\mmansour\appdata\local\conda\conda\envs\cntk\lib\site-packages (from cntk==2.0rc1)
Requirement already satisfied: numpy>=1.11 in c:\users\mmansour\appdata\local\conda\conda\envs\cntk\lib\site-packages (from cntk==2.0rc1)
```

Then in python terminal:
```
(cntk) d:\Experiments>python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cntk
Traceback (most recent call last):
  File "C:\Users\mmansour\AppData\Local\conda\conda\envs\cntk\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mmansour\AppData\Local\conda\conda\envs\cntk\lib\site-packages\cntk\__init__.py", line 8, in <module>
    import numpy as np
  File "C:\Users\mmansour\AppData\Local\conda\conda\envs\cntk\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\mmansour\AppData\Local\conda\conda\envs\cntk\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\mmansour\AppData\Local\conda\conda\envs\cntk\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\mmansour\AppData\Local\conda\conda\envs\cntk\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\mmansour\AppData\Local\conda\conda\envs\cntk\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
```

Any help would be appreciated!

**Comment by mohamedmansour** [comment]
Now in the native python without conda, it seems scypy is the issue. Then I went to install tensorflow and it installed fine.:

```
C:\Users\mmansour>pip install https://cntk.ai/PythonWheel/GPU/cntk-2.0rc1-cp35-cp35m-win_amd64.whl
Collecting cntk==2.0rc1 from https://cntk.ai/PythonWheel/GPU/cntk-2.0rc1-cp35-cp35m-win_amd64.whl
  Using cached https://cntk.ai/PythonWheel/GPU/cntk-2.0rc1-cp35-cp35m-win_amd64.whl
Collecting scipy>=0.17 (from cntk==2.0rc1)
  Using cached scipy-0.19.0.zip
Collecting numpy>=1.11 (from cntk==2.0rc1)
  Using cached numpy-1.12.1-cp35-none-win_amd64.whl
Installing collected packages: numpy, scipy, cntk
  Running setup.py install for scipy ... error
    Complete output from command c:\users\mmansour\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mmansour\\AppData\\Local\\Temp\\pip-build-cb9w59bb\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\mmansour\AppData\Local\Temp\pip-_2hv2bwc-record\install-record.txt --single-version-externally-managed --compile:

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)


    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['c:\\users\\mmansour\\appdata\\local\\programs\\python\\python35\\lib', 'C:\\', 'c:\\users\\mmansour\\appdata\\local\\programs\\python\\python35\\libs']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['c:\\users\\mmansour\\appdata\\local\\programs\\python\\python35\\lib', 'C:\\', 'c:\\users\\mmansour\\appdata\\local\\programs\\python\\python35\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    c:\users\mmansour\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:1051: UserWarning: Specified path C:\projects\numpy-wheels\windows-wheel-builder\atlas-builds\atlas-3.11.38-sse2-64\lib is invalid.
      pre_dirs = system_info.get_paths(self, section, key)
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    c:\users\mmansour\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
      libraries lapack not found in ['c:\\users\\mmansour\\appdata\\local\\programs\\python\\python35\\lib', 'C:\\', 'c:\\users\\mmansour\\appdata\\local\\programs\\python\\python35\\libs']
      NOT AVAILABLE

    c:\users\mmansour\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE

    c:\users\mmansour\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE

    Running from scipy source directory.
    non-existing path in 'scipy\\integrate': 'quadpack.h'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mmansour\AppData\Local\Temp\pip-build-cb9w59bb\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\mmansour\AppData\Local\Temp\pip-build-cb9w59bb\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "c:\users\mmansour\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\mmansour\AppData\Local\Temp\pip-build-cb9w59bb\scipy\setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "c:\users\mmansour\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "c:\users\mmansour\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\mmansour\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "c:\users\mmansour\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "c:\users\mmansour\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\mmansour\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
Command "c:\users\mmansour\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mmansour\\AppData\\Local\\Temp\\pip-build-cb9w59bb\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\mmansour\AppData\Local\Temp\pip-_2hv2bwc-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\mmansour\AppData\Local\Temp\pip-build-cb9w59bb\scipy\

```

**Comment by bencherian** [comment]
After activating the CNTK Anaconda environment do you have a PYTHONPATH set? If so, try unsetting it and then importing numpy, cntk, etc. It seems rather odd that it fails on a numpy import...everything ran ok when you created the conda environment, right?

**Comment by wolfma61** [comment]
no follow-up , assuming closed

**Comment by Ark-kun** [comment]
I've just verified that this issue is still not fixed:
```
>conda create --name ML python=3.6
>activate ML
>pip install https://cntk.ai/PythonWheel/GPU/cntk-2.1-cp36-cp36m-win_amd64.whl
Collecting cntk==2.1 from https://cntk.ai/PythonWheel/GPU/cntk-2.1-cp36-cp36m-win_amd64.whl
  Downloading https://cntk.ai/PythonWheel/GPU/cntk-2.1-cp36-cp36m-win_amd64.whl (271.0MB)
    100% |████████████████████████████████| 271.0MB 2.4kB/s
Collecting numpy>=1.11 (from cntk==2.1)
  Downloading numpy-1.13.1-cp36-none-win_amd64.whl (7.8MB)
    100% |████████████████████████████████| 7.8MB 89kB/s
Collecting scipy>=0.17 (from cntk==2.1)
  Downloading scipy-0.19.1.tar.gz (14.1MB)
    100% |████████████████████████████████| 14.1MB 45kB/s
Building wheels for collected packages: scipy
  Running setup.py bdist_wheel for scipy ... error
  Complete output from command C:\Users\Ark\.conda\envs\ML\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ark\\AppData\\Local\\Temp\\pip-build-_lyq3uv_\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Ark\AppData\Local\Temp\tmpj00hcgacpip-wheel- --python-tag cp36:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Ark\AppData\Local\Temp\pip-build-_lyq3uv_\scipy\setup.py", line 416, in <module>
      setup_package()
    File "C:\Users\Ark\AppData\Local\Temp\pip-build-_lyq3uv_\scipy\setup.py", line 396, in setup_package
      from numpy.distutils.core import setup
  ModuleNotFoundError: No module named 'numpy'

  ----------------------------------------
  Failed building wheel for scipy
```

**Comment by wolfma61** [comment]
Not sure … your documentation recommends for creating the environment:
https://docs.microsoft.com/en-us/cognitive-toolkit/setup-windows-python


conda create --name cntk-py34 python=3.4 numpy scipy h5py jupyter

that should also work for python 3.6

**Comment by Ark-kun** [comment]
@wolfma61 

`conda install scipy` seems to be working too.

The documentation is a bit misleading here: https://docs.microsoft.com/en-us/cognitive-toolkit/setup-windows-python?tabs=cntkpy21#anaconda3

There is a little "pip install without an environment" small-heading section which seems to advice the global installation, but does not tell you that installing inside an environment would fail.

After that section there is the "First time CNTK installation" section with a similar heading style. That's what the first time users are reading regardless of their environment usage.

The fact that a binary wheel installs successfully in global conda env, but not in a virtual conda env is non-obvious.

The documentation lacks guidance for the scenario where user wants to insall CNTK in an existing environment. People will skip the `conda create` line in that case.

I propose adding warnings to the documentation that installing CNTK in a virtual environment **requires** installing certain packages from conda repo using the `conda install scipy` or `conda create ... scipy` command.
