### ISSUE TITLE
numpy errror running transfer learning example (python 3.5, ubuntu 16.04)

### ISSUE THREAD

**Issue by ckalas** [Microsoft/CNTK#1926]
Training transfer learning model for 30 epochs (epoch_size = 30).
Training 1026 parameters in 2 parameter tensors.
Finished Epoch[1 of 30]: [Training] loss = 1.539022 * 30, metric = 50.00% * 30 0.795s ( 37.7 samples/s);
Finished Epoch[2 of 30]: [Training] loss = 1.218500 * 30, metric = 46.67% * 30 0.423s ( 70.9 samples/s);
Finished Epoch[3 of 30]: [Training] loss = 0.424574 * 30, metric = 23.33% * 30 0.026s (1153.8 samples/s);
Finished Epoch[4 of 30]: [Training] loss = 0.060564 * 30, metric = 0.00% * 30 0.271s (110.7 samples/s);
Finished Epoch[5 of 30]: [Training] loss = 0.151549 * 30, metric = 10.00% * 30 0.237s (126.6 samples/s);
Finished Epoch[6 of 30]: [Training] loss = 0.069963 * 30, metric = 3.33% * 30 0.237s (126.6 samples/s);
Finished Epoch[7 of 30]: [Training] loss = 0.012647 * 30, metric = 0.00% * 30 0.228s (131.6 samples/s);
Finished Epoch[8 of 30]: [Training] loss = 0.002805 * 30, metric = 0.00% * 30 0.226s (132.7 samples/s);
Finished Epoch[9 of 30]: [Training] loss = 0.000908 * 30, metric = 0.00% * 30 0.227s (132.2 samples/s);
Finished Epoch[10 of 30]: [Training] loss = 0.000363 * 30, metric = 0.00% * 30 0.227s (132.2 samples/s);
Finished Epoch[11 of 30]: [Training] loss = 0.000165 * 30, metric = 0.00% * 30 0.227s (132.2 samples/s);
Finished Epoch[12 of 30]: [Training] loss = 0.000082 * 30, metric = 0.00% * 30 0.226s (132.7 samples/s);
Finished Epoch[13 of 30]: [Training] loss = 0.000044 * 30, metric = 0.00% * 30 0.227s (132.2 samples/s);
Finished Epoch[14 of 30]: [Training] loss = 0.000025 * 30, metric = 0.00% * 30 0.226s (132.7 samples/s);
Finished Epoch[15 of 30]: [Training] loss = 0.000015 * 30, metric = 0.00% * 30 0.227s (132.2 samples/s);
Finished Epoch[16 of 30]: [Training] loss = 0.000010 * 30, metric = 0.00% * 30 0.227s (132.2 samples/s);
Finished Epoch[17 of 30]: [Training] loss = 0.000007 * 30, metric = 0.00% * 30 0.227s (132.2 samples/s);
Finished Epoch[18 of 30]: [Training] loss = 0.000004 * 30, metric = 0.00% * 30 0.228s (131.6 samples/s);
Finished Epoch[19 of 30]: [Training] loss = 0.000003 * 30, metric = 0.00% * 30 0.228s (131.6 samples/s);
Finished Epoch[20 of 30]: [Training] loss = 0.000002 * 30, metric = 0.00% * 30 0.228s (131.6 samples/s);
Finished Epoch[21 of 30]: [Training] loss = 0.000002 * 30, metric = 0.00% * 30 0.227s (132.2 samples/s);
Finished Epoch[22 of 30]: [Training] loss = 0.000001 * 30, metric = 0.00% * 30 0.227s (132.2 samples/s);
Finished Epoch[23 of 30]: [Training] loss = 0.000001 * 30, metric = 0.00% * 30 0.227s (132.2 samples/s);
Finished Epoch[24 of 30]: [Training] loss = 0.000001 * 30, metric = 0.00% * 30 0.228s (131.6 samples/s);
Finished Epoch[25 of 30]: [Training] loss = 0.000001 * 30, metric = 0.00% * 30 0.228s (131.6 samples/s);
Finished Epoch[26 of 30]: [Training] loss = 0.000001 * 30, metric = 0.00% * 30 0.227s (132.2 samples/s);
Finished Epoch[27 of 30]: [Training] loss = 0.000001 * 30, metric = 0.00% * 30 0.228s (131.6 samples/s);
Finished Epoch[28 of 30]: [Training] loss = 0.000001 * 30, metric = 0.00% * 30 0.227s (132.2 samples/s);
Finished Epoch[29 of 30]: [Training] loss = 0.000000 * 30, metric = 0.00% * 30 0.227s (132.2 samples/s);
Finished Epoch[30 of 30]: [Training] loss = 0.000000 * 30, metric = 0.00% * 30 0.230s (130.4 samples/s);
Stored trained model at /home/chris/code/CNTK/Examples/Image/TransferLearning/Output/TransferLearning.model
Traceback (most recent call last):
  File "TransferLearning_Extended.py", line 110, in <module>
    train_and_eval(base_model_file, train_image_folder, test_image_folder, results_file, new_model_file)
  File "TransferLearning_Extended.py", line 100, in train_and_eval
    formatted_line = format_output_line(img_file, true_label, probs, class_mapping)
  File "TransferLearning_Extended.py", line 61, in format_output_line
    class_probs = np.column_stack((probs, class_mapping)).tolist()
  File "/home/chris/.local/lib/python3.5/site-packages/numpy/lib/shape_base.py", line 321, in column_stack
    return _nx.concatenate(arrays, 1)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by ckalas** [comment]
upon closer inspection i had to change 
class_probs = np.column_stack((probs[0], class_mapping)).tolist(), because probs.shape was (1,2) and class_mapping was just a python list of shape (2, )
