### ISSUE TITLE
invalid gpu device id with nvidia-381 ubuntu

### ISSUE THREAD

**Issue by ckalas** [Microsoft/CNTK#1984]
I upgraded my graphics drivers to v381 to resolve a display issue, but now cntk gives me an error. Obviously I will revert, but I'm wondering if this is known to you or not.

`python3 TransferLearning_Extended.py 
../models/ResNet_18.model
Traceback (most recent call last):
  File "TransferLearning_Extended.py", line 129, in <module>
    try_set_default_device(gpu(0))
  File "/usr/local/lib/python3.5/dist-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/cntk/device.py", line 94, in gpu
    return cntk_py.DeviceDescriptor.gpu_device(device_id)
ValueError: Specified GPU device id (0) is invalid.

[CALL STACK]
[0x7f58954e541c]                                                       + 0x64c41c
[0x7f58954e1bac]    CNTK::DeviceDescriptor::  GPUDevice  (unsigned int) + 0xcc
[0x7f5895dbbd89]                                                       + 0x9ad89
[0x4e9b9f]          PyCFunction_Call                                   + 0x4f
[0x524414]          PyEval_EvalFrameEx                                 + 0x614
[0x52e12b]          PyEval_EvalCodeEx                                  + 0x13b
[0x4ebdd7]                                                            
[0x5b7167]          PyObject_Call                                      + 0x47
[0x5262af]          PyEval_EvalFrameEx                                 + 0x24af
[0x52d82f]                                                            
[0x529332]          PyEval_EvalFrameEx                                 + 0x5532
[0x52d2e3]                                                            
[0x52dfdf]          PyEval_EvalCode                                    + 0x1f
[0x5fd2c2]                                                            
[0x5ff76a]          PyRun_FileExFlags                                  + 0x9a
[0x5ff95c]          PyRun_SimpleFileExFlags                            + 0x1bc
[0x63e7d6]          Py_Main                                            + 0x456
[0x4cfe41]          main                                               + 0xe1
[0x7f58adb58830]    __libc_start_main                                  + 0xf0
[0x5d5f29]          _start                                             + 0x29
`

**Comment by n17s** [comment]
I've had a similar issue and the solution was
```
sudo apt install libcuda1-381
```
