### ISSUE TITLE
ImportError with shared object libpython3.6m.so.1.0

### ISSUE THREAD

**Issue by EgorZay** [Microsoft/CNTK#2015]
Hi. It's your boy here with Kubuntu 16.04

I'm using Python 3.6.1 and I have installed CNTK via `python3.6 -m pip install cntk`. 
Before I had installed the necessary **openmbi-bin** library via apt-get.
Below is what I receive trying to import **cntk** in my PyCharm:

> Traceback (most recent call last):
  File "/home/komplett/.local/lib/python3.6/site-packages/cntk/cntk_py.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
**ModuleNotFoundError: No module named 'cntk._cntk_py'**

> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/komplett/pycharm-community-2017.1.3/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/komplett/.local/lib/python3.6/site-packages/cntk/__init__.py", line 10, in <module>
    from . import cntk_py
  File "/home/komplett/pycharm-community-2017.1.3/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/komplett/.local/lib/python3.6/site-packages/cntk/cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "/home/komplett/.local/lib/python3.6/site-packages/cntk/cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
**ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory**

Here is the list of `sys.path`:
> /home/komplett/pycharm-community-2017.1.3/helpers/pydev
/usr/local/lib/python3.6/dist-packages/xgboost-0.6-py3.6.egg
/home/komplett/pycharm-community-2017.1.3/helpers/pydev
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/komplett/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/komplett/PycharmProjects

*/home/komplett/.local/lib/python3.6/site-packages*  contains every library connected to Python 3.6.1 interpreter in PyCharm. Each library goes there when I provoke `python3.6 -m pip install <lib>`

*I do not have Anaconda3 installed*

Thanks in advance.
E.

**Comment by mahilleb-msft** [comment]
Hi @egorzay,
  I wasn't able to reproduce this, under a Ubuntu 16.04 docker with Python 3.6 (as you know it's not available by default under Ubuntu 16.04). So, with this:

```
# On Ubuntu 16.04
apt-get update
apt-get install software-properties-common wget openmpi-bin
add-apt-repository ppa:jonathonf/python-3.6
apt-get update
apt-get install python3.6
wget https://bootstrap.pypa.io/get-pip.py
python3.6 get-pip.py
python3.6 -m pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.1-cp36-cp36m-linux_x86_64.whl
```

CNTK import just works:
```
root@0fabdb625fb4:/# python3.6
Python 3.6.2 (default, Jul 20 2017, 08:43:29)
[GCC 5.4.1 20170519] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']
>>> import cntk
>>>
```
I can't help with any PyCharm-specific setup. Potentially, you'll need some configuration there, to make it available of your Python 3.6 distribution and library path and such. That it complains about not finding 
`libpython3.6m.so.1.0` definitely looks fishy. You may be able to get things working, checking for the location of libpython on your system, and, if it's not in a standard library path, adding it to `$LD_LIBRARY_PATH`.

Hope that helps,

Mark

**Comment by mahilleb-msft** [comment]
I'm closing this. Please re-open this issue if there's more info to share.

**Comment by pegulhane** [comment]
I am also seeing the same error for cntk 2.5
```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cntk
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/cntk/cntk_py.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/opt/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cntk._cntk_py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.6/site-packages/cntk/__init__.py", line 17, in <module>
    from . import cntk_py
  File "/opt/anaconda3/lib/python3.6/site-packages/cntk/cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "/opt/anaconda3/lib/python3.6/site-packages/cntk/cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "/opt/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

```

Would appreciate help on the same

**Comment by kodonnell** [comment]
I'm seeing the same as @pegulhane - Ubuntu 16.04 in WSL, with conda environment.

**Comment by kodonnell** [comment]
@thiagocrepaldi I'm not sure that'll help:

![image](https://user-images.githubusercontent.com/8204904/41004093-ce5ec7e6-696c-11e8-9b09-74a9795ca876.png)

**Comment by abaheti95** [comment]
I facing the same problem as @pegulhane . I am trying to install CNTK 2.5 on anaconda 3.5 on python 3.6.

Also, I am doing this on a academic server and thus I don't have the sudo access. Can you help me with this? Also, is there any easy way to install CNTK gpu with anaconda and python. I couldn't find a single straightforward command to do this in any of the installation tutorials.
