### ISSUE TITLE
Keras with CNTK backend

### ISSUE THREAD

**Issue by fcivardi** [Microsoft/CNTK#2061]
By setting the keras backend to cntk, after "import keras" I got the following error:
AttributeError: module 'cntk' has no attribute 'set_global_option'

in cntk_backend.py , C.set_global_option('align_axis, 1)

**Comment by souptc** [comment]
@fcivardi , did you install CNTK v2 correctly? current cntk keras backend is suppose to work with CNTK v2 GA version:
https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-your-machine

**Comment by fcivardi** [comment]
I did not install CNTK v2, because I'm using the last Windows DSVM (just created), where everything is preinstalled..
I simply did:
conda create --name keras --clone py35   (avoiding possibly corrupting the original p35 env of the DSVM)
pip install keras
activate keras
Then I changed the default backend and tried importing keras

**Comment by fcivardi** [comment]
I built a new environment with the latest version of Keras and CNTK as explained here
https://docs.microsoft.com/en-us/cognitive-toolkit/using-cntk-with-keras
 and it works.
I close the issue

**Comment by guillaume-chevalier** [comment]
I get this error too (on a GPU environment) that should work fine. It would be interesting to know the exact reason for this error.

```
>>> import keras
Using CNTK backend
Traceback (most recent call last):
  File "optimize.py", line 9, in <module>
    from model_architecture import *
  File "/home/ec2-user/pynbs/geoanalysis/model_architecture.py", line 18, in <module>
    from lsuv_init import LSUVinit
  File "/home/ec2-user/pynbs/geoanalysis/lsuv_init.py", line 6, in <module>
    from keras.models import Model
  File "/usr/local/lib64/python3.4/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/lib64/python3.4/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/usr/local/lib64/python3.4/site-packages/keras/utils/conv_utils.py", line 3, in <module>
    from .. import backend as K
  File "/usr/local/lib64/python3.4/site-packages/keras/backend/__init__.py", line 77, in <module>
    from .cntk_backend import *
  File "/usr/local/lib64/python3.4/site-packages/keras/backend/cntk_backend.py", line 10, in <module>
    C.set_global_option('align_axis', 1)
AttributeError: 'module' object has no attribute 'set_global_option'
```

Commenting out the line "C.set_global_option('align_axis', 1)" makes the import work, but the code would still bug later on when using Keras, for example, I get this error later on, here is a part of the stack:

```
  File "/usr/local/lib64/python3.4/site-packages/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib64/python3.4/site-packages/keras/layers/convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "/usr/local/lib64/python3.4/site-packages/keras/backend/cntk_backend.py", line 1331, in conv2d
    x = _preprocess_conv2d_input(x, data_format)
  File "/usr/local/lib64/python3.4/site-packages/keras/backend/cntk_backend.py", line 1947, in _preprocess_conv2d_input
    x = C.transpose(x, (2, 0, 1))
  File "/home/ec2-user/src/cntk/bindings/python/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/home/ec2-user/src/cntk/bindings/python/cntk/ops/__init__.py", line 1920, in transpose
    axis1 = sanitize_axis(axis1)
  File "/home/ec2-user/src/cntk/bindings/python/cntk/internal/sanitize.py", line 422, in sanitize_axis
    elif axis.is_static_axis and (axis.static_axis_index() != Axis.new_leading_axis().static_axis_index()):
AttributeError: 'tuple' object has no attribute 'is_static_axis'
```

**Comment by guillaume-chevalier** [comment]
Got it working. I had a previous installation of `cntk==2.0rc1` overriding my newer `cntk==2.1` installation. Some path issues.

**Comment by csbrown** [comment]
@guillaume-chevalier how did you fix this thing?  I am also having troubles with past and present versions of cntk fighting, and am getting this identical error.
