### ISSUE TITLE
ImageDeserializer: Unable to get labels from MinibatchSource

### ISSUE THREAD

**Issue by tomekjaworski** [Microsoft/CNTK#2151]
Hi,
I'm unable to get labels from data read from MinibatchSource, it its based on ImageDeserializer. Getting the following error. Same code with CTFDeserializer works fine.
Stack trace:
```
C:\Program Files\Python36\lib\site-packages\cntk\tensor.py:227: UserWarning: converting Value object to CSR format might be slow
  warnings.warn('converting Value object to CSR format might be slow')
Traceback (most recent call last):
  File "C:\Program Files\Python36\PyCharm Community Edition 2017.1.4\helpers\pydev\pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\Python36\PyCharm Community Edition 2017.1.4\helpers\pydev\pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\Python36\PyCharm Community Edition 2017.1.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "M:/!!BADANIA/deep/MNIST_ConvNet_Python/blad_czytnika.py", line 52, in <module>
    print(data[label_var].asarray())
  File "C:\Program Files\Python36\lib\site-packages\cntk\tensor.py", line 240, in asarray
    result = to_csr(dense_data)
  File "C:\Program Files\Python36\lib\site-packages\cntk\tensor.py", line 234, in to_csr
    'with shape %s of rank > 2 to a scipy.csr matrix.' % str(dense_data.shape))
ValueError: Cannot convert a sparse NDArrayView or Value object with shape (16, 1, 102) of rank > 2 to a scipy.csr matrix.
```
Using CNTK 2.0 GPU and Python 3.6.1 x64.

**Comment by tomekjaworski** [comment]
Sorry, forgot about the test code:

```
from __future__ import print_function
import numpy as np
import os
import cntk as C

def create_image_mb_source(train_file, is_training):
    # transformation pipeline for the features has jitter/crop only when training
    import cntk.io.transforms as T

    transforms = []
    transforms = [T.scale(width=image_width, height=image_height, channels=num_channels, interpolations='linear')]

    # deserializer
    stream_defs = C.io.StreamDefs(features=C.io.StreamDef(field='image', transforms=transforms),
                                  # 1st col in mapfile referred to as 'image'
                                  labels=C.io.StreamDef(field='label', shape=num_classes))

    image_deserializer = C.io.ImageDeserializer(train_file, stream_defs)

    return C.io.MinibatchSource(
        image_deserializer,
        multithreaded_deserializer=True,
        randomize=is_training,
        max_sweeps=C.io.INFINITELY_REPEAT if is_training else 1)

image_height = 64
image_width = 64
num_channels = 1
num_classes = 102
num_channels = 3

train_file = "c:\\flowers102\\train_files.txt"

# Input variables denoting the features and label data
input_var = C.ops.input_variable((num_channels, image_height, image_width), np.float32, name="Input image")
label_var = C.ops.input_variable(num_classes, np.float32, name="Labels")

##################################################
reader_train = create_image_mb_source(train_file, True)
input_map = {
    input_var: reader_train.streams.features,
    label_var: reader_train.streams.labels
}

batch_size = 16
data = reader_train.next_minibatch(batch_size, input_map=input_map)  # fetch minibatch.

# This work:
print(data[input_var].asarray())
# This doest not wotk:
print(data[label_var].asarray())

```

**Comment by marcinmachura** [comment]
Try this: data[label_var].as_sequences(label_var)[0]

**Comment by tomekjaworski** [comment]
Thanks! Works like a charm.

**Comment by ujjwal-researcher** [comment]
Once your issue gets resolved, please consider closing it. A resolved but open issue is confusing and it also masks the efforts of the contributors and developers who take their time and energy to solve others' queries.
