### ISSUE TITLE
GraphViz's executables not found

### ISSUE THREAD

**Issue by kyoro1** [Microsoft/CNTK#2197]
In executing Faster R-CNN with the following path:
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FasterRCNN/FasterRCNN.py

The following error has generated:

```sh
C:\Users\kyiwasak\git\CNTK\Examples\Image\Detection\FasterRCNN (master)
(py35) λ piython FasterRCNN.py
Selected CPU as the process wide default device.
Using the following parameters:
Flip image       : True
Train conv layers: True
Random seed      : 3
Momentum per MB  : 0.9
E2E epochs       : 20
Storing graphs and models to C:\Users\kyiwasak\git\CNTK\Examples\Image\Detection\FasterRCNN\Output.
Traceback (most recent call last):
  File "FasterRCNN.py", line 723, in <module>
    eval_model = train_faster_rcnn_e2e(base_model_file, debug_output=cfg["CNTK"].DEBUG_OUTPUT)
  File "FasterRCNN.py", line 446, in train_faster_rcnn_e2e
    plot(loss, os.path.join(globalvars['output_path'], "graph_frcn_train_e2e." + cfg["CNTK"].GRAPH_TYPE))
  File "C:\Users\kyiwasak\AppData\Local\Continuum\Anaconda2\envs\py35\lib\site-packages\cntk\logging\graph.py", line 338, in plot
    dot_object.write_png(filename, prog='dot')
  File "C:\Users\kyiwasak\AppData\Local\Continuum\Anaconda2\envs\py35\lib\site-packages\pydot_ng\__init__.py", line 1743, in <lambda>
    lambda path, f=frmt, prog=self.prog: self.write(path, format=f, prog=prog)
  File "C:\Users\kyiwasak\AppData\Local\Continuum\Anaconda2\envs\py35\lib\site-packages\pydot_ng\__init__.py", line 1848, in write
    fobj.write(self.create(prog, format))
  File "C:\Users\kyiwasak\AppData\Local\Continuum\Anaconda2\envs\py35\lib\site-packages\pydot_ng\__init__.py", line 1890, in create
    'GraphViz\'s executables not found')
pydot_ng.InvocationException: GraphViz's executables not found
```

Do we need `graphviz` in executing Faster r-cnn?

**Comment by mortengryning** [comment]
I just installed it and the error went away :-)

**Comment by kyoro1** [comment]
OK, thanks:) I did it!

Indeed, I installed `Graphviz` and set `PATH` in my PC. Then, succeeded!
Also found a comment in CNTK:
https://github.com/Microsoft/CNTK/blob/909e5235be893f1af55105c74dc1e2fe798645e4/bindings/python/cntk/logging/graph.py

```py
def plot(root, filename=None):
    '''
    Walks through every node of the graph starting at ``root``,
    creates a network graph, and returns a network description. If ``filename`` is
    specified, it outputs a DOT, PNG, PDF, or SVG file depending on the file name's suffix.
    Requirements:
     * for DOT output: `pydot_ng <https://pypi.python.org/pypi/pydot-ng>`__
     * for PNG, PDF, and SVG output: `pydot_ng <https://pypi.python.org/pypi/pydot-ng>`__
       and `graphviz <http://graphviz.org>`__ (GraphViz executable has to be in the system's PATH).
```

So, issue was closed.
