### ISSUE TITLE
FasterRCNN anchor_target_layer issue with image dimension

### ISSUE THREAD

**Issue by dashesy** [Microsoft/CNTK#2224]
With training set of images all 3648x2736, when I set `ImageHeight` equal to `ImageWidth` equal to 1000 `overlaps` could be empty, resulting in this error:

```
$ python -u FasterRCNN.py
Selected GPU[0] GeForce GTX 1070 as the process wide default device.
Using the following parameters:
Flip image       : True
Train conv layers: True
Random seed      : 3
Momentum per MB  : 0.9
E2E epochs       : 20
Storing graphs and models to D:\development\CNTK\Examples\Image\Detection\FasterRCNN\Output.
Warning: node 'Block749', graph 'network_graph' size too small for label
Warning: node 'UserDefinedFunction609', graph 'network_graph' size too small for label
Warning: node 'NoOp7', graph 'network_graph' size too small for label
Warning: node 'Block924', graph 'network_graph' size too small for label
Warning: node 'NoOp778', graph 'network_graph' size too small for label
Warning: node 'UserDefinedFunction772', graph 'network_graph' size too small for label
Warning: node 'NoOp606', graph 'network_graph' size too small for label

Using base model:   AlexNet
lr_per_sample:      [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 1e-05]
biases
Parameter('b', [], [18 x 1 x 1])
Parameter('b', [], [256 x 1 x 1])
Parameter('conv1.b', [], [64 x 1 x 1])
Parameter('conv2.b', [], [192 x 1 x 1])
Parameter('conv3.b', [], [384 x 1 x 1])
Parameter('conv4.b', [], [256 x 1 x 1])
Parameter('conv5.b', [], [256 x 1 x 1])
Parameter('b', [], [36 x 1 x 1])
Parameter('h1.b', [], [4096])
Parameter('h2.b', [], [4096])
Parameter('cls_score.b', [], [50])
Parameter('bbox_regr.b', [], [200])
others
Parameter('W', [], [18 x 256 x 1 x 1])
Parameter('W', [], [256 x 256 x 3 x 3])
Parameter('conv5.W', [], [256 x 256 x 3 x 3])
Parameter('conv4.W', [], [256 x 384 x 3 x 3])
Parameter('conv3.W', [], [384 x 192 x 3 x 3])
Parameter('conv2.W', [], [192 x 64 x 5 x 5])
Parameter('conv1.W', [], [64 x 3 x 11 x 11])
Parameter('W', [], [36 x 256 x 1 x 1])
Parameter('cls_score.W', [], [4096 x 50])
Parameter('h2.W', [], [4096 x 4096])
Parameter('h1.W', [], [256 x 6 x 6 x 4096])
Parameter('bbox_regr.W', [], [4096 x 200])
bias_lr_mult: 2.0
Training model for 20 epochs.
Training 58632048 parameters in 24 parameter tensors.
-------------------------------------------------------------------
Build info:

                Built time: Jul 31 2017 03:32:30
                Last modified date: Wed Jul 26 04:13:05 2017
                Build type: Release
                Build target: GPU
                With 1bit-SGD: yes
                With ASGD: yes
                Math lib: mkl
                CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
                CUB_PATH: c:\local\cub-1.4.1
                CUDNN_PATH: C:\local\cudnn-8.0-windows10-x64-v6.0.21\cuda
                Build Branch: HEAD
                Build SHA1: 5643a5619097b125f49e629f5bdbbc5a6ceedcf0
                Built by svcphil on DPHAIM-22
                Build Path: C:\jenkins\workspace\CNTK-Build-Windows\Source\CNTKv2LibraryDll\
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda3\envs\py35_cntk2.0\lib\site-packages\cntk\ops\functions.py", line 1674, in _forward
    state = self.forward(args, outputs, device, outputs_to_retain)
  File "D:\development\CNTK\Examples\Image\Detection\FasterRCNN\..\utils\rpn\anchor_target_layer.py", line 172, in forward
    argmax_overlaps = overlaps.argmax(axis=1)

```

This issue is similar to [this](https://github.com/rbgirshick/py-faster-rcnn/issues/410), but changing `_allowed_border ` did not help. To get over this issue I have to set `ImageWidth` and `ImageHeight` to the fixed size (or larger than)  of the original images size of 3648x2736 (all images must be the same size too). Large image size makes training slower.

What is the core issue here and is there a suggested normalized size to use for the training set?

-------------
Edit: Even with fixed size images the error is reproduced (after more iterations, so less frequent)

```
Processed 700 samples
PROGRESS: 0.00%
PROGRESS: 0.00%
PROGRESS: 0.00%
Traceback (most recent call last):
  File "C:\Anaconda3\envs\py35_cntk2.0\lib\site-packages\cntk\ops\functions.py", line 1674, in _forward
    state = self.forward(args, outputs, device, outputs_to_retain)
  File "D:\development\CNTK\Examples\Image\Detection\FasterRCNN\..\utils\rpn\anchor_target_layer.py", line 172, in forward
    argmax_overlaps = overlaps.argmax(axis=1)
ValueError: attempt to get argmax of an empty sequence
```

I will try to create a small test to reproduce this.

**Comment by dashesy** [comment]
Ok, at least one case that this error happens is when there is an image with no ground truth data during training. The fix to that is to just delete the image and update the lines accordingly.

An empty line in the `train_roi_file.txt` e.g.

    458 |roiAndLabel 

Will result in this error, because `gt_boxes` would be zero for that image.
I will try to reproduce other corner cases (if any)

**Comment by cha-zhang** [comment]
Thanks! Seems this is resolved. Closing it now.
