### ISSUE TITLE
debug_model does not work with LSTM

### ISSUE THREAD

**Issue by n17s** [Microsoft/CNTK#2231]
It seems debug_model assumes that every node has one output, which is not true for LSTMs (which output a hidden state and a cell state). The following code does not given an exception when I use a `C.layers.GRU` instead of `C.layers.LSTM`.

```python
>>> x = C.sequence.input_variable(5)
>>> y = C.layers.Sequential([C.layers.Embedding(100), C.layers.Recurrence(C.layers.LSTM(200)), C.layers.Dense(10)])
>>> z = y(x)
>>> z.eval({x:x0})
[array([[-0.19680208, -0.04795102,  0.04390366,  0.10843965,  0.04639784,
        -0.01087247,  0.05240977,  0.20029213,  0.11081621,  0.02255788],
       [-0.18312994, -0.14049117, -0.03551376,  0.19424647,  0.0590032 ,
         0.23556565, -0.02098456,  0.30189207,  0.11128835, -0.00979212],
       [-0.10086668, -0.09921069, -0.18231876,  0.22916119, -0.04540209,
         0.57299697, -0.14773467,  0.26541185,  0.07272118, -0.06762365],
       [-0.0657562 , -0.02663144, -0.29578406,  0.26820424, -0.14508072,
         0.82975447, -0.17949513,  0.24425402,  0.0214614 , -0.05334111],
       [-0.05673546,  0.00458169, -0.34949103,  0.30596924, -0.20245627,
         0.97540689, -0.13516515,  0.24724582, -0.01221067, -0.01629719],
       [-0.05261448,  0.0079973 , -0.36138129,  0.33714998, -0.22992295,
         1.05347419, -0.08094192,  0.26667568, -0.03439096,  0.00795412]], dtype=float32)]
>>> w = C.debugging.debug_model(z)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\nikosk\Documents\mastercntk\CNTK\bindings\python\cntk\debugging\debug.py", line 434, in debug_model
    for n in nodes}
  File "C:\Users\nikosk\Documents\mastercntk\CNTK\bindings\python\cntk\debugging\debug.py", line 434, in <dictcomp>
    for n in nodes}
  File "C:\Users\nikosk\Documents\mastercntk\CNTK\bindings\python\cntk\debugging\debug.py", line 178, in __init__
    super(_DebugNode, self).__init__([arg], as_numpy=True, name=name)
  File "C:\Users\nikosk\Documents\mastercntk\CNTK\bindings\python\cntk\ops\functions.py", line 1625, in __init__
    super(UserFunction, self).__init__(inputs, name)
  File "C:\Users\nikosk\Documents\mastercntk\CNTK\bindings\python\cntk\ops\functions.py", line 115, in __init__
    super(Function, self).__init__(*args, **kwargs)
  File "C:\Users\nikosk\Documents\mastercntk\CNTK\bindings\python\cntk\cntk_py.py", line 1992, in __init__
    this = _cntk_py.new_Function(_self, *args)
TypeError: cannot convert list element to CNTK::Variable
```

**Comment by abhimohta** [comment]
Facing the same issue. Is there any work around to make it work with LSTMs?
