### ISSUE TITLE
DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by baozi-lala** [Microsoft/CNTK#2246]
before,I could use cntk normally,but after I modified the environment variable and install the tensorflow in another anaconda environment ,this error occurs.I tried to change the environment back,but it was useless.how can i do to solve this problem.

C:\local\Anaconda2\python.exe "D:/Machine Learning/projects/CNTK/ConvNet_MNIST.py"
Traceback (most recent call last):
  File "D:/Machine Learning/projects/CNTK/ConvNet_MNIST.py", line 11, in <module>
    import cntk as C
  File "C:\local\Anaconda2\lib\site-packages\cntk\__init__.py", line 10, in <module>
    from . import cntk_py
  File "C:\local\Anaconda2\lib\site-packages\cntk\cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "C:\local\Anaconda2\lib\site-packages\cntk\cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "C:\local\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: DLL load failed: The specified module could not be found

**Comment by tangyuq** [comment]
To separate different environments, you might want to create virtual environments for each of them, for example,
 conda create --name cntk-py34 python=3.4 numpy scipy h5py jupyter
 activate cntk-py34
 pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.1-cp34-cp34m-win_amd64.whl

You can replace the Python version, the CPU or GPU wheel files above with the one fit your need. A list of release CNTK packages is at:
https://docs.microsoft.com/en-us/cognitive-toolkit/setup-windows-python?tabs=cntkpy21#quick-installation-test

**Comment by baozi-lala** [comment]
thank you very much
