### ISSUE TITLE
RuntimeError: Failed to parse Dictionary from the input stream.

### ISSUE THREAD

**Issue by cxfire16** [Microsoft/CNTK#2312]
Greetings! I'm very new to CNTK, I installed the version 2.1 and encountered the error described below. I already scoured the net for answers, it seems to be the only occurrence in context of CNTK. The code is from the image detection example. Installed in a conda env with all instructions followed until
Executing "python DetectionDemo.py", it returns

(cntkObjectDetection) F:\Files\Work\4\AI\segmentation\CNTK-master\Examples\Image\Detection>python DetectionDemo.py FastRCNN
training FastRCNN
Selected CPU as the process wide default device.
Traceback (most recent call last):
  File "DetectionDemo.py", line 59, in <module>
    eval_model = od.train_object_detector(cfg)
  File "F:\Files\Work\4\AI\segmentation\CNTK-master\Examples\Image\Detection\utils\od_utils.py", line 17, in train_object_detector
    eval_model = train_fast_rcnn(cfg)
  File "F:\Files\Work\4\AI\segmentation\CNTK-master\Examples\Image\Detection\FastRCNN\FastRCNN_train.py", line 274, in train_fast_rcnn
    loss, pred_error = create_fast_rcnn_model(image_input, roi_proposals, label_targets, bbox_targets, bbox_inside_weights, cfg)
  File "F:\Files\Work\4\AI\segmentation\CNTK-master\Examples\Image\Detection\FastRCNN\FastRCNN_train.py", line 191, in create_fast_rcnn_model
    base_model = load_model(cfg['BASE_MODEL_PATH'])
  File "C:\Users\rox\Anaconda3\envs\cntkObjectDetection\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\rox\Anaconda3\envs\cntkObjectDetection\lib\site-packages\cntk\ops\functions.py", line 1604, in load_model
    return Function.load(model, device)
  File "C:\Users\rox\Anaconda3\envs\cntkObjectDetection\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\rox\Anaconda3\envs\cntkObjectDetection\lib\site-packages\cntk\ops\functions.py", line 1518, in load
    return cntk_py.Function.load(str(model), device)
RuntimeError: Failed to parse Dictionary from the input stream.

[CALL STACK]
    > CNTK::operator>>
    - CNTK::Function::  Load
    - PyInit__cntk_py (x2)
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)
    - PyFunction_SetAnnotations
    - PyObject_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)
    - PyEval_GetFuncDesc (x2)
    - PyEval_EvalFrameEx

I'm open to any comments. I may have missed something? 
Thanks!

**Comment by spandantiwari** [comment]
Can you confirm that you have the model (and also data) downloaded at the right place? You will need to run install_data_and_model.py script for that from the Examples/Images/Detection/FastRCNN folder.

**Comment by cha-zhang** [comment]
Closing this due to lack of response. Please reopen if needed.

**Comment by NickDarvey** [comment]
I had this, my issue was that the model download was... fucked.
I had to redownload it from https://github.com/Microsoft/CNTK/blob/master/PretrainedModels/Image.md#alexnet-for-imagenet-1k-1
