### ISSUE TITLE
”CUDA failure 77: an illegal memory access was encountered" in Executing Faster R-CNN

### ISSUE THREAD

**Issue by kyoro1** [Microsoft/CNTK#2388]
In executing `run_faster_rcnn.py` of CNTK2.2, I encountered error message as follows. With version=2.1, I've never met this kind of error.

- Environment:
  - NC24 in Azure(4-GPU)
  - CNTK: 2.2
  - python 3.5

What kind of activities can we do in this situation? (As far as I tried, Fast R-CNN scripts was fine in the same environment.)

```sh
C:\git\CNTK\Examples\Image\Detection\FasterRCNN (master)
(cntk2.2) λ python run_faster_rcnn.py
Selected GPU[1] Tesla K80 as the process wide default device.
Using base model:   AlexNet
lr_per_sample:      [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 1e-05]
Training model for 20 epochs.
Training 57554122 parameters in 27 parameter tensors.
-------------------------------------------------------------------
Build info:

                Built time: Sep 15 2017 07:42:54
                Last modified date: Thu Sep 14 22:33:54 2017
                Build type: Release
                Build target: GPU
                With 1bit-SGD: no
                With ASGD: yes
                Math lib: mkl
                CUDA version: 8.0.0
                CUDNN version: 6.0.21
                Build Branch: HEAD
                Build SHA1: 23878e5d1f73180d6564b6f907b14fe5f53513bb
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
CUDA failure 77: an illegal memory access was encountered ; GPU=0 ; hostname=ABC-XYZ ; expr=cudaMemcpy(Data(), pArray, sizeof(ElemType) * GetNumElements(), (matrixFlags & matrixFlagSetValueOnDevice) ? cudaMemcpyDeviceToDevice : cudaMemcpyHostToDevice)
Traceback (most recent call last):
  File "run_faster_rcnn.py", line 35, in <module>
    trained_model = train_faster_rcnn(cfg)
  File "C:\git\CNTK\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 291, in train_faster_rcnn
    eval_model = train_faster_rcnn_e2e(cfg)
  File "C:\git\CNTK\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 329, in train_faster_rcnn_e2e
    e2e_lr_per_sample_scaled, mm_schedule, cfg["CNTK"].L2_REG_WEIGHT, cfg["CNTK"].E2E_MAX_EPOCHS, cfg)
  File "C:\git\CNTK\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 571, in train_model
    trainer.train_minibatch(data)                                    # update model with it
  File "C:\Anaconda\envs\cntk2.2\lib\site-packages\cntk\train\trainer.py", line 170, in train_minibatch
    arguments, device)
  File "C:\Anaconda\envs\cntk2.2\lib\site-packages\cntk\cntk_py.py", line 2804, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
RuntimeError: CUDA failure 77: an illegal memory access was encountered ; GPU=0 ; hostname=ABC-XYZ ; expr=cudaMemcpy(Data(), pArray, sizeof(ElemType) * GetNumElements(), (matrixFlags & matrixFlagSetValueOnDevice) ? cudaMemcpyDeviceToDevice : cudaMemcpyHostToDevice)

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::GPUMatrix<float>::  SetValue (x2)
    - Microsoft::MSR::CNTK::Matrix<float>::  SetValue
    - Microsoft::MSR::CNTK::DataTransferer::  operator= (x2)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - Microsoft::MSR::CNTK::DataTransferer::  operator=
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfSamplesSeen
    - CNTK::Trainer::  TrainMinibatch (x2)
    - PyInit__cntk_py (x2)
```

**Comment by KeDengMS** [comment]
Are you running distributed training? Please try using CUDA_VISIBLE_DEVICES to limit to 1 GPU and see if the bug still occurs. We will try get a local repro.

**Comment by kyoro1** [comment]
@KeDengMS Thanks for your information. I've succeeded in starting the process.

```sh
C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN (master)
(cntk2.2) λ set CUDA_VISIBLE_DEVICES=1

C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN (master)
(cntk2.2) λ python run_faster_rcnn.py
Selected GPU[0] Tesla K80 as the process wide default device.
Using base model:   AlexNet
lr_per_sample:      [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 1e-05]
Training model for 20 epochs.
Training 57820427 parameters in 27 parameter tensors.
-------------------------------------------------------------------
Build info:

                Built time: Sep 15 2017 07:42:54
                Last modified date: Thu Sep 14 22:33:54 2017
                Build type: Release
                Build target: GPU
                With 1bit-SGD: no
                With ASGD: yes
                Math lib: mkl
                CUDA version: 8.0.0
                CUDNN version: 6.0.21
                Build Branch: HEAD
                Build SHA1: 23878e5d1f73180d6564b6f907b14fe5f53513bb
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
PROGRESS: 0.00%
PROGRESS: 0.00%
Finished Epoch[1 of 20]: [Training] loss = 1.808086 * 20, metric = 22.27% * 20 16.443s (  1.2 samples/s);
Finished Epoch[2 of 20]: [Training] loss = 1.058197 * 20, metric = 13.16% * 20 6.250s (  3.2 samples/s);
PROGRESS: 0.00%
Finished Epoch[3 of 20]: [Training] loss = 0.816437 * 20, metric = 10.00% * 20 6.031s (  3.3 samples/s);
PROGRESS: 0.00%
Finished Epoch[4 of 20]: [Training] loss = 0.745689 * 20, metric = 8.55% * 20 6.063s (  3.3 samples/s);
  :
```

Then, if we'd like to use multiple GPU, what kind of setting is needed?
The `CUDA_VISIBLE_DEVICES=2` means that we use 2-GPU(, if the machine has 2 or over GPU), right?

**Comment by KeDengMS** [comment]
CUDA_VISIBLE_DEVICES is a string of comma separated device ids [explained here](http://acceleware.com/blog/cudavisibledevices-masking-gpus), so to use two GPU set it to "0,1". I think there's a bug in FasterRCNN or CNTK code when running the model with multiple devices, and we'll look into it.

**Comment by kyoro1** [comment]
@KeDengMS Thanks! But, as far as I tried following 2 cases, the processes were not successful...

- the 1st case:
```sh
C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN (master)
(cntk2.2) λ set CUDA_VISIBLE_DEVICES=0,1

C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN (master)
(cntk2.2) λ python run_faster_rcnn.py
Selected GPU[1] Tesla K80 as the process wide default device.
Using base model:   AlexNet
lr_per_sample:      [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 1e-05]
Training model for 20 epochs.
Training 57820427 parameters in 27 parameter tensors.
-------------------------------------------------------------------
Build info:

                Built time: Sep 15 2017 07:42:54
                Last modified date: Thu Sep 14 22:33:54 2017
                Build type: Release
                Build target: GPU
                With 1bit-SGD: no
                With ASGD: yes
                Math lib: mkl
                CUDA version: 8.0.0
                CUDNN version: 6.0.21
                Build Branch: HEAD
                Build SHA1: 23878e5d1f73180d6564b6f907b14fe5f53513bb
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
CUDA failure 77: an illegal memory access was encountered ; GPU=0 ; hostname=OLYMPUS-VERIF ; expr=cudaMemcpy(Data(), pArray, sizeof(ElemType) * GetNumElements(), (matrixFlags & matrixFlagSetValueOnDevice) ? cudaMemcpyDeviceToDevice : cudaMemcpyHostToDevice)
Traceback (most recent call last):
  File "run_faster_rcnn.py", line 33, in <module>
    trained_model = train_faster_rcnn(cfg)
  File "C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 291, in train_faster_rcnn
    eval_model = train_faster_rcnn_e2e(cfg)
  File "C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 329, in train_faster_rcnn_e2e
    e2e_lr_per_sample_scaled, mm_schedule, cfg["CNTK"].L2_REG_WEIGHT, cfg["CNTK"].E2E_MAX_EPOCHS, cfg)
  File "C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 571, in train_model
    trainer.train_minibatch(data)                                    # update model with it
  File "C:\Anaconda\envs\cntk2.2\lib\site-packages\cntk\train\trainer.py", line 170, in train_minibatch
    arguments, device)
  File "C:\Anaconda\envs\cntk2.2\lib\site-packages\cntk\cntk_py.py", line 2804, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
RuntimeError: CUDA failure 77: an illegal memory access was encountered ; GPU=0 ; hostname=OLYMPUS-VERIF ; expr=cudaMemcpy(Data(), pArray, sizeof(ElemType) * GetNumElements(), (matrixFlags & matrixFlagSetValueOnDevice) ? cudaMemcpyDeviceToDevice : cudaMemcpyHostToDevice)

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::GPUMatrix<float>::  SetValue (x2)
    - Microsoft::MSR::CNTK::Matrix<float>::  SetValue
    - Microsoft::MSR::CNTK::DataTransferer::  operator= (x2)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - Microsoft::MSR::CNTK::DataTransferer::  operator=
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfSamplesSeen
    - CNTK::Trainer::  TrainMinibatch (x2)
    - PyInit__cntk_py (x2)
```

- the 2nd case:

```sh
C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN (master)
(cntk2.2) λ set CUDA_VISIBLE_DEVICES=”0,1”
C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN (master)
(cntk2.2) λ python run_faster_rcnn.py
Selected CPU as the process wide default device.
Using base model:   AlexNet
lr_per_sample:      [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 1e-05]
Training model for 20 epochs.
Training 57820427 parameters in 27 parameter tensors.
-------------------------------------------------------------------
Build info:

                Built time: Sep 15 2017 07:42:54
                Last modified date: Thu Sep 14 22:33:54 2017
                Build type: Release
                Build target: GPU
                With 1bit-SGD: no
                With ASGD: yes
                Math lib: mkl
                CUDA version: 8.0.0
                CUDNN version: 6.0.21
                Build Branch: HEAD
                Build SHA1: 23878e5d1f73180d6564b6f907b14fe5f53513bb
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
no CUDA-capable device is detected
no CUDA-capable device is detected
no CUDA-capable device is detected
no CUDA-capable device is detected
no CUDA-capable device is detected
no CUDA-capable device is detected
no CUDA-capable device is detected
no CUDA-capable device is detected
PROGRESS: 0.00%
no CUDA-capable device is detected
no CUDA-capable device is detected
no CUDA-capable device is detected
no CUDA-capable device is detected
no CUDA-capable device is detected
no CUDA-capable device is detected
no CUDA-capable device is detected
  : 
```

**Comment by kyoro1** [comment]
@KeDengMS Thanks, After merging your modification, I confirmed as follows:

- Preparation: `set CUDA_VISIBLE_DEVICES=0,1,2,3`

- Case1: `python run_faster_rcnn.py` -> no problem
- Case2: `mpiexec -n 2 python run_faster_rcnn.py` -> maybe no problem.
  - `mAP` was different.. (0.7108, 0.6760)
- Case3: `mpiexec -n 4 python run_faster_rcnn.py` -> memory error.
  - I will raise issue for another record.

- The following is a log for Case 2:

```sh
C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN (master)
(ver2.2sgd) λ mpiexec -n 2 python run_faster_rcnn.py
Selected GPU[0] Tesla K80 as the process wide default device.
ping [requestnodes (before change)]: 2 nodes pinging each other
Selected GPU[0] Tesla K80 as the process wide default device.
ping [requestnodes (before change)]: 2 nodes pinging each other
ping [requestnodes (after change)]: 2 nodes pinging each other
ping [requestnodes (after change)]: 2 nodes pinging each other
requestnodes [MPIWrapperMpi]: using 2 out of 2 MPI nodes on a single host (2 requested); we (0) are in (participating)
requestnodes [MPIWrapperMpi]: using 2 out of 2 MPI nodes on a single host (2 requested); we (1) are in (participating)
ping [mpihelper]: 2 nodes pinging each other
ping [mpihelper]: 2 nodes pinging each other
Using base model:   AlexNet
lr_per_sample:      [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 1e-05]
Training model for 20 epochs.
Training 57820427 parameters in 27 parameter tensors.
PROGRESS: 0.00%
PROGRESS: 0.00%
Finished Epoch[1 of 20]: [Training] loss = 5.158435 * 21, metric = 62.39% * 21 18.906s (  1.1 samples/s);
PROGRESS: 0.00%
Finished Epoch[2 of 20]: [Training] loss = 3.408283 * 20, metric = 46.80% * 20 8.359s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[3 of 20]: [Training] loss = 3.082792 * 20, metric = 38.75% * 20 8.625s (  2.3 samples/s);
Finished Epoch[4 of 20]: [Training] loss = 2.567383 * 20, metric = 31.17% * 20 8.391s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[5 of 20]: [Training] loss = 2.197969 * 20, metric = 30.23% * 20 8.359s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[6 of 20]: [Training] loss = 1.973470 * 20, metric = 24.06% * 20 8.297s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[7 of 20]: [Training] loss = 1.794266 * 20, metric = 19.77% * 20 8.352s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[8 of 20]: [Training] loss = 1.676747 * 20, metric = 18.28% * 20 9.031s (  2.2 samples/s);
PROGRESS: 0.00%
Finished Epoch[9 of 20]: [Training] loss = 1.633366 * 20, metric = 20.78% * 20 8.844s (  2.3 samples/s);
Finished Epoch[10 of 20]: [Training] loss = 1.468312 * 20, metric = 16.64% * 20 8.486s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[11 of 20]: [Training] loss = 1.433293 * 20, metric = 17.66% * 20 8.359s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[12 of 20]: [Training] loss = 1.401409 * 20, metric = 16.72% * 20 8.232s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[13 of 20]: [Training] loss = 1.292891 * 20, metric = 17.42% * 20 8.375s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[14 of 20]: [Training] loss = 1.360878 * 20, metric = 16.33% * 20 8.422s (  2.4 samples/s);
Finished Epoch[15 of 20]: [Training] loss = 1.131498 * 20, metric = 14.45% * 20 8.438s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[16 of 20]: [Training] loss = 1.090316 * 20, metric = 14.22% * 20 8.516s (  2.3 samples/s);
PROGRESS: 0.00%
Finished Epoch[17 of 20]: [Training] loss = 1.122947 * 20, metric = 13.91% * 20 8.234s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[18 of 20]: [Training] loss = 1.068471 * 20, metric = 14.14% * 20 8.266s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[19 of 20]: [Training] loss = 1.035403 * 20, metric = 12.11% * 20 8.375s (  2.4 samples/s);
Finished Epoch[20 of 20]: [Training] loss = 0.980310 * 20, metric = 12.11% * 20 8.500s (  2.4 samples/s);
creating eval model
Stored eval model at C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN\Output\faster_rcnn_eval_AlexNet_e2e.model
Evaluating Faster R-CNN model for 5 images.
Number of rois before non-maximum suppression: 260
Number of rois  after non-maximum suppression: 43
AP for          gerkin = 0.5000
AP for          butter = 0.5556
AP for       champagne = 0.5000
AP for         joghurt = 1.0000
AP for            milk = 0.9167
AP for           onion = 0.0000
AP for         ketchup = 0.6667
AP for          tomato = 0.9667
AP for          orange = 1.0000
AP for         avocado = 0.6667
AP for          pepper = 0.6000
AP for         mustard = 1.0000
AP for          eggBox = 0.7500
AP for         tabasco = 1.0000
AP for           water = 0.5000
AP for     orangeJuice = 0.7500
Mean AP = 0.7108
Using base model:   AlexNet
lr_per_sample:      [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 1e-05]
Training model for 20 epochs.
Training 57820427 parameters in 27 parameter tensors.
PROGRESS: 0.00%
PROGRESS: 0.00%
Finished Epoch[1 of 20]: [Training] loss = 5.157951 * 21, metric = 62.31% * 21 19.422s (  1.1 samples/s);
PROGRESS: 0.00%
Finished Epoch[2 of 20]: [Training] loss = 3.408283 * 20, metric = 46.80% * 20 8.359s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[3 of 20]: [Training] loss = 3.082792 * 20, metric = 38.75% * 20 8.625s (  2.3 samples/s);
Finished Epoch[4 of 20]: [Training] loss = 2.567383 * 20, metric = 31.17% * 20 8.391s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[5 of 20]: [Training] loss = 2.197969 * 20, metric = 30.23% * 20 8.359s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[6 of 20]: [Training] loss = 1.973470 * 20, metric = 24.06% * 20 8.297s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[7 of 20]: [Training] loss = 1.794266 * 20, metric = 19.77% * 20 8.352s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[8 of 20]: [Training] loss = 1.676747 * 20, metric = 18.28% * 20 9.031s (  2.2 samples/s);
PROGRESS: 0.00%
Finished Epoch[9 of 20]: [Training] loss = 1.633366 * 20, metric = 20.78% * 20 8.844s (  2.3 samples/s);
Finished Epoch[10 of 20]: [Training] loss = 1.468312 * 20, metric = 16.64% * 20 8.486s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[11 of 20]: [Training] loss = 1.433293 * 20, metric = 17.66% * 20 8.359s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[12 of 20]: [Training] loss = 1.401409 * 20, metric = 16.72% * 20 8.216s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[13 of 20]: [Training] loss = 1.292891 * 20, metric = 17.42% * 20 8.406s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[14 of 20]: [Training] loss = 1.360878 * 20, metric = 16.33% * 20 8.406s (  2.4 samples/s);
Finished Epoch[15 of 20]: [Training] loss = 1.131498 * 20, metric = 14.45% * 20 8.438s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[16 of 20]: [Training] loss = 1.090316 * 20, metric = 14.22% * 20 8.516s (  2.3 samples/s);
PROGRESS: 0.00%
Finished Epoch[17 of 20]: [Training] loss = 1.122947 * 20, metric = 13.91% * 20 8.234s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[18 of 20]: [Training] loss = 1.068471 * 20, metric = 14.14% * 20 8.266s (  2.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[19 of 20]: [Training] loss = 1.035403 * 20, metric = 12.11% * 20 8.375s (  2.4 samples/s);
Finished Epoch[20 of 20]: [Training] loss = 0.980310 * 20, metric = 12.11% * 20 8.500s (  2.4 samples/s);
creating eval model
Stored eval model at C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN\Output\faster_rcnn_eval_AlexNet_e2e.model
Evaluating Faster R-CNN model for 5 images.
Number of rois before non-maximum suppression: 256
Number of rois  after non-maximum suppression: 44
AP for          eggBox = 0.7500
AP for         mustard = 1.0000
AP for          pepper = 1.0000
AP for         avocado = 0.3333
AP for          tomato = 0.9000
AP for           water = 0.5000
AP for          orange = 1.0000
AP for         tabasco = 0.2500
AP for          gerkin = 0.5000
AP for       champagne = 0.5000
AP for          butter = 1.0000
AP for            milk = 1.0000
AP for           onion = 0.0000
AP for         ketchup = 0.6667
AP for     orangeJuice = 0.7500
AP for         joghurt = 0.6667
Mean AP = 0.6760
-------------------------------------------------------------------
Build info:

                Built time: Sep 15 2017 07:42:32
                Last modified date: Fri Sep 15 04:28:56 2017
                Build type: Release
                Build target: GPU
                With 1bit-SGD: yes
                With ASGD: yes
                Math lib: mkl
                CUDA version: 8.0.0
                CUDNN version: 6.0.21
                Build Branch: HEAD
                Build SHA1: 23878e5d1f73180d6564b6f907b14fe5f53513bb
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
-------------------------------------------------------------------
Build info:

                Built time: Sep 15 2017 07:42:32
                Last modified date: Fri Sep 15 04:28:56 2017
                Build type: Release
                Build target: GPU
                With 1bit-SGD: yes
                With ASGD: yes
                Math lib: mkl
                CUDA version: 8.0.0
                CUDNN version: 6.0.21
                Build Branch: HEAD
                Build SHA1: 23878e5d1f73180d6564b6f907b14fe5f53513bb
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
```

**Comment by KeDengMS** [comment]
The current FasterRCNN example needs some modifications to enable distributed training:
1. It needs to use distributed_learner
2. The [reader](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/utils/od_mb_source.py) needs to handle partitions of data w.r.t. worker_rank and number_of_workers. Otherwise, all workers would receive the same data. That would not have any benefit in training speed, and is effectively just multiplying learning rate with the number of workers.
3. The config currently hardcoded GPU_ID 0 for all workers, which would not leverage multi-GPU rather than running several processes on the same GPU. I think the mem error you found is OOM when 4 processes are both using GPU 0. It needs to be removed and pass the default GPU selected by CNTK into gpu_nms. The current fix is a temporary one.

**Comment by kyoro1** [comment]
@KeDengMS @spandantiwari @ebarsoumMS 
Tentatively, I generated `FasterRCNN_train.py` script with my branch:
https://github.com/Microsoft/CNTK/blob/kyiwasak/faster-rcnn-distributed/Examples/Image/Detection/FasterRCNN/FasterRCNN_train.py

Histories: https://github.com/Microsoft/CNTK/commit/c5c4427e00b12aabaf65dd1d736f432f1359439b , https://github.com/Microsoft/CNTK/commit/ee64f51c361e6cf009d3284c784d6182a0ee977e

Then, can you advise what kind of changes are needed for 
```
It needs to be removed and pass the default GPU selected by CNTK into gpu_nms.
```
instead of temporary change https://github.com/Microsoft/CNTK/commit/62a80d2e8b7e720c52523fe92405cc14564e2443 ? If you support me, I'll change accordingly.

**Comment by KeDengMS** [comment]
Thanks kyoro1, the change has been merged into master. gpu_nms is not working properly so use cpu_nms instead.
