### ISSUE TITLE
CNTK running on Multiple Machines error

### ISSUE THREAD

**Issue by pakio** [Microsoft/CNTK#2393]
I updated CNTK to 2.2 to use it with NCCL2 , and trying to run [this program](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/AlexNet/Python/AlexNet_ImageNet_Distributed.py)  on multiple nodes.
But since I updated to CNTK 2.2 , I cannot run the program with multiple nodes.
I'm not using Infiniband and not sure if NCCL2 is supporting to run the program on multiple node without InfiniBand.

Maybe it is NCCL related error , but can anyone give me advice to work the program correctly?

this is the error message
```
Traceback (most recent call last):
  File "AlexNet_ImageNet_Distributed.py", line 253, in <module>
    gen_heartbeat=True)
  File "AlexNet_ImageNet_Distributed.py", line 202, in alexnet_train_and_eval
    train_and_test(network, trainer, train_source, test_source, minibatch_size, epoch_size, restore)
  File "AlexNet_ImageNet_Distributed.py", line 182, in train_and_test
    test_config= TestConfig(test_source, minibatch_size=minibatch_size)
  File "*/CNTK/bindings/python/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File */CNTK/bindings/python/cntk/train/training_session.py", line 276, in train
    super(TrainingSession, self).train(device)
  File "*/CNTK/bindings/python/cntk/cntk_py.py", line 3312, in train
    return _cntk_py.TrainingSession_train(self, computeDevice)
RuntimeError: NcclComm failed to initialize: unhandled system error. Set the ENV "NCCL_DEBUG=INFO" for more information.```

**Comment by KeDengMS** [comment]
NCCL2 should work without Infiniband. Can you `export NCCL_DEBUG=INFO` and check the output?

**Comment by pakio** [comment]
```
server01:9061:9061 [0] INFO Using internal Network Socket
server01:9061:9061 [0] INFO NET : Using interface enp0s25:*address*<0>
server01:9061:9061 [0] INFO NET : Using interface docker0:*address*<0>
server01:9061:9061 [0] INFO NET : Using interface vethc*address*<0>
server01:9061:9061 [0] INFO NET : Using interface vethe*address*<0>
server01:9061:9061 [0] INFO NET/Socket : 4 interfaces found
NCCL version 2.0.5 compiled with CUDA 8.0 
server02:3263:3263 [0] INFO Using internal Network Socket
server02:3263:3263 [0] INFO NET : Using interface enp0s25:*address*<0>
server02:3263:3263 [0] INFO NET : Using interface docker0:*address*<0>
server02:3263:3263 [0] INFO NET/Socket : 2 interfaces found
server01:9061:9061 [0] INFO Using 256 threads
server01:9061:9061 [0] INFO [0] Ring 0 :    0   1   
server01:9061:9061 [0] INFO [0] Ring 1 :    0   1   
server02:3263:3263 [0] INFO 0 -> 1 via NET/Socket/0
server01:9061:9061 [0] INFO 1 -> 0 via NET/Socket/0
server02:3263:3263 [0] INFO 0 -> 1 via NET/Socket/1
server01:9061:9061 [0] INFO 1 -> 0 via NET/Socket/1

server01:9061:9061 [0] include/socket.h:185 WARN Call to connect failed : Connection refused
server01:9061:9061 [0] INFO transport/net_socket.cu:103 -> 2
server01:9061:9061 [0] INFO include/net.h:28 -> 2 [Net]
server01:9061:9061 [0] INFO transport/net.cu:254 -> 2
server01:9061:9061 [0] INFO init.cu:373 -> 2
server01:9061:9061 [0] INFO init.cu:432 -> 2
Failed, NCCL error nvidia-sample.cu:88 'unhandled system error'

server02:3263:3263 [0] include/socket.h:185 WARN Call to connect failed : Connection refused
server02:3263:3263 [0] INFO transport/net_socket.cu:103 -> 2
server02:3263:3263 [0] INFO include/net.h:28 -> 2 [Net]
server02:3263:3263 [0] INFO transport/net.cu:254 -> 2
server02:3263:3263 [0] INFO init.cu:373 -> 2
server02:3263:3263 [0] INFO init.cu:432 -> 2
Failed, NCCL error nvidia-sample.cu:88 'unhandled system error'
```

this is the result of NCCL_DEBUG=INFO
it seems like OpenMPI is detecting docker as as network socket.
but i already added 
```
 btl_tcp_if_exclude = lo,docker0
```
to .openmpi/mca-params.conf

**Comment by pakio** [comment]
This is my fault 
I solved this problem my self
it was occurred by NCCL , added 
```
-x NCCL_SOCKET_IFNAME=^docker0 
```
to bashrc and it worked well

thank you for your advice !
