### ISSUE TITLE
Missing functionality to save and load an untrained (not trained) model in CNTK

### ISSUE THREAD

**Issue by imatiach-msft** [Microsoft/CNTK#2409]
The trainer (https://github.com/Microsoft/CNTK/blob/7034de260ee20fc0923709c3c3371f8ff8958d45/bindings/python/cntk/train/trainer.py) in the python API has an interface to save and restore from checkpoint, but there does not seem to be a way to save and load a model from scratch.  When calling save_checkpoint() and then using load_model() on the same file (instead of restore from checkpoint because I need to recreate a new model from scratch), the model loads fine but then on evaluation it seems to be missing some of the parameters, such as the loss function, and I get the error:

Function does not have 'loss_function' and it cannot be looked up in its outputs because it does not have exactly one
Traceback (most recent call last):
  File "/usr/bin/anaconda/lib/python2.7/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/usr/bin/anaconda/lib/python2.7/site-packages/cntk/train/training_session.py", line 377, in training_session
    progress_frequency, checkpoint_config, cv_config, test_config)
  File "/usr/bin/anaconda/lib/python2.7/site-packages/cntk/train/training_session.py", line 203, in __init__
    mb_source, model_inputs_to_streams = TrainingSession._sanitize_minibatch_source(mb_source, model_inputs_to_streams, trainer.loss_function)
  File "/usr/bin/anaconda/lib/python2.7/site-packages/cntk/ops/functions.py", line 483, in __getattr__
    "exactly one"%name)
AttributeError: Function does not have 'loss_function' and it cannot be looked up in its outputs because it does not have exactly one

Using pickle to serialize fails due to the C++ objects, the following code:

from cntk.ops.functions import load_model
import pickle
pickle.dump(trainer, open("/tmp/workdir15/my_special_model", "wb"))
model = pickle.load("/tmp/workdir15/my_special_model")

Failed with error:

can't pickle SwigPyObject objects
Traceback (most recent call last):
  File "/usr/bin/anaconda/lib/python2.7/pickle.py", line 1376, in dump
    Pickler(file, protocol).dump(obj)
  File "/usr/bin/anaconda/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/bin/anaconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/bin/anaconda/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/usr/bin/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/bin/anaconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/bin/anaconda/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/usr/bin/anaconda/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/usr/bin/anaconda/lib/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle SwigPyObject objects

I then tried to serialize each of the components of Trainer individually, and I was able to do this via 

network['ce'].save("/tmp/workdir15/my_cross_entropy")
network['pe'].save("/tmp/workdir15/my_classification_error")
network['output'].save("/tmp/workdir15/output")

followed by:

from cntk.cntk_py import Function
loss_function = Function.load("/tmp/workdir15/my_cross_entropy")
evaluation_function = Function.load("/tmp/workdir15/my_classification_error")
output = Function.load("/tmp/workdir15/output")

However, there is one parameter that I was not able to save an load for the trainer, the learner passed to the trainer: 

Trainer(network['output'], (network['ce'], network['pe']), **learner**, progress_printer)

Looking through the API, it looks like there only exists a "CreateCheckpoint" and "RestoreFromCheckpoint" in the Learner.cpp code, but these fail for my scenario because they 1.) require an existing learner when restoring (whereas I want to create one from scratch) and 2.) don't even checkpoint all of the data, eg in the LearnerMomentumSGD we don't serialize the momentumSchedule:

        LearnerMomentumSGD(const std::vector<Parameter>& parameters,
                           const LearningRateSchedule& learningRateSchedule,
                           const MomentumSchedule& momentumSchedule,
                           bool unitGain,
                           AdditionalLearningOptions additionalOptions,
                           bool allocateSmoothGradients = true)
                           : LearnerBase(parameters, learningRateSchedule, additionalOptions, allocateSmoothGradients),
                           m_momentumSchedule(momentumSchedule), 
                           m_unitGain(unitGain)
        { }

There needs to be some quick and easy "save" and static "load" on Trainer in the python API for users who want to build an untrained model, save it, and then restore it and train it.

**Comment by imatiach-msft** [comment]
I spoke to Alexey Reznichenko, it looks like this is a new feature that would need to be implemented in CNTK - currently the learners are not serializable
