### ISSUE TITLE
"CUDA failure 2: out of memory" for Faster R-CNN

### ISSUE THREAD

**Issue by kyoro1** [Microsoft/CNTK#2426]
In executing Faster R-CNN with `mpiexec` with multiple GPU, I encountered following errors:

- Environment:
  - NC24 in Azure(4-GPU)
  - CNTK: 2.2
  - python 3.5
- Environment variable: 
`set CUDA_VISIBLE_DEVICES=0,1,2,3`

I tested the following cases:
- Case1: `python run_faster_rcnn.py` -> no problem
- Case2: `mpiexec -n 2 python run_faster_rcnn.py` -> maybe no problem.
  - `mAP` was different.. (0.7108, 0.6760) [Reported here](https://github.com/Microsoft/CNTK/issues/2388#issuecomment-332840414)
- Case3: `mpiexec -n 4 python run_faster_rcnn.py` -> memory error.

I'd like to solve the case 3. Here is the log of it: 

```sh
C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN (master)
(ver2.2sgd) λ mpiexec -n 4 python run_faster_rcnn.py
Selected GPU[0] Tesla K80 as the process wide default device.
-------------------------------------------------------------------
Build info:

                Built time: Sep 15 2017 07:42:32
                Last modified date: Fri Sep 15 04:28:56 2017
                Build type: Release
                Build target: GPU
                With 1bit-SGD: yes
                With ASGD: yes
                Math lib: mkl
                CUDA version: 8.0.0
                CUDNN version: 6.0.21
                Build Branch: HEAD
                Build SHA1: 23878e5d1f73180d6564b6f907b14fe5f53513bb
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
CUDA failure 2: out of memory ; GPU=0 ; hostname=ABC-XYZ ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * AsMultipleOf(numElements, 2))
Retrying with reduced workspace memory for convolution
CUDA failure 17: invalid device pointer ; GPU=0 ; hostname=ABC-XYZ ; expr=cudaFree((void*) bufferPtr)
Retrying with reduced workspace memory for convolution
cuDNN failure 4: CUDNN_STATUS_INTERNAL_ERROR ; GPU=0 ; hostname=ABC-XYZ ; expr=finder(calgo, algoPerf)
Fall back to use static finder to get the algorithm for convolution
cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=ABC-XYZ ; expr=cudnnConvolutionBackwardData(*m_cudnn, &C::One, *m_kernelT, ptr(kernel), m_outT, ptr(srcGrad), *m_conv, m_backDataAlgo.selectedAlgo, ptr(workspace), workspace.BufferSize(), accumulateGradient ? &C::One : &C::Zero, m_inT, ptr(grad))
Using base model:   AlexNet
lr_per_sample:      [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 1e-05]
Training model for 20 epochs.
Training 57820427 parameters in 27 parameter tensors.
PROGRESS: 0.00%
Traceback (most recent call last):
  File "run_faster_rcnn.py", line 35, in <module>
    trained_model = train_faster_rcnn(cfg)
  File "C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 291, in train_faster_rcnn
    eval_model = train_faster_rcnn_e2e(cfg)
  File "C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 329, in train_faster_rcnn_e2e
    e2e_lr_per_sample_scaled, mm_schedule, cfg["CNTK"].L2_REG_WEIGHT, cfg["CNTK"].E2E_MAX_EPOCHS, cfg)
  File "C:\git\ver2.2\CNTK\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 571, in train_model
    trainer.train_minibatch(data)                                    # update model with it
  File "C:\Anaconda\envs\ver2.2sgd\lib\site-packages\cntk\train\trainer.py", line 170, in train_minibatch
    arguments, device)
  File "C:\Anaconda\envs\ver2.2sgd\lib\site-packages\cntk\cntk_py.py", line 2804, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
RuntimeError: cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=ABC-XYZ ; expr=cudnnConvolutionBackwardData(*m_cudnn, &C::One, *m_kernelT, ptr(kernel), m_outT, ptr(srcGrad), *m_conv, m_backDataAlgo.selectedAlgo, ptr(workspace), workspace.BufferSize(), accumulateGradient ? &C::One : &C::Zero, m_inT, ptr(grad))

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::DataTransferer::  operator= (x3)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfSamplesSeen
    - CNTK::Trainer::  TrainMinibatch (x2)
    - PyInit__cntk_py (x2)
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)
```

**Comment by KeDengMS** [comment]
The current FasterRCNN example needs some modifications to enable distributed training:
1.It needs to use distributed_learner
2.The reader needs to handle partitions of data w.r.t. worker_rank and number_of_workers. Otherwise, all workers would receive the same data. That would not have any benefit in training speed, and is effectively just multiplying learning rate with the number of workers.
3.The config currently hardcoded GPU_ID 0 for all workers, which would not leverage multi-GPU rather than running several processes on the same GPU. I think the mem error you found is OOM when 4 processes are both using GPU 0. It needs to be removed and pass the default GPU selected by CNTK into gpu_nms. The current fix is a temporary one.

**Comment by cha-zhang** [comment]
@KeDengMS can you take a look at https://github.com/Microsoft/CNTK/pull/2414?
