### ISSUE TITLE
MemoryError when installing CNTK in VirtualEnv

### ISSUE THREAD

**Issue by ArmageddonKnight** [Microsoft/CNTK#2439]
Hi, I am trying to install `CNTK` in a `virtualenv`. Is this supported? Because when I try to install, I got the following `MemoryError`

`Exception:
Traceback (most recent call last):
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/download.py", line 605, in _download_url
    consume(downloaded_chunks)
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 852, in consume
    deque(iterator, maxlen=0)
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/home/armageddonknight/VirtualEnv/Hello-CNTK/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError`

**Comment by liwchang** [comment]
I don't think we tested Virtualenv. Correct me if I am wrong. 
But we support Anaconda, which provides similar functionality.
Maybe you can try Anaconda.
