### ISSUE TITLE
FSAdagradUpdate -> Feature Not Implemented

### ISSUE THREAD

**Issue by Meai1** [Microsoft/CNTK#2441]
I'm just trying to run the Examples/LanguageUnderstanding/ATIS/Python sample but I get this error:
Is this supposed to be here? I disabled asgd because I dont have a GPU here except for Intel.

> (cntk-py36) pc@linux-94q0:~/cntk/CNTK/Examples/LanguageUnderstanding/ATIS/Python> python ./LanguageUnderstanding.py 
> Selected CPU as the process wide default device.
> Training 721482 parameters in 9 parameter tensors.
> 
> -------------------------------------------------------------------
> Build info: 
> 
> 		Built time: Oct  3 2017 16:52:16
> 		Last modified date: Sat Sep 30 15:13:53 2017
> 		Build type: release
> 		Build target: CPU-only
> 		With 1bit-SGD: no
> 		With ASGD: no
> 		Math lib: openblas
> 		Build Branch: master
> 		Build SHA1: b224a7d035fac5b6c167204b99f8205ec8f031dc (modified)
> 		MPI distribution: Open MPI
> 		MPI version: 1.10.3
> -------------------------------------------------------------------
> Example Sentence After 0 Epochs
> 	BOS	I-arrive_date.day_number
> 	flights	B-arrive_time.period_mod
> 	from	I-arrive_date.day_number
> 	new	B-fare_basis_code
> 	york	B-fare_basis_code
> 	to	B-fromloc.airport_name
> 	seattle	I-return_date.today_relative
> 	EOS	I-return_date.today_relative
> Learning rate per 1 samples: 0.003
> Inside File: Source/Math/Matrix.cpp  Line: 1796  Function: FSAdagradUpdate  -> Feature Not Implemented.
> Traceback (most recent call last):
>   File "./LanguageUnderstanding.py", line 205, in <module>
>     train(reader, model, max_epochs)
>   File "./LanguageUnderstanding.py", line 163, in train
>     callbacks=[progress_printer, progress_callback])
>   File "/home/pc/anaconda3/envs/cntk-py36/lib/python3.6/site-packages/cntk/ops/functions.py", line 1377, in train
>     ts.train()
>   File "/home/pc/anaconda3/envs/cntk-py36/lib/python3.6/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
>     result = f(*args, **kwds)
>   File "/home/pc/anaconda3/envs/cntk-py36/lib/python3.6/site-packages/cntk/train/training_session.py", line 276, in train
>     super(TrainingSession, self).train(device)
>   File "/home/pc/anaconda3/envs/cntk-py36/lib/python3.6/site-packages/cntk/cntk_py.py", line 3312, in train
>     return _cntk_py.TrainingSession_train(self, computeDevice)
> RuntimeError: Inside File: Source/Math/Matrix.cpp  Line: 1796  Function: FSAdagradUpdate  -> Feature Not Implemented.
> 
> [CALL STACK]
> [0x7fe7f2c3eedc]                                                       + 0x58aedc
> [0x7fe7ee766045]    Microsoft::MSR::CNTK::Matrix<float>::  FSAdagradUpdate  (Microsoft::MSR::CNTK::Matrix<float>&,  Microsoft::MSR::CNTK::Matrix<float>&,  double,  double,  double,  double,  float) + 0x1d5
>

**Comment by cha-zhang** [comment]
FSAdagrad has not been implemented on sparse data for CPU.

**Comment by haricntk** [comment]
> FSAdagrad has not been implemented on sparse data for CPU.

Is this issue was resolved? if yes, where to find the relevant link for reference
