### ISSUE TITLE
C# model evaluation fails with SEHException

### ISSUE THREAD

**Issue by mikhail-barg** [Microsoft/CNTK#2451]
We are using CNTK C# wrapper rather intensively to eval same model over and over again, and over time we get this (at random):

```
Fatal exception External component has thrown an exception. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   в CNTK.CNTKLibPINVOKE.FloatVector_Add(HandleRef jarg1, Single jarg2)
   в CNTK.FloatVector.Add(Single x)
   в CNTK.Helper.AsFloatVector[T](IEnumerable`1 input)
   в CNTK.Value.CreateBatch[T](NDShape sampleShape, IEnumerable`1 batch, DeviceDescriptor device, Boolean readOnly)
   ...
```
This is very unfortunate to have in a production code and we see no clear way how to investigate this further.

We are using CNTK v2.2 NuGet package.

**Comment by johansenmic** [comment]
Experiencing the same here using lates version 2.3.1 and CPU as device

**Comment by johansenmic** [comment]
Solution:
CNTK for C# still has bindings to VC++ 2013 runtime !!!
Install also VC++ 2013 runtime components for x64 and the exception goes away.

**Comment by whitmark** [comment]
Experiencing similar issue as @johansenmic using 2.3.1 CPU-Only as posted in  **Handling of input value list CNTK 2.x Evaluation vs legacy 1.x EvalDLL** #2706 

```
... Error: External component has thrown an exception.
Native CallStack:  at CNTK.CNTKLibPINVOKE.Function__Evaluate__SWIG_0(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, HandleRef jarg4)
at CNTK.Function._Evaluate(UnorderedMapVariableValuePtr arguments, UnorderedMapVariableValuePtr outputs, DeviceDescriptor computeDevice)
at CNTK.Function.Evaluate(IDictionary`2 inputs, IDictionary`2 outputs, Boolean createPersistentOutputValues, DeviceDescriptor computeDevice)
at CNTK.Function.Evaluate(IDictionary`2 inputs, IDictionary`2 outputs, DeviceDescriptor computeDevice)    
...
```
Unfortunately, updating to the most recent VC++ 2013 and 2015 redistributables did not resolve it.

![image](https://user-images.githubusercontent.com/8396992/35159634-dbb6795a-fd08-11e7-81c6-9ca3c3a98077.png)

Would welcome other ideas in #2706

**Comment by jakrivan** [comment]
I was having simmilar issue (on v2.3.0) and ended up installing VS redist 2013, 2015 and 2017 to solve my issue.

- VS redist 2015 is packed as prerequisity with CNTK release
- VS redist 2017 is mentioned in this and similar CNTK issues and in post from @liqunfu [Model Evaluation on Windows](https://docs.microsoft.com/en-us/cognitive-toolkit/cntk-library-evaluation-on-windows)
- VS redist 2013 is not mentioned, but after installing previous 2 I was still getting the error and complaint about missing MSVCR120.dll - which is part of 2013.

It would be nice to pack all needed prerequisities as part of the release (as used to be the case).

Thanks
Jan

**Comment by mikhail-barg** [comment]
Totally agree with @jakrivan, it would be great to have all the prerequisites built-in. Specifically, why not statically link the runtime?
