### ISSUE TITLE
build error of release

### ISSUE THREAD

**Issue by szhaomsft** [Microsoft/CNTK#2459]
use script to install dependencies on a machine without GPU

build with below error in VS 2015

8>  Finished generating code
16>  Using CNTK sources at 'C:\repos\cntk\Source'
16>  Using CNTK libs at 'C:\repos\cntk\x64\Release'
16>  Traceback (most recent call last):
16>    File ".\setup.py", line 95, in <module>
16>      shutil.copy(src_file, tgt_file)
16>    File "c:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntkdev-py35\lib\shutil.py", line 235, in copy
16>      copyfile(src, dst, follow_symlinks=follow_symlinks)
16>    File "c:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntkdev-py35\lib\shutil.py", line 114, in copyfile
16>      with open(src, 'rb') as fsrc:
16>  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\repos\\cntk\\x64\\Release\\nvml.dll'
16>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(41,5): error MSB3073: The command ".\vsbuild.bat "C:\repos\cntk\x64\Release\" "false" "true" "2.2" "c:\local\swigwin-3.0.10" "" "" "" "c:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntkdev-py35" """ exited with code 1.
8>  V2LibraryEndToEndTests.vcxproj -> C:\repos\cntk\x64\Release\V2LibraryEndToEndTests.exe

**Comment by cha-zhang** [comment]
Is this a clean build? We test build every time new code is checked in, so there shouldn't be a problem building the code...

**Comment by eldakms** [comment]
Please use Release_CPUOnly build on the top, not Release one, Release requires GPU and all dependencies to be present. Thank you!

![image](https://user-images.githubusercontent.com/12430061/31487499-20cc0a1c-af3b-11e7-879b-69a59c3e4237.png)
