### ISSUE TITLE
Anaconda Spyder doesn't start when CNTK installed

### ISSUE THREAD

**Issue by RayFireh** [Microsoft/CNTK#2490]
Windows 7 64bit
Anaconda 64bit latest (Python 3.6.2)
Spyder 3.2.3
CNTK 2.2 installed with pip from:
https://cntk.ai/PythonWheel/GPU/cntk-2.2-cp36-cp36m-win_amd64.whl
When CNTK is installed Spyder doesn't start:
`
Traceback (most recent call last):
  File "D:\Other\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Other\Anaconda3\lib\site-packages\spyder\app\start.py", line 140, in main
    from spyder.app import mainwindow
  File "D:\Other\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 78, in <module>
    from qtpy.compat import from_qvariant
  File "D:\Other\Anaconda3\lib\site-packages\qtpy\compat.py", line 15, in <module>
    from .QtWidgets import QFileDialog
  File "D:\Other\Anaconda3\lib\site-packages\qtpy\QtWidgets.py", line 22, in <module>
    from PyQt5.QtWidgets import *
ImportError: DLL load failed: The specified procedure could not be found.
`
When CNTK is removed with pip uninstall, then Spyder does work.

**Comment by machomachopadre** [comment]
Has anyone found a fix? I also have the same issue.

**Comment by mx-iao** [comment]
This should help - #2654
