### ISSUE TITLE
KeyError when collecting output of train_minibatch

### ISSUE THREAD

**Issue by calledbymountains** [Microsoft/CNTK#2520]
The relevant part of my snippet is as below : 

```
 feature_output = network['output'].find_by_name('fc8').outputs
 _, output = trainer.train_minibatch(data, (feature_output))
print(output.keys())
print(output[dict_keys(feature_output]))

```
It gives me an error as follows : 
```
dict_keys([Output('fc8', [#], [1000])])
Traceback (most recent call last):
  File "trainoverfeataccurate.py", line 325, in <module>
    warm_up=0, max_epochs=epochs)
  File "trainoverfeataccurate.py", line 250, in overfeataccuratetraining
    restore, profiling, print_freq=1)
  File "trainoverfeataccurate.py", line 145, in train_and_test
    print(output[feature_output])
KeyError: (Output('fc8', [#], [1000]),)

```
I also tried  `_, output = trainer.train_minibatch(data,{'a' : feature_output}) ` 
But it gives me the following error 
`TypeError: cannot convert key of dictionary to N4CNTK8VariableE`

What is the right approach to collect outputs when using `train_minibatch` ?

**Comment by calledbymountains** [comment]
I resolved it after careful examination : 

feature_output is obtained using `.outputs` which makes a `tuple`. Hence, using `output[dict_keys(feature_output)]`  makes python look for a tuple as a key which it does not find. 

The best approach I have found is 

```
fetches = []
# Append to this list 
```
and when using `train_minibatch` use `outputs=fetches`. Then when you want the output , use `fetches[i]` as the key name where `i` corresponds to the index of the feature you want.
