### ISSUE TITLE
Getting Top5 accuracy apart from Top1 accuracy

### ISSUE THREAD

**Issue by calledbymountains** [Microsoft/CNTK#2522]
This issue is related to a problem faced while trying to get around the problem stated in #2340 
I have a function to compute top5 accuracy as follows : 

```
def  top5_accuracy(batchsize, numclasses):
    feature = C.placeholder(shape=(batchsize, numclasses), name='feature')
    label = C.placeholder(shape=(batchsize, 1, numclasses), name='label')
    return C.classification_error(feature, label, topN=5)

```
In my training script (I have put only a small part for better utilizing the space) : 
```
feature_output = network['output'].find_by_name('fc8').output
fetches = [feature_output]
_, output = trainer.train_minibatch(data, fetches)
lbl = data[network['label']].as_sequences(network['label'])[0]
pe5 = top5train.eval({'feature':output[fetches[0]], 'label':lbl})

```

When I run my code here are the major pieces of message I receive : 

```
 /home/uujjwal/collection-stars/anaconda3/envs/cntk-test/lib/python3.6/site-packages/cntk/core.py:296: UserWarning: converting Value object to CSR format might be slow
  warnings.warn('converting Value object to CSR format might be slow')
/home/uujjwal/collection-stars/anaconda3/envs/cntk-test/lib/python3.6/site-packages/cntk/core.py:361: UserWarning: your data is of type "float32", but your input variable (uid "Placeholder3489") expects "None". Please convert your data beforehand to speed up training.

[CALL STACK]
[0x7f53d68eb38c]                                                       + 0x71638c
[0x7f53d69ccb47]    CNTK::Utils::  VerifyVariableValueCompatibility  (CNTK::Variable const&,  std::shared_ptr<CNTK::Value> const&,  CNTK::NDShape*) + 0x77
[0x7f53d693bbd2]    CNTK::CompositeFunction::  InferFreeDimensionsOfArguments  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&) + 0x142
[0x7f53d69405e7]    CNTK::CompositeFunction::  Forward  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&) + 0x447
[0x7f53d68f6f51]    CNTK::Function::  Forward  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&) + 0x81
[0x7f53d72a8657]                                                       + 0x67657
[0x7f53d74fac5b]                                                       + 0x2b9c5b
[0x7f53e79ed2cf]    PyCFunction_Call                                   + 0x5f
[0x7f53e7aa39b3]    _PyEval_EvalFrameDefault                           + 0x5693
[0x7f53e7a75f24]                                                       + 0x197f24
[0x7f53e7a76dc1]                                                       + 0x198dc1
[0x7f53e7a7cf95]                                                       + 0x19ef95
[0x7f53e7a9e62a]    _PyEval_EvalFrameDefault                           + 0x30a
[0x7f53e7a77c78]    PyEval_EvalCodeEx                                  + 0x6c8
[0x7f53e7a78806]                                                       + 0x19a806
[0x7f53e79ea16e]    PyObject_Call                                      + 0x3e
[0x7f53e7Traceback (most recent call last):
  File "trainoverfeataccurate.py", line 336, in <module>
    warm_up=0, max_epochs=epochs)
  File "trainoverfeataccurate.py", line 261, in overfeataccuratetraining
    restore, profiling, print_freq=1)
  File "trainoverfeataccurate.py", line 155, in train_and_test
    pe5 = top5train.eval({'feature':output[fetches[0]], 'label':lbl})
  File "/home/uujjwal/collection-stars/anaconda3/envs/cntk-test/lib/python3.6/site-packages/cntk/ops/functions.py", line 649, in eval
    _, output_map = self.forward(arguments, outputs, device=device, as_numpy=as_numpy)
  File "/home/uujjwal/collection-stars/anaconda3/envs/cntk-test/lib/python3.6/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/home/uujjwal/collection-stars/anaconda3/envs/cntk-test/lib/python3.6/site-packages/cntk/ops/functions.py", line 783, in forward
    keep_for_backward)
  File "/home/uujjwal/collection-stars/anaconda3/envs/cntk-test/lib/python3.6/site-packages/cntk/cntk_py.py", line 1886, in _forward
    return _cntk_py.Function__forward(self, *args)
RuntimeError: Unknown DataType.

```

- Why am I getting the` RunTimeError of Unknown Data Type` because in the feed dictionary to `.eval()` both my values have a data type of `np.float32` ?

- I understand the `UserWarning` regarding converting the data beforehand. But I am unable to see a way to do that. The labels I receive from the minibatch seem to be sparse due to one-hot encoding internally done. How can I handle this in an efficient way ?

- I ideally would have liked to evaluate multiple metrics within the trainer but it seems this feature is not available right now (judging from #2340 ) . Is anyone working on that ? If it is not possible for anyone to take it up immediately, I would like to work on that.

**Comment by cha-zhang** [comment]
Yes, this is a missing feature. We supported it in BrainScript, but Python API hasn't supported that. 

We are heavily resource constrained due to a few high-profile on-going projects (ONNX, Gluon, etc.) If you could help, it would be great. Thanks!

**Comment by calledbymountains** [comment]
Sure. I'd love to contribute it. I'll post some queries here if i get stuck at something major. i'll get on it from today

**Comment by Arkoprabho** [comment]
@calledbymountains @cha-zhang Any updates on this?

**Comment by cha-zhang** [comment]
@Arkoprabho Sorry I left the CNTK team last November. @ebarsoumMS is now in charge.
