### ISSUE TITLE
ImportError: cannot import name 'cntk_py'

### ISSUE THREAD

**Issue by Tar12** [Microsoft/CNTK#2558]
Did anyone even try the instructions on 
https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Python?tabs=cntkpy22

Both global and inside an environment doing
pip install https://cntk.ai/PythonWheel/GPU/cntk-2.2-cp35-cp35m-win_amd64.whl

on Windows 7 with Anaconda3 4.1.1, it gives

----------------------------
"Python 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1
900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cntk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\repos\cntk\bindings\python\cntk\__init__.py", line 10, in <module>
    from . import cntk_py
ImportError: cannot import name 'cntk_py'
---------------------------

Thanks!

**Comment by bencherian** [comment]
Why is CNTK getting grabbed from C:\repos\cntk\bindings? You most likely have PYTHONPATH set from an attempt at building from source. Make sure it's unset after activating your environment before starting python.
