### ISSUE TITLE
CUDA failure 30: unknown error - cudaMalloc

### ISSUE THREAD

**Issue by haixpham** [Microsoft/CNTK#2602]
when I call trainer.train_minibatch(data), I got this error message:

> Traceback (most recent call last):
  File "D:\vsproj\Speech_processing\Speech_processing\p3_train.py", line 95, in <module>
    main()
  File "D:\vsproj\Speech_processing\Speech_processing\p3_train.py", line 83, in main
    image_inputs, audio_inputs, G_output, D_output, G_loss, D_loss = train(mbs, num_minibatches=10000)
  File "D:\vsproj\Speech_processing\Speech_processing\p3_train.py", line 46, in train
    G_trainer.train_minibatch(G_batch_inputs)
  File "C:\Program Files\Anaconda3\lib\site-packages\cntk\train\trainer.py", line 173, in train_minibatch
    device)
  File "C:\Program Files\Anaconda3\lib\site-packages\cntk\cntk_py.py", line 2807, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: CUDA failure 30: unknown error ; GPU=0 ; hostname=HPZ440 ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * AsMultipleOf(numElements, 2))

> [CALL STACK]
     Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop (x2)
    - Microsoft::MSR::CNTK::GPUMatrix<float>::  Resize
    - Microsoft::MSR::CNTK::Matrix<float>::  Resize
    - Microsoft::MSR::CNTK::DataTransferer::  operator= (x4)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - Microsoft::MSR::CNTK::DataTransferer::  operator=
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfSamplesSeen
    - CNTK::Trainer::  TrainMinibatch

I am using CTNK 2.2 with Python 3.5. I checked the computational graphs of network model and loss functions (exported by logging.graph.plot()) , all are correct as expected. I believe it has something to do with data minibatch. Can anyone give me a pointer?

Thanks!

**Comment by haixpham** [comment]
I found out actual problem is with minibatch_size. I set MBS to 200 and the training procedure overflows the GPU memory. Reducing it to 60 makes it work. Never thought 12GB of VRAM could be all used up like that.
