### ISSUE TITLE
Getting class_weight must be dict error during train_svms.py

### ISSUE THREAD

**Issue by kpierce8** [Microsoft/CNTK#2604]
I'm running through the ObjectDetectionUsingCNTK model and I'm getting the following error while running the 4_trainSvm.py script. I'm running cntk_2.0 because of a script breaking change in 2.2. I'm using python 3.5 and win 10 64bit pro. Running gpu version.

>>> Updating avocado detector <<<
Cache holds 59 pos examples and 2130 neg examples
C:\Program Files\Anaconda3\envs\cntkgpu\lib\site-packages\sklearn\svm\classes.py:219: DeprecationWarning: loss='l1' has been deprecated in favor of loss='hinge' as of 0.16. Backward compatibility for the loss='l1' will be removed in 1.0
  DeprecationWarning)
Traceback (most recent call last):
  File "4_trainSvm.py", line 51, in <module>
    svm.train()
  File "C:\data\CodeProjects\ObjectDetectionUsingCntk\fastRCNN\train_svms.py", line 198, in train
    self.train_with_hard_negatives()
  File "C:\data\CodeProjects\ObjectDetectionUsingCntk\fastRCNN\train_svms.py", line 167, in train_with_hard_negatives
    self.trainers[j].append_neg_and_retrain(feat=hard_feat)
  File "C:\data\CodeProjects\ObjectDetectionUsingCntk\fastRCNN\train_svms.py", line 299, in append_neg_and_retrain
    new_w_b, pos_scores, neg_scores = self.train()
  File "C:\data\CodeProjects\ObjectDetectionUsingCntk\fastRCNN\train_svms.py", line 259, in train
    self.svm.fit(X, y)
  File "C:\Program Files\Anaconda3\envs\cntkgpu\lib\site-packages\sklearn\svm\classes.py", line 235, in fit
    self.loss, sample_weight=sample_weight)
  File "C:\Program Files\Anaconda3\envs\cntkgpu\lib\site-packages\sklearn\svm\base.py", line 855, in _fit_liblinear
    class_weight_ = compute_class_weight(class_weight, classes_, y)
  File "C:\Program Files\Anaconda3\envs\cntkgpu\lib\site-packages\sklearn\utils\class_weight.py", line 62, in compute_class_weight
    " got: %r" % class_weight)
ValueError: class_weight must be dict, 'balanced', or None, got: 'auto'

**Comment by kpierce8** [comment]
Found the error, or code update.
In the PARAMETERS file line 69 the svm_posweight should be set to 'balanced', not 'auto'
