### ISSUE TITLE
AdamLearner with L2 Regularization gives error on GPU in C# API

### ISSUE THREAD

**Issue by IvoTops** [Microsoft/CNTK#2641]
If I specify an L2 weight for the AdamLearner the error below follows during Training
__________________________________________________________________________________________

Using CNTK GPU v2.2, Windows10, VisualStudio2017, C#4.7
___________________________________________________________________________________________
System.ApplicationException occurred
  HResult=0x80131600
  Message=Inside File: C:/jenkins/workspace/CNTK-Build-Windows/Source/Math/GPUSparseMatrix.cu  Line: 2077  Function: Microsoft::MSR::CNTK::GPUSparseMatrix<ElemType>::ScaleAndAdd  -> Feature Not Implemented.

[CALL STACK]
    > Microsoft::MSR::CNTK::GPUSparseMatrix<float>::  ScaleAndAdd
    - Microsoft::MSR::CNTK::Matrix<float>::  ScaleAndAdd
    - CNTK::Internal::  ZeroesWithDynamicAxesLike (x2)
    - CNTK::  UniversalLearner
    - CNTK::TrainingParameterSchedule<unsigned __int64>::  Transform
    - CNTK::Trainer::  TotalNumberOfSamplesSeen
    - CNTK::Trainer::  TrainMinibatch (x2)
    - CSharp_CNTK_Trainer_TrainMinibatch__SWIG_0
    - 00007FF92F7FE61C (SymFromAddr() error: The specified module could not be found.)

  Source=Cntk.Core.Managed-2.2
  StackTrace:
   at CNTK.Trainer.TrainMinibatch(UnorderedMapVariableMinibatchData arguments, DeviceDescriptor computeDevice)
   at RTNeuralyticsLib.RTMLPredictValueCNTK`1.Train(Int32 minutes, MLModelResult setup) in D:\VSProjects\RT\RTNeuralyticsLib\RTMLPredictValueCNTK.cs:line 84

**Comment by douglas125** [comment]
How do you specify it? I am trying to do that as well...

**Comment by IvoTops** [comment]
You add it to the additionallearningoptions. Same as L1. See the C#
Examples for L1

Op 3 dec. 2017 05:41 schreef "douglas125" <notifications@github.com>:
