### ISSUE TITLE
CNTK 2.2 - CUBLAS failure 13 in fasterRCNN detectiondemo.py

### ISSUE THREAD

**Issue by pmfcdb** [Microsoft/CNTK#2647]
Hi, I was trying to run detectiondemo.py with default option fasterRCNN and I got this error:

Using windows 10 pro x64  build 16299  ( 4 x  nvidia gtx 1080, driver 388.13)

![err02](https://user-images.githubusercontent.com/22818355/33071969-870240fa-ceb5-11e7-81c2-005765dfb80a.png)

Thks,

**Comment by pmfcdb** [comment]
Update: With CNTK 2.3 I have the same problem:

![err03](https://user-images.githubusercontent.com/22818355/33175721-85193cb2-d054-11e7-9130-cb61f918b759.png)

Python 3.5.2 |Anaconda 4.1.1 (64-bit)
Opencv_python 3.3.0.10
Future 0.16.0
Pyyaml 3.11
Easydict 1.7
Numpy 1.13.3

**Comment by spandantiwari** [comment]
Which version of cuBLAS and cuDNN do you have installed?

**Comment by pmfcdb** [comment]
CUDA version: 9.0.10
CUDNN version: 6.0.21

**Comment by spandantiwari** [comment]
@pmfcdb We moved to CUDA 9 and cuDNN 7 in CNTK 2.4. You have CUDA 9 but with cuDNN 7. I don't believe we have tested the support for this configuration. It is possible that the cuBLAS failure you are seeing is because of that. Could you update to cuDNN 7 and try it again, if possible with CNTK 2.5 or at least 2.4, and see if you are able to run the example.

**Comment by pmfcdb** [comment]
Hello,

With set CUDA_VISIBLE_DEVICES=0 ( I tested with 2 nvidia geforce gtx 1080 )
I can run CNTK 2.5 ( CUDA version: 9.0.0 and  CUDNN version: 7.0.5 )
EX:
python DetectionDemo.py
Please provide a detector name as the single argument. Usage:
    python DetectionDemo.py <detector_name>
Available detectors: ['FastRCNN', 'FasterRCNN']
Using default detector: FasterRCNN
training FasterRCNN
Selected GPU[0] GeForce GTX 1080 as the process wide default device.
Using base model:   AlexNet
lr_per_sample:      [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 1e-05]
Training model for 20 epochs.
Training 57820427 parameters in 27 parameter tensors.


-------------------------------------------------------------------
Build info:

                Built time: Mar 15 2018 17:19:41
                Last modified date: Thu Mar 15 16:09:26 2018
                Build type: Release
                Build target: GPU
                With ASGD: yes
                Math lib: mkl
                CUDA version: 9.0.0
                CUDNN version: 7.0.5
                Build Branch: HEAD
                Build SHA1: 545a592f8399c4597c2587347a8b6bfb67cf07cd
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
PROGRESS: 0.00%
Finished Epoch[1 of 20]: [Training] loss = 2.152028 * 20, metric = 27.46% * 20 7.715s (  2.6 samples/s);
Finished Epoch[2 of 20]: [Training] loss = 1.257596 * 20, metric = 14.34% * 20 2.694s (  7.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[3 of 20]: [Training] loss = 1.001546 * 20, metric = 11.95% * 20 2.678s (  7.5 samples/s);
Finished Epoch[4 of 20]: [Training] loss = 0.841976 * 20, metric = 8.98% * 20 2.694s (  7.4 samples/s);
Finished Epoch[5 of 20]: [Training] loss = 0.751716 * 20, metric = 9.38% * 20 2.653s (  7.5 samples/s);
Finished Epoch[6 of 20]: [Training] loss = 0.667294 * 20, metric = 8.40% * 20 2.688s (  7.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[7 of 20]: [Training] loss = 0.609828 * 20, metric = 8.28% * 20 2.694s (  7.4 samples/s);
Finished Epoch[8 of 20]: [Training] loss = 0.581359 * 20, metric = 7.93% * 20 2.693s (  7.4 samples/s);
Finished Epoch[9 of 20]: [Training] loss = 0.506759 * 20, metric = 6.68% * 20 2.678s (  7.5 samples/s);
Finished Epoch[10 of 20]: [Training] loss = 0.479824 * 20, metric = 6.41% * 20 2.693s (  7.4 samples/s);
PROGRESS: 0.00%
Finished Epoch[11 of 20]: [Training] loss = 0.553501 * 20, metric = 7.77% * 20 2.666s (  7.5 samples/s);
Finished Epoch[12 of 20]: [Training] loss = 0.458333 * 20, metric = 6.64% * 20 2.700s (  7.4 samples/s);
Finished Epoch[13 of 20]: [Training] loss = 0.376930 * 20, metric = 5.43% * 20 2.670s (  7.5 samples/s);
PROGRESS: 0.00%
Finished Epoch[14 of 20]: [Training] loss = 0.392206 * 20, metric = 5.86% * 20 2.708s (  7.4 samples/s);
Finished Epoch[15 of 20]: [Training] loss = 0.348369 * 20, metric = 5.16% * 20 2.662s (  7.5 samples/s);
Finished Epoch[16 of 20]: [Training] loss = 0.349414 * 20, metric = 5.08% * 20 2.710s (  7.4 samples/s);
Finished Epoch[17 of 20]: [Training] loss = 0.318025 * 20, metric = 4.88% * 20 2.667s (  7.5 samples/s);
PROGRESS: 0.00%
Finished Epoch[18 of 20]: [Training] loss = 0.326578 * 20, metric = 5.00% * 20 2.676s (  7.5 samples/s);
Finished Epoch[19 of 20]: [Training] loss = 0.318443 * 20, metric = 5.12% * 20 2.698s (  7.4 samples/s);
Finished Epoch[20 of 20]: [Training] loss = 0.315645 * 20, metric = 4.96% * 20 2.698s (  7.4 samples/s);
creating eval model
Stored eval model at C:\local\cntk\Examples\Image\Detection\FasterRCNN\Output\faster_rcnn_eval_AlexNet_e2e.model
evaluating FasterRCNN
Evaluating Faster R-CNN model for 5 images.
Number of rois before non-maximum suppression: 600
Number of rois  after non-maximum suppression: 53
AP for         ketchup = 0.6667
AP for          pepper = 1.0000
AP for         joghurt = 1.0000
AP for     orangeJuice = 1.0000
AP for           onion = 1.0000
AP for          orange = 1.0000
AP for           water = 0.5000
AP for       champagne = 1.0000
AP for          gerkin = 1.0000
AP for          butter = 1.0000
AP for         mustard = 1.0000
AP for         tabasco = 1.0000
AP for         avocado = 1.0000
AP for          tomato = 1.0000
AP for            milk = 1.0000
AP for          eggBox = 1.0000
Mean AP = 0.9479

But with both it will crash with error:

CUBLAS failure 14: CUBLAS_STATUS_INTERNAL_ERROR ; GPU=0 ; hostname=DESKTOP-KFH7QLV ; expr=cublasgemmHelper(cuHandle, transA, transB, m, n, k, &alpha, a.Data(), (int) a.m_numRows, b.Data(), (int) b.m_numRows, &beta, c.Data(), (int) c.m_numRows)
Traceback (most recent call last):
  File "DetectionDemo.py", line 59, in <module>
    eval_model = od.train_object_detector(cfg)
  File "C:\local\cntk\Examples\Image\Detection\utils\od_utils.py", line 21, in train_object_detector
    eval_model = train_faster_rcnn(cfg)
  File "C:\local\cntk\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 291, in train_faster_rcnn
    eval_model = train_faster_rcnn_e2e(cfg)
  File "C:\local\cntk\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 329, in train_faster_rcnn_e2e
    e2e_lr_per_sample_scaled, mm_schedule, cfg["CNTK"].L2_REG_WEIGHT, cfg["CNTK"].E2E_MAX_EPOCHS, cfg)
  File "C:\local\cntk\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 571, in train_model
    trainer.train_minibatch(data)                                    # update model with it
  File "C:\Anaconda3\lib\site-packages\cntk\train\trainer.py", line 181, in train_minibatch
    arguments, device)
  File "C:\Anaconda3\lib\site-packages\cntk\cntk_py.py", line 3024, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
RuntimeError: CUBLAS failure 14: CUBLAS_STATUS_INTERNAL_ERROR ; GPU=0 ; hostname=DESKTOP-KFH7QLV ; expr=cublasgemmHelper(cuHandle, transA, transB, m, n, k, &alpha, a.Data(), (int) a.m_numRows, b.Data(), (int) b.m_numRows, &beta, c.Data(), (int) c.m_numRows)

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::GPUMatrix<float>::  MultiplyAndWeightedAdd
    - Microsoft::MSR::CNTK::Matrix<float>::  MultiplyAndWeightedAdd
    - Microsoft::MSR::CNTK::TensorView<float>::  DoMatrixProductOf
    - Microsoft::MSR::CNTK::TensorView<float>::  AssignMatrixProductOf
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this (x2)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfUnitsSeen
    - CNTK::Trainer::  TrainMinibatch (x2)
