### ISSUE TITLE
ImportError: DLL load failed:

### ISSUE THREAD

**Issue by AnupViAn** [Microsoft/CNTK#2648]
I set up the CNTK manually from source code as per the document.
[](https://docs.microsoft.com/en-us/cognitive-toolkit/setup-cntk-on-windows#cntk-python-environments)
Platform: Windows 8 (64-bit) only CPU
Environment variable for python are,
CNTK_PY35_PATH =  C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35
PYTHONPATH = c:\repos\cntk\bindings\python;%PYTHONPATH%

I build the CNTK in Release_CpuOnly configuration and everything is well up to this step. 
Now I am struggling to understand, where I have to activate cntk-py35 environment.
I tried it from "C:\local\Anaconda3-4.1.1-Windows-x86_64\script" and got an error below. I am new in this and don't have any prior knowledge but I am eager to learn CNTK so please help me out.

C:\local\Anaconda3-4.1.1-Windows-x86_64\Scripts>activate cntk-py35

(cntk-py35) C:\local\Anaconda3-4.1.1-Windows-x86_64\Scripts>python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v
.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cntk
Traceback (most recent call last):
  File "c:\repos\cntk\bindings\python\cntk\cntk_py.py", line 18, in swig_import_
helper
    return importlib.import_module(mname)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\importlib\__i
nit__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'cntk._cntk_py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\repos\cntk\bindings\python\cntk\__init__.py", line 10, in <module>
    from . import cntk_py
  File "c:\repos\cntk\bindings\python\cntk\cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "c:\repos\cntk\bindings\python\cntk\cntk_py.py", line 20, in swig_import_
helper
    return importlib.import_module('_cntk_py')
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\importlib\__i
nit__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified module could not be found.
>>>

**Comment by ebarsoumMS** [comment]
Did you launch your VS from your activated cntk-py35 conda prompt?

**Comment by AnupViAn** [comment]
@ebarsoumMS Thanks for the reply.
I missed adding "C:\repos\cntk\x64\Release_CpuOnly" path in the environment variable.
Now I am able to import CNTK in cntk-py35.
