### ISSUE TITLE
CNTK 2.3 CPU script installation - Environment update error

### ISSUE THREAD

**Issue by frankibem** [Microsoft/CNTK#2667]
I get the error message below when trying to upgrade from CNTK v2.2 to v2.3 (CPU only). Any suggestions will be appreciated.

> Fetching package metadata .............
> Solving package specifications: .
> Using Anaconda Cloud api site https://api.anaconda.org
> An unexpected error has occurred.
> Please consider posting the following information to the
> conda GitHub issue tracker at:
> 
>     https://github.com/conda/conda/issues
> 
> 
> 
> Current conda install:
> 
>                platform : win-64
>           conda version : 4.3.25
>        conda is private : False
>       conda-env version : 4.3.25
>     conda-build version : 1.21.3
>          python version : 3.5.2.final.0
>        requests version : 2.14.2
>        root environment : C:\local\Anaconda3-4.1.1-Windows-x86_64  (writable)
>     default environment : C:\local\Anaconda3-4.1.1-Windows-x86_64
>        envs directories : C:\local\Anaconda3-4.1.1-Windows-x86_64\envs
>                           C:\Users\souls\AppData\Local\conda\conda\envs
>                           C:\Users\souls\.conda\envs
>           package cache : C:\local\Anaconda3-4.1.1-Windows-x86_64\pkgs
>                           C:\Users\souls\AppData\Local\conda\conda\pkgs
>            channel URLs : https://repo.continuum.io/pkgs/free/win-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/r/win-64
>                           https://repo.continuum.io/pkgs/r/noarch
>                           https://repo.continuum.io/pkgs/pro/win-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>                           https://repo.continuum.io/pkgs/msys2/win-64
>                           https://repo.continuum.io/pkgs/msys2/noarch
>             config file : None
>              netrc file : None
>            offline mode : False
>              user-agent : conda/4.3.25 requests/2.14.2 CPython/3.5.2 Windows/10 Windows/10.0.15063    
>           administrator : True
> 
> `$ C:\local\Anaconda3-4.1.1-Windows-x86_64\Scripts\conda-env-script.py update --file C:\local\CNTK-2-3\cntk\Scripts\install\windows\conda-windows-cntk-py35-environment.yml --name C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35`
> 
> 
> 
> 
>     Traceback (most recent call last):
>       File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda_env\cli\main_update.py", line 106, in execute
>         installer.install(prefix, specs, args, env, prune=args.prune)
>       File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda_env\installers\pip.py", line 8, in install
>         pip_cmd = pip_args(prefix) + ['install', ] + specs
>     TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

**Comment by frankibem** [comment]
Removing the previous conda environment using `conda remove --name cntk-py35 -all `and rerunning install.bat fixed this issue.
