### ISSUE TITLE
Issue locating libnccl.so.2 (NCCL2) with CNTK 2.3 on Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by aschweig** [Microsoft/CNTK#2683]
After upgrading to CNTK 2.3, I saw the following stack trace when running a known-good training program for CNTK 2.3:

    $ python train.py
    Traceback (most recent call last):
      File "/home/username/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 18, in swig_import_helper
        return importlib.import_module(mname)
      File "/home/username/anaconda3/envs/cntk-py35/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
    ImportError: No module named 'cntk._cntk_py'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "train.py", line 7, in <module>
        import cntk as C
      File "/home/username/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/__init__.py", line 10, in <module>
        from . import cntk_py
      File "/home/username/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 21, in <module>
        _cntk_py = swig_import_helper()
      File "/home/username/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 20, in swig_import_helper
        return importlib.import_module('_cntk_py')
      File "/home/username/anaconda3/envs/cntk-py35/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    ImportError: libnccl.so.2: cannot open shared object file: No such file or directory

I tried unsuccessfully to resolve the issue by removing all existing dependencies and reinstalling CNTK.  I was able to resolve by modifying the LD_LIBRARY_PATH in activate_cntk as follows:

`export LD_LIBRARY_PATH="/home/username/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/libs/:/home/username/cntk/cntk/lib:/home/username/cntk/cntk/dependencies/lib:$LD_LIBRARY_PATH"`

**Comment by KeDengMS** [comment]
Can you share your install script? I just installed CNTK 2.3 Python wheel in a container of nvidia/cuda:8.0-cudnn6-runtime-ubuntu16.04, and everything is working.

**Comment by aschweig** [comment]
I installed from CNTK-2-3-Linux-64bit-GPU.tar.gz (cksum=3219862830).  I used the default ./cntk/Scripts/install/linux/install-cntk.sh script, which I have also attached (renamed to .txt so github will accept it.)

[install-cntk-sh.txt](https://github.com/Microsoft/CNTK/files/1507397/install-cntk-sh.txt)

**Comment by KeDengMS** [comment]
I see. The install-cntk.sh modified LD_LIBRARY_PATH, so <anaconda>/envs/cntk-py35/lib/python3.5/site-packages/cntk/libs was not searched for. You can add it to LD_LIBRARY_PATH to workaround. This is because the script sets up environment for both Python and BrainScript, and expects NCCL2 to be installed separately as CUDA8/cuDNN6. We'll update the docs to clarify that.
