### ISSUE TITLE
cntk image microsoft/cntk:2.2-cpu-python3.5  has a bug

### ISSUE THREAD

**Issue by shaheeng** [Microsoft/CNTK#2685]
I am using the cntk image microsoft/cntk:2.2-cpu-python3.5  from https://hub.docker.com/r/microsoft/cntk/

When I am in the python environment inside the container 'import cntk' does not work. See error log below

PS C:\Users\gshaheen\Documents\Docker\mytensorwlgbm> docker run -it microsoft/cntk:2.2-cpu-python3.5  /bin/bash

************************************************************
Welcome to Microsoft Cognitive Toolkit (CNTK) v. 2.2

Activating CNTK environment...

(Use command below to activate manually when needed)

  source "/cntk/activate-cntk"

************************************************************
CNTK is activated.

Please checkout tutorials and examples here:
  /cntk/Tutorials
  /cntk/Examples

To deactivate the environment run

  source /root/anaconda3/bin/deactivate

************************************************************
(/root/anaconda3/envs/cntk-py35) root@f1a7d9ccdadf:~# python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cntk
Traceback (most recent call last):
  File "/root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/root/anaconda3/envs/cntk-py35/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'cntk._cntk_py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/__init__.py", line 10, in <module>
    from . import cntk_py
  File "/root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "/root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "/root/anaconda3/envs/cntk-py35/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
>>>

**Comment by KeDengMS** [comment]
This is a known issue in 2.2 and it's fixed in 2.3. Please try install 2.2 Python wheels, or switch to 2.3 docker images
