### ISSUE TITLE
FastRCNN tutorial is broken

### ISSUE THREAD

**Issue by omri374** [Microsoft/CNTK#2692]
Hi,
Going over the tutorial here: 
https://docs.microsoft.com/en-us/cognitive-toolkit/Object-Detection-using-Fast-R-CNN

When running python run_fast_rcnn.py one gets an ImportException
Traceback (most recent call last):
  File "run_fast_rcnn.py", line 9, in <module>
    from FastRCNN_train import prepare, train_fast_rcnn
  File "/CNTK/Examples/Image/Detection/FastRCNN/FastRCNN_train.py", line 18, in <module>
    from cntk.learners import momentum_sgd, learning_parameter_schedule_per_sample, momentum_schedule
ImportError: cannot import name 'learning_parameter_schedule_per_sample'

I believe the CNTK code was changed but the example wasn't updated.
Thanks!

**Comment by kyoro1** [comment]
Related to [this comment](https://github.com/Microsoft/CNTK/commit/f1d6fc9ed6c2c6fed1c8adc0095d4c40e31c6e50#commitcomment-25711425)

**Comment by hellosaumil** [comment]
I'm facing a similar issue.

**Comment by hellosaumil** [comment]
@omri374 Hi, please refer to the previously referenced issue #2713 it has been fixed.

Please close this one if you are through with it. Otherwise, right back and I'll try to solve it.

**Comment by omri374** [comment]
@hellosaumil Thanks! It now works.

**Comment by hellosaumil** [comment]
@omri374 😄

**Comment by manya19** [comment]
Hi, 
I am facing a similar problem while trying to run the python run_fast_rcnn.py from the examples in Fast RCNN

(C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35) C:\local\CNTK-2-3\cntk\Examples\Image\Detection\FastRCNN>python run_fast_rcnn.py
Traceback (most recent call last):
  File "run_fast_rcnn.py", line 9, in <module>
    from FastRCNN_train import prepare, train_fast_rcnn
  File "C:\local\CNTK-2-3\cntk\Examples\Image\Detection\FastRCNN\FastRCNN_train.py", line 29, in <module>
    from utils.od_mb_source import ObjectDetectionMinibatchSource
  File "C:\local\CNTK-2-3\cntk\Examples\Image\Detection\FastRCNN\..\utils\od_mb_source.py", line 9, in <module>
    from utils.od_reader import ObjectDetectionReader
  File "C:\local\CNTK-2-3\cntk\Examples\Image\Detection\FastRCNN\..\utils\od_reader.py", line 8, in <module>
    import cv2 # pip install opencv-python
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cv2\__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: DLL load failed: The specified module could not be found.

I re-installed the python as well, but nothing worked.
