### ISSUE TITLE
Handling of input value list CNTK 2.x Evaluation vs legacy 1.x EvalDLL  

### ISSUE THREAD

**Issue by whitmark** [Microsoft/CNTK#2706]
In CNTK 2.3, I have trained and tested a simple feedforward classification model with 96 inputs and 2 classes using minibatches but now I want to evaluate a single sequence of inputs in a C# app.  In CNTK 1.x, this was straightforward using the legacy EvalDLL approach as follows:

```c#
List<float> DNNInputValueList = new List<float>();
. . .
List<float> outputs = null;	
// Add a list of feature values to dictionary
var inputs = new Dictionary<string, List<float>>();
inputs.Add("features", DNNInputValueList);							
outputs = modelUp.Evaluate(inputs, "P", 2);
```
and below is my attempt to refactor the code using the new CNTK2.3 methods: 
```c#
CNTK.Variable upFPP_Feature = upFPP_ModelFunc.Arguments[0];
CNTK.Variable upFPP_Label = upFPP_ModelFunc.Output;	
						
// Create input data map									
var upFPP_InputDataMap = new Dictionary<CNTK.Variable, CNTK.Value>() {
    { upFPP_Feature, DNNInputValueList }
};									

// Create output data map
var upFPP_OutputDataMap = new Dictionary<CNTK.Variable, CNTK.Value>() {
    { upFPP_Label, null }
};									
									
upFPP_ModelFunc.Evaluate(upFPP_InputDataMap, upFPP_OutputDataMap, mDeviceDescriptor);
```
However, its not allowing the conversion of the DNNInputValueList of 96 items to the CNTK.Value in the "Create input data map" section .  What is the proper way to do this?

**Comment by whitmark** [comment]
@ebarsoumMS, I see @liqunfu has been assigned this issue and many others, but hasn't responded to any issues since ~October 20.  Should these be reassigned?

**Comment by pprice** [comment]
@whitmark - The input map needs to be of `Value` type, currently `DNNInputValueList` is of `List<float>` type. You'll need to create a `Value` from your `List<float>`. 

Something like this: 
```csharp
NDShape myInputShape = new[] { 96 }; // Not sure of the actual shape, adjust accordingly 
var value = Value.CreateBatch(myInputShape, DNNInputValueList, mDeviceDescriptor);

var upFPP_InputDataMap = new Dictionary<CNTK.Variable, CNTK.Value>() {
    { upFPP_Feature, value }
};
```

**Comment by whitmark** [comment]
Thanks @pprice for the assist.  I wasn't able to implement your suggestion without throwing an error in the CreateBatch() function but I was able to get the following CreateBatch float () to run:

```c#
//Extract Features and Labels Variables from the model
CNTK.Variable upFPP_Feature = upFPP_Model.Arguments[0];
CNTK.Variable upFPP_Label = upFPP_Model.Output;	

//Get shape data for the input variable
NDShape upFPP_InputShape = upFPP_Feature.Shape;

//Assign List to float Array 
float[] upFPP_InputValue = new float[96];									
int i = 0;
foreach(float floatValue in DNNInputValueList)
{
    if (i < DNNInputValueList.Count)
        upFPP_InputValue[i] = DNNInputValueList[i];
    i++;										
}		

//Create CNTK.Value
CNTK.Value upFPP_Value = CNTK.Value.CreateBatch<float>(upFPP_InputShape, upFPP_InputValue, mDeviceDescriptor);									
									
//Map the variables and values for input
var upFPP_InputDataMap = new Dictionary<CNTK.Variable, CNTK.Value>() {
    { upFPP_Feature, upFPP_Value }
};

//Map the variables and values for input
var upFPP_OutputDataMap = new Dictionary<CNTK.Variable, CNTK.Value>() {
    { upFPP_Label, null }
};

//Evaluate the model.
upFPP_Model.Evaluate(upFPP_InputDataMap, upFPP_OutputDataMap, mDeviceDescriptor);


```
However, it is now throwing an error on the Evaluate call which is confusing since there are 96 inputs values defined in the input shape and float array.

```
Native CallStack:    at CNTK.CNTKLibPINVOKE.Function__Evaluate__SWIG_0(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, HandleRef jarg4)
   at CNTK.Function._Evaluate(UnorderedMapVariableValuePtr arguments, UnorderedMapVariableValuePtr outputs, DeviceDescriptor computeDevice)
   at CNTK.Function.Evaluate(IDictionary`2 inputs, IDictionary`2 outputs, Boolean createPersistentOutputValues, DeviceDescriptor computeDevice)
   at CNTK.Function.Evaluate(IDictionary`2 inputs, IDictionary`2 outputs, DeviceDescriptor computeDevice)
```
To make sure there was not an issue with the data, I assigned my own test data and the same error thrown:  

```c#
float[] upFPP_InputValue = new float[96] { 18.0000f, 25.0000f, 37.2539f, 38.0000f, 69.0000f, 308.5923f, 24.0000f, 25.0000f, 119.3144f, 25.0000f, 56.0000f, 409.1096f, 17.0000f, 12.0000f, 14.3800f, 21.0000f, 175.0000f, 874.2702f, 39.0000f, 150.0000f, 837.0163f, 1.0000f, 81.0000f, 528.4239f, 26.2500f, 105.0000f, 175.0000f, 874.2702f, 36.2500f, 45.5732f, 107.9352f, 111.4130f, 1.17f, 2.11f, 2.17f, 1.33f, 0.63f, 0.66f, 1.04f, 25.00f, 7.00f, 2.76f, 6.00f, 1.00f, 0.36f, 0.81f, 2.24f, 0.69f, 23.47f, 8.28f, 22.47f, 0.39f, 3.20f, 1.33f, 3.43f, 0.77f, 0.5385f, 1.0000f, 0.0256f, 0.6410f, 0.0000f, 0.4359f, 0.0000f, 0.1337f, 0.5027f, 0.6364f, 0.9358f, 1.0000f, 0.0000f, 0.0419f, 0.3892f, 0.5234f, 0.9838f, 1.0000f, 0.5125f, 0.5383f, 0.7526f, 0.8355f, 0.1196f, 0.1296f, 																		0.2161f, 0.2198f, 0.2504f, 0.2622f, 0.3028f, 0.3042f, 0.5067f, 0.4517f, 0.4862f, 0.4799f, 0.5023f, 2.6371f, 1.1378f, 0.9184f, 0.1020f, 0.2048f };	
```
Any suggestions would be most appreciated.  This was quite trivial in the legacy v1.x EvalDLL so would encourage the CNTK Team to provide more multi-variate, multi-class, end-to-end examples with real data.

**Comment by whitmark** [comment]
Looks like I formatted the input correctly but the SEHException was caused by not having all of the dependency dlls in place in the same directory as the third-party executable.  Also, since 2.2 additional dll dependencies are required per @liqunfu post on the [Model Evaluation on Windows](https://docs.microsoft.com/en-us/cognitive-toolkit/cntk-library-evaluation-on-windows) article.
