### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by hellosaumil** [Microsoft/CNTK#2714]
While running DetectionDemo.py under `Examples/Image/Detection` I get the following error:
`TypeError: 'NoneType' object is not subscriptable`

Detailed error:
```
Mean AP = 0.9604
detecting objects in image /notebooks/CNTKApps/Codes/Examples/Image/DataSets/Grocery/../DataSets/Grocery/testImages/WIN_20160803_11_28_42_Pro.jpg
Traceback (most recent call last):
  File "DetectionDemo.py", line 88, in <module>
    regressed_rois, cls_probs = od.evaluate_single_image(eval_model, img_path, cfg)
  File "/notebooks/CNTKApps/Codes/Examples/Image/Detection/utils/od_utils.py", line 75, in evaluate_single_image
    regressed_rois, cls_probs = evaluator.process_image(img_path)
  File "/notebooks/CNTKApps/Codes/Examples/Image/Detection/FasterRCNN/FasterRCNN_eval.py", line 27, in process_image
    out_cls_pred, out_rpn_rois, out_bbox_regr, dims = self.process_image_detailed(img_path)
  File "/notebooks/CNTKApps/Codes/Examples/Image/Detection/FasterRCNN/FasterRCNN_eval.py", line 34, in process_image_detailed
    _, cntk_img_input, dims = load_resize_and_pad(img_path, self._img_shape[2], self._img_shape[1])
  File "/notebooks/CNTKApps/Codes/Examples/Image/Detection/utils/plot_helpers.py", line 36, in load_resize_and_pad
    return resize_and_pad(img, width, height, pad_value)
  File "/notebooks/CNTKApps/Codes/Examples/Image/Detection/utils/plot_helpers.py", line 39, in resize_and_pad
    img_width = len(img[0])
TypeError: 'NoneType' object is not subscriptable

```

**Comment by hellosaumil** [comment]
Please refer #2715 ... This is a duplicate entry
