### ISSUE TITLE
upsample using convolution_transpose ops - something fishy or maybe the doc is unclear?

### ISSUE THREAD

**Issue by arijit17** [Microsoft/CNTK#2745]
Hi!

I can upsample an image (W=3, H=3) by factor of 2 using:
```
import cntk as C
import numpy as np
img = np.reshape(np.arange(9.0, dtype = np.float32), (1, 3, 3))
x = C.input_variable(img.shape)
size = (1,2,2)
kernel = C.constant(value = np.ones(size, dtype=np.float32))
C.convolution_transpose(kernel, x, auto_padding = [False], strides = size).eval({x: [img]})
```

Above code works when the number of input channel is 1 (i.e. 1x3x3) 

What if I want the number of input and output channels to be 2 and wish to upsample both the channels by a factor of 2? For example, this image (2x3x3):
`img = np.reshape(np.arange(18.0, dtype = np.float32), (2, 3, 3))`

What should be my size now?
`size = (2,2,2)` does not work!
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\cntk\ops\functions.py", line 687, in eval
    _, output_map = self.forward(arguments, outputs, device=device, as_numpy=as_numpy)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\cntk\ops\functions.py", line 821, in forward
    keep_for_backward)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\cntk\cntk_py.py", line 1892, in _forward
    return _cntk_py.Function__forward(self, *args)
RuntimeError: Mismatching outputShape and mapCount

[CALL STACK]
    > Microsoft::MSR::CNTK::ConvolutionEngine<float>::  Geometry
    - Microsoft::MSR::CNTK::ConvolutionEngine<float>::  MaxUnpooling
    - Microsoft::MSR::CNTK::ConvolutionEngine<float>::  BackwardData (x2)
    - Microsoft::MSR::CNTK::DataTransferer::  operator= (x2)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - Microsoft::MSR::CNTK::DataTransferer::  operator=
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - PyInit__cntk_py (x2)
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)
```
From the [doc](https://www.cntk.ai/pythondocs/cntk.ops.html?highlight=convolution_transpose#cntk.ops.convolution_transpose) I thought it should be
`size = (2,2,2,2)`
It doesn't work either!
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\cntk\ops\__init__.py", line 352, in convolution_transpose
    output_shape, dilation, reduction_rank, max_temp_mem_size_in_samples, name)
ValueError: Convolution stride tensor must have rank 1 or the same as the output tensor.

[CALL STACK]
    > Microsoft::MSR::CNTK::DataTransferer::  operator=
    - CNTK::NDMask::  MaskedCount (x2)
    - CNTK::Function::  ~Function
    - CNTK_ReleaseModel
    - RtlRunOnceExecuteOnce
    - InitOnceExecuteOnce
    - _crtInitOnceExecuteOnce
    - CNTK_ReleaseModel
    - CNTK::Function::  RawOutputs
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  ~Function
    - CNTK_ReleaseModel
    - RtlRunOnceExecuteOnce
    - InitOnceExecuteOnce
    - _crtInitOnceExecuteOnce
```

I'm using CNTK '2.3.1'
Windows 10, Python 3.5

Similar issues can be found here #2606

**Comment by jeandebleau** [comment]
I did not test it but first the stride should be (1,2,2) and not equal to the kernel size (2,2,2,2). 

Secondly if you want to upsample each channel separately, you need to change the kernel because the one with ones everywhere will also mix the channel together. 

You need a kernel like this one so that each channel are filtered independently:
k = np.zeros( (2,2,2,2) ,  dtype = np.float32)) 
k[0,0,:,:] = np.ones( (2,2) ,  dtype = np.float32)) 
k[1,1,:,:] = np.ones( (2,2) ,  dtype = np.float32))

**Comment by arijit17** [comment]
Thanks @jeandebleau 
Very informative! It works!
