### ISSUE TITLE
Any specifications about  train_map.txt/val_map.txt of Imagenet dataset?

### ISSUE THREAD

**Issue by giantpoplar** [Microsoft/CNTK#2778]
I want to train resnet-50 on ILSVRC2012-**VAL** dataset.  I start from this script 
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/Python/TrainResNet_ImageNet_Distributed.py

But there is not an installation script as mentioned : https://github.com/Microsoft/CNTK/issues/2091
I write a script to generate train_map.txt/val_map.txt  by using ILSVRC2012_validation_ground_truth.txt in ILSVRC2012_devkit_t12. I try two format but doesn't work.

I find few information(just code notes in TrainResNet_ImageNet_Distributed.py) about the format of a map file used in cntk. And I am not familiar with cntk's source code.
So could anybody  give  me  any advice on this problem?

**Here are the errors:**
Format 1. lines in val_map.txt like this(there are two tabs in the middle blanks)
this format is similar with https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/Python/TrainResNet_CIFAR10_Distributed.py
and
https://github.com/Microsoft/CNTK/blob/master/Tests/EndToEndTests/Image/AlexNet/train_map.txt

`/var/dataset/imagenet/cntk/val/00000001.JPEG        489  ` 
`/var/dataset/imagenet/cntk/val/00000002.JPEG        360` 
I get an error:
`RuntimeError: Invalid numeric sequence id '/var/dataset/imagenet/cntk/val/00000001.JPEG`

Format 2. lines in val_map.txt like this
`00000001.JPEG       489` 
`00000002.JPEG       360`
but I get an error:
`RuntimeError: Cannot open file ''`

**Following are the details:**
CNTK version :
 prebuilt version
2.3.1 GPU Python2.7  https://cntk.ai/PythonWheel/GPU/cntk-2.3.1-cp27-cp27mu-linux_x86_64.whl
CNTK source path:
`/home/chongyang/ddl/cntk/CNTK/Examples/Image/Classification/ResNet/Python`
Data path:
`(ck-py27) [chongyang@gpu2 Python]$ ls /var/dataset/imagenet/cntk/`
`ImageNet1K_intensity.xml  ImageNet1K_mean.xml  train  train_map.txt  val  val_map.txt`

OS:centos7.3,Python:Python 2.7.13 :: Continuum Analytics, Inc.

I modify TrainResNet_ImageNet_Distributed.py with hard code path
`219     mean_data = os.path.join("/var/dataset/imagenet/cntk/", 'ImageNet1K_mean.xml')`
`220     train_data = os.path.join("/var/dataset/imagenet/cntk/train/", 'train_map.txt')`
`221     test_data = os.path.join("/var/dataset/imagenet/cntk/val/", 'val_map.txt')`

**In Fromat1,full error information**
```
(ck-py27) [chongyang@gpu2 Python]$ python TrainResNet_ImageNet_Distributed.py 
Start training: quantize_bit = 32, epochs = 10, distributed_after = 0
ping [requestnodes (before change)]: 1 nodes pinging each other
ping [requestnodes (after change)]: 1 nodes pinging each other
requestnodes [MPIWrapperMpi]: using 1 out of 1 MPI nodes on a single host (1 requested); we (0) are in (participating)
ping [mpihelper]: 1 nodes pinging each other
-------------------------------------------------------------------
Build info: 

		Built time: Nov 22 2017 21:46:56
		Last modified date: Mon Nov 13 23:32:21 2017
		Build type: release
		Build target: GPU
		With 1bit-SGD: no
		With ASGD: yes
		Math lib: mkl
		CUDA version: 8.0.0
		CUDNN version: 6.0.21
		Build Branch: HEAD
		Build SHA1: feade5b1bc1fbe6a8fc13b214f66aa89dac0db53
		MPI distribution: Open MPI
		MPI version: 1.10.7
-------------------------------------------------------------------
Selected GPU[0] Tesla P100-PCIE-16GB as the process wide default device.
/var/dataset/imagenet/cntk/train/train_map.txt ===== <cntk.io.MinibatchSource; proxy of <Swig Object of type 'CNTK::MinibatchSourcePtr *' at 0x2aec6e546de0> >
Traceback (most recent call last):
  File "TrainResNet_ImageNet_Distributed.py", line 241, in <module>
    profiling=args['profile'])
  File "TrainResNet_ImageNet_Distributed.py", line 181, in resnet_imagenet
    test_source = create_image_mb_source(test_data, mean_data, train=False, total_number_of_samples=C.io.FULL_DATA_SWEEP)
  File "TrainResNet_ImageNet_Distributed.py", line 63, in create_image_mb_source
    multithreaded_deserializer=True)
  File "/home/chongyang/custom_libs/anaconda3/envs/ck-py27/lib/python2.7/site-packages/cntk/io/__init__.py", line 226, in __init__
    source = cntk_py.create_composite_minibatch_source(config)
RuntimeError: Invalid numeric sequence id '/var/dataset/imagenet/cntk/val/00000001.JPEG'

[CALL STACK]
[0x2aecdfaf12ec]                                                       + 0x192ec
[0x2aecdfaf1334]                                                       + 0x19334
[0x2aecdfd46947]    CNTK::ImageDataDeserializer::  CreateSequenceDescriptions  (std::shared_ptr<CNTK::CorpusDescriptor>,  std::string,  unsigned long,  bool) + 0x697
[0x2aecdfd475db]    CNTK::ImageDataDeserializer::  ImageDataDeserializer  (std::shared_ptr<CNTK::CorpusDescriptor>,  Microsoft::MSR::CNTK::ConfigParameters const&,  bool) + 0x42b
[0x2aecdfd3fbb1]    CreateDeserializer                                 + 0xb1
[0x2aecdfaecd67]    CNTK::CompositeDataReader::  CreateDeserializer  (Microsoft::MSR::CNTK::ConfigParameters const&,  bool) + 0x1d7
[0x2aecdfaed161]    CNTK::CompositeDataReader::  CreateDeserializers  (Microsoft::MSR::CNTK::ConfigParameters const&) + 0x281
[0x2aecdfaedb1a]    CNTK::CompositeDataReader::  CompositeDataReader  (Microsoft::MSR::CNTK::ConfigParameters const&) + 0x75a
[0x2aecdfaf7b06]    CreateCompositeDataReader                          + 0x26
[0x2aeca2eccaa0]    CNTK::CompositeMinibatchSource::  CompositeMinibatchSource  (CNTK::MinibatchSourceConfig const&) + 0x5f0
[0x2aeca2eccee7]    CNTK::  CreateCompositeMinibatchSource  (CNTK::MinibatchSourceConfig const&) + 0x27
[0x2aeca2357759]                                                       + 0x11f759
[0x2aec5a3971e5]    PyEval_EvalFrameEx                                 + 0x7b35
[0x2aec5a398c3e]    PyEval_EvalCodeEx                                  + 0x89e
[0x2aec5a313b68]                                                       + 0x79b68
[0x2aec5a2e3e93]    PyObject_Call                                      + 0x53
[0x2aec5a2f664f]                                                       + 0x5c64f
[0x2aec5a2e3e93]    PyObject_Call                                      + 0x53
[0x2aec5a353e70]                                                       + 0xb9e70
[0x2aec5a347568]                                                       + 0xad568
[0x2aec5a2e3e93]    PyObject_Call                                      + 0x53
[0x2aec5a39680d]    PyEval_EvalFrameEx                                 + 0x715d
[0x2aec5a398c3e]    PyEval_EvalCodeEx                                  + 0x89e
[0x2aec5a3981f7]    PyEval_EvalFrameEx                                 + 0x8b47
[0x2aec5a398c3e]    PyEval_EvalCodeEx                                  + 0x89e
[0x2aec5a3981f7]    PyEval_EvalFrameEx                                 + 0x8b47
[0x2aec5a398c3e]    PyEval_EvalCodeEx                                  + 0x89e
[0x2aec5a398d52]    PyEval_EvalCode                                    + 0x32
[0x2aec5a3b9450]    PyRun_FileExFlags                                  + 0xb0
[0x2aec5a3b962f]    PyRun_SimpleFileExFlags                            + 0xef
[0x2aec5a3cefd4]    Py_Main                                            + 0xca4
[0x2aec5afdcb35]    __libc_start_main                                  + 0xf5
[0x400729]                       
```

**In Fromat2,full error information**
```
(ck-py27) [chongyang@gpu2 Python]$ python TrainResNet_ImageNet_Distributed.py 
Start training: quantize_bit = 32, epochs = 10, distributed_after = 0
ping [requestnodes (before change)]: 1 nodes pinging each other
ping [requestnodes (after change)]: 1 nodes pinging each other
requestnodes [MPIWrapperMpi]: using 1 out of 1 MPI nodes on a single host (1 requested); we (0) are in (participating)
ping [mpihelper]: 1 nodes pinging each other
-------------------------------------------------------------------
Build info: 

		Built time: Nov 22 2017 21:46:56
		Last modified date: Mon Nov 13 23:32:21 2017
		Build type: release
		Build target: GPU
		With 1bit-SGD: no
		With ASGD: yes
		Math lib: mkl
		CUDA version: 8.0.0
		CUDNN version: 6.0.21
		Build Branch: HEAD
		Build SHA1: feade5b1bc1fbe6a8fc13b214f66aa89dac0db53
		MPI distribution: Open MPI
		MPI version: 1.10.7
-------------------------------------------------------------------
Selected GPU[0] Tesla P100-PCIE-16GB as the process wide default device.
/var/dataset/imagenet/cntk/train/train_map.txt ===== <cntk.io.MinibatchSource; proxy of <Swig Object of type 'CNTK::MinibatchSourcePtr *' at 0x2b0c5ec2fde0> >
/var/dataset/imagenet/cntk/val/val_map.txt ===== <cntk.io.MinibatchSource; proxy of <Swig Object of type 'CNTK::MinibatchSourcePtr *' at 0x2b0c5ec2ffc0> >
[line 143] <cntk.io.MinibatchSource; proxy of <Swig Object of type 'CNTK::MinibatchSourcePtr *' at 0x2b0c5ec2ffc0> >
Traceback (most recent call last):
  File "TrainResNet_ImageNet_Distributed.py", line 241, in <module>
    profiling=args['profile'])
  File "TrainResNet_ImageNet_Distributed.py", line 183, in resnet_imagenet
    train_and_test(network, trainer, train_source, test_source, minibatch_size, epoch_size, restore, profiling)
  File "TrainResNet_ImageNet_Distributed.py", line 151, in train_and_test
    test_config=TestConfig(test_source, minibatch_size)
  File "/home/chongyang/custom_libs/anaconda3/envs/ck-py27/lib/python2.7/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/home/chongyang/custom_libs/anaconda3/envs/ck-py27/lib/python2.7/site-packages/cntk/train/training_session.py", line 332, in train
    super(TrainingSession, self).train(device)
  File "/home/chongyang/custom_libs/anaconda3/envs/ck-py27/lib/python2.7/site-packages/cntk/cntk_py.py", line 3361, in train
    return _cntk_py.TrainingSession_train(self, computeDevice)
RuntimeError: Cannot open file ''

[CALL STACK]
[0x2b0cdef1f23c]                                                       + 0x3b23c
[0x2b0cdef287ad]    CNTK::ImageDataDeserializer::ImageChunk::  GetSequence  (unsigned long,  std::vector<std::shared_ptr<CNTK::SequenceDataBase>,std::allocator<std::shared_ptr<CNTK::SequenceDataBase>>>&) + 0x2ad
[0x2b0c95fd212f]                                                       + 0xca212f
[0x2b0c95040c53]    __kmp_invoke_microtask                             + 0x93
[0x2b0c95010357]                                                       + 0x84357
[0x2b0c9500f9d5]                                                       + 0x839d5
[0x2b0c95041133]                                                       + 0xb5133
[0x2b0c4ad86dc5]                                                       + 0x7dc5
[0x2b0c4b79b73d]    clone                                              + 0x6d

```

**Comment by giantpoplar** [comment]
there must be **one** tab in map_train.txt map_val.txt
two tab will produce an error 😂
