### ISSUE TITLE
i installed CNTK through pip for python3.6, when i try to import it ModuleNotFoundError: No module named 'cntk._cntk_py' error

### ISSUE THREAD

**Issue by ay12496** [Microsoft/CNTK#2803]
Traceback (most recent call last):
  File "C:\Users\Abhishek\AppData\Local\Programs\Python\Python36\lib\site-packages\cntk\cntk_py.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Abhishek\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cntk._cntk_py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Abhishek\AppData\Local\Programs\Python\Python36\lib\site-packages\cntk\__init__.py", line 10, in <module>
    from . import cntk_py
  File "C:\Users\Abhishek\AppData\Local\Programs\Python\Python36\lib\site-packages\cntk\cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "C:\Users\Abhishek\AppData\Local\Programs\Python\Python36\lib\site-packages\cntk\cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "C:\Users\Abhishek\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified module could not be found.

**Comment by dhinar1991** [comment]
Hi @ay12496  did u find any solution? i get the same error even after adding path to system variable.

**Comment by ay12496** [comment]
It didn't work for windows with simple pip installation, but using anaconda I was able to get it work.
For ubuntu(linux) I was able to get it work with simple pip installation.
