### ISSUE TITLE
L2 Regularization with Sparse Matricies

### ISSUE THREAD

**Issue by nsombuntham** [Microsoft/CNTK#2850]
Hi,

I am trying to implement a classifier using Glove word embeddings with L2 regularization.  

However, when I set the l2_regularization_weight parameter on the learner, I get the errors as shown below (feature not implemented on GPUSparseMatrix).

I have tried to make Glove vectors static (using the weights parameter in layer.Embeddings) so that gradient calculation is not required for the sparse matrix but it still does not work.

Is it possible to have sparse inputs and L2 regularization in CNTK?  Is there work around on this issue?

Thanks,
Natat

```
Inside File: Source/Math/GPUSparseMatrix.cu  Line: 2033  Function: ScaleAndAdd  -> Feature Not Implemented.
Traceback (most recent call last):
  File "/hdfs/pnrsy//aether/prod/5342a45a-aaf5-4005-b080-ce4e918373ee@@@-Py3--Test--Philly-_Run_CNTK_Python@@@a0880ef1@@@1-17-2018_01-33-24_AM/config/train_script.py", line 501, in <module>
    tensorboard_logdir=args['tensorboard_logdir'])
  File "/hdfs/pnrsy//aether/prod/5342a45a-aaf5-4005-b080-ce4e918373ee@@@-Py3--Test--Philly-_Run_CNTK_Python@@@a0880ef1@@@1-17-2018_01-33-24_AM/config/train_script.py", line 406, in convnet_cifar10_dataaug
    train_and_test(network, trainer, train_source, val_source, test_source, minibatch_size, epoch_size, restore, profiling)
  File "/hdfs/pnrsy//aether/prod/5342a45a-aaf5-4005-b080-ce4e918373ee@@@-Py3--Test--Philly-_Run_CNTK_Python@@@a0880ef1@@@1-17-2018_01-33-24_AM/config/train_script.py", line 358, in train_and_test
    test_config = TestConfig(test_source)
  File "/var/storage/shared/pnrsy/sys/jobs/application_1515637172012_1815/.local/lib/python3.4/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/var/storage/shared/pnrsy/sys/jobs/application_1515637172012_1815/.local/lib/python3.4/site-packages/cntk/train/training_session.py", line 276, in train
    super(TrainingSession, self).train(device)
  File "/var/storage/shared/pnrsy/sys/jobs/application_1515637172012_1815/.local/lib/python3.4/site-packages/cntk/cntk_py.py", line 2998, in train
    return _cntk_py.TrainingSession_train(self, computeDevice)
RuntimeError: Inside File: Source/Math/GPUSparseMatrix.cu  Line: 2033  Function: ScaleAndAdd  -> Feature Not Implemented.

[CALL STACK]
[0x7f9ceeb22bbc]                                                       + 0x54bbbc
[0x7f9cebdb502e]    Microsoft::MSR::CNTK::GPUSparseMatrix<float>::  ScaleAndAdd  (float,  Microsoft::MSR::CNTK::GPUSparseMatrix<float> const&,  float,  Microsoft::MSR::CNTK::GPUMatrix<float> const&,  Microsoft::MSR::CNTK::GPUMatrix<float>&) + 0x31e
[0x7f9cebd13f74]    Microsoft::MSR::CNTK::Matrix<float>::  ScaleAndAdd  (float,  Microsoft::MSR::CNTK::Matrix<float> const&,  Microsoft::MSR::CNTK::Matrix<float>&) + 0x264
[0x7f9ceed25d3b]    void CNTK::LearnerBase::  PreProcess  <float>(std::shared_ptr<CNTK::NDArrayView> const&,  std::shared_ptr<CNTK::NDArrayView> const&,  unsigned long) const + 0x12b
[0x7f9ceed28446]    void CNTK::LearnerBase::  Update  <float>(CNTK::Parameter const&,  std::shared_ptr<CNTK::NDArrayView> const&,  std::shared_ptr<CNTK::NDArrayView> const&,  unsigned long) const + 0x36
[0x7f9ceed22224]    CNTK::LearnerBase::  Update  (std::unordered_map<CNTK::Parameter,std::shared_ptr<CNTK::NDArrayView>,std::hash<CNTK::Parameter>,std::equal_to<CNTK::Parameter>,std::allocator<std::pair<CNTK::Parameter const,std::shared_ptr<CNTK::NDArrayView>>>>&,  unsigned long,  bool) + 0x134
[0x7f9ceecfc3a2]    CNTK::Learners::  Update  (std::unordered_map<CNTK::Parameter,std::shared_ptr<CNTK::NDArrayView>,std::hash<CNTK::Parameter>,std::equal_to<CNTK::Parameter>,std::allocator<std::pair<CNTK::Parameter const,std::shared_ptr<CNTK::NDArrayView>>>>&,  unsigned long,  bool) + 0x162
[0x7f9ceecf00c1]    CNTK::Trainer::  TrainLocalMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  bool,  CNTK::DeviceDescriptor const&) + 0x211
[0x7f9ceecf0c44]    CNTK::Trainer::  TrainMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&) + 0x44
[0x7f9ceecf0d40]    CNTK::Trainer::  TrainMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  CNTK::DeviceDescriptor const&) + 0xa0
[0x7f9ceed4245d]    CNTK::TrainingSession::  Train  (CNTK::DeviceDescriptor const&) + 0x1fd
[0x7f9cef588eb3]                                                       + 0x105eb3
[0x7f9cf8248a41]    PyEval_EvalFrameEx                                 + 0x7cb1
[0x7f9cf8247ee6]    PyEval_EvalFrameEx                                 + 0x7156
[0x7f9cf8249371]    PyEval_EvalCodeEx                                  + 0x8b1
[0x7f9cf81a7161]                                                       + 0x91161
[0x7f9cf81771f9]    PyObject_Call                                      + 0x59
[0x7f9cf8246766]    PyEval_EvalFrameEx                                 + 0x59d6
[0x7f9cf8249371]    PyEval_EvalCodeEx                                  + 0x8b1
[0x7f9cf8247d2a]    PyEval_EvalFrameEx                                 + 0x6f9a
[0x7f9cf8249371]    PyEval_EvalCodeEx                                  + 0x8b1
[0x7f9cf8247d2a]    PyEval_EvalFrameEx                                 + 0x6f9a
[0x7f9cf8249371]    PyEval_EvalCodeEx                                  + 0x8b1
[0x7f9cf8247d2a]    PyEval_EvalFrameEx                                 + 0x6f9a
[0x7f9cf8249371]    PyEval_EvalCodeEx                                  + 0x8b1
[0x7f9cf824943b]    PyEval_EvalCode                                    + 0x3b
[0x7f9cf8269db0]    PyRun_FileExFlags                                  + 0x130
[0x7f9cf826ce44]    PyRun_SimpleFileExFlags                            + 0x104
[0x7f9cf8287276]    Py_Main                                            + 0xba6
[0x400acd]          main                                               + 0x15d
[0x7f9cf7447f45]    __libc_start_main                                  + 0xf5
[0x4008a9]          
```

**Comment by KeDengMS** [comment]
Yes this is a missing feature. However, implementing it may not be the answer, because the intention of using sparse matrix for gradient in embedding with big vocab is to save computation and memory. With L2 reg, the gradient would become dense, thus hurting perf and memory footprint.
Maybe a better way to deal with this, is to create a dedicate learner for embedding that do not use L2Reg?
