### ISSUE TITLE
C# update Value data instead of creating new when shape remains the same

### ISSUE THREAD

**Issue by sunnsurf** [Microsoft/CNTK#2856]
According to VS CPU Profiler Value.CreateBatch is accounts for most of the CPU time and additionally GPU memory usage appears to be saw-toothing. Where the shape remains constant e.g. mini-batch to mini-batch, is there, or can there be a way to update the data from a float[] instead of creating a new Value object each time?

Currently, the following is executed for each minibatch:
`public void PrepareTrainData(int batchSize, string[] labels, Dictionary<string, int> lengths, float[] data)
{
    if (null == TrainData)
    {
        TrainData = new Dictionary<string, Value>(labels.Length);
        foreach (string label in labels)
            TrainData[label] = null;
    }
    //---
    int beginIdx = 0;
    foreach(string label in labels)
    {
        int varSize = lengths[label];
        TrainData[label] = Value.CreateBatch(new int[] { varSize }, data, beginIdx, varSize * batchSize, Device, /* readonly = */ true);
        beginIdx += varSize * batchSize;
    }
}`

If the following was possible instead then GPU memory saw-toothing would probably diminish significantly and with it possibly a tick up in performance. Or not, happy to learn a better way :-)

`public void PrepareTrainData(int batchSize, string[] labels, Dictionary<string, int> lengths, float[] data)
{
    if (null == TrainData)
    {
        TrainData = new Dictionary<string, Value>(labels.Length);
        foreach (string label in labels)
            TrainData[label] = null;
    }
    //---
    int beginIdx = 0;
    foreach(string label in labels)
    {
        int varSize = lengths[label];
        if (batchSize == prevBatchSize)
        	TrainData[label].UpdateBatch(data, beginIdx, varSize * batchSize);
        else
        	TrainData[label] = Value.CreateBatch(new int[] { varSize }, data, beginIdx, varSize * batchSize, Device, /* readonly = */ true);
        beginIdx += varSize * batchSize;
    }
}`

**Comment by sunnsurf** [comment]
Tested the idea using a temporary NDArrayView (as per below) and it did lift the overall performance, although the memory saw-toothing still exists, now in system memory, and CPU is running at 100%. In terms of the performance uplift, the epoch duration reduced by about 35%.

```C#
public void PrepareTrainData(int batchSize, string[] labels, Dictionary<string, int> lengths, float[] data)
{
    if (null == TrainData)
    {
        TrainData = new Dictionary<string, Value>(labels.Length);
        foreach (string label in labels)
            TrainData[label] = null;
    }
    //---
    int beginIdx = 0;
    foreach(string label in labels)
    {
        int varSize = lengths[label];
        if (prevTrainBatchSize == batchSize)
        {
            ArraySegment<float> segment = new ArraySegment<float>(data, beginIdx, varSize * batchSize);
            NDArrayView d = new NDArrayView(new int[] { varSize, 1, batchSize }, segment.ToArray(), DeviceDescriptor.CPUDevice, /* readonly = */ true);
            TrainData[label].Data.CopyFrom(d);
            d.Dispose();
        }
        else
            TrainData[label] = Value.CreateBatch(new int[] { varSize }, data, beginIdx, varSize * batchSize, Device, /* readonly = */ false);
        beginIdx += varSize * batchSize;
    }
}
```

**Comment by sunnsurf** [comment]
Unfortunately the `NDArrayView.CopyFrom` method appears to be a little unstable. After varying numbers of epochs, the following is encountered:
```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at CNTK.CNTKLibPINVOKE.NDArrayView_CopyFrom(HandleRef jarg1, HandleRef jarg2)
   at CNTK.NDArrayView.CopyFrom(NDArrayView source)
```
