### ISSUE TITLE
[With NVIDIA K40c] ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by moderato** [microsoft/CNTK#2872]
Hello! I got this error when I try to import cntk:

```
Traceback (most recent call last):
  File "/home/m092926/miniconda3/envs/neon/lib/python3.5/site-packages/cntk/cntk_py.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/m092926/miniconda3/envs/neon/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ImportError: No module named 'cntk._cntk_py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Cntk.py", line 33, in <module>
    import cntk as C
  File "/home/m092926/miniconda3/envs/neon/lib/python3.5/site-packages/cntk/__init__.py", line 10, in <module>
    from . import cntk_py
  File "/home/m092926/miniconda3/envs/neon/lib/python3.5/site-packages/cntk/cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "/home/m092926/miniconda3/envs/neon/lib/python3.5/site-packages/cntk/cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "/home/m092926/miniconda3/envs/neon/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory
```

The configurations of my environment are:
Ubuntu 16.04
NVIDIA K40c (totally 4 in the server, using one in this case)
CUDA 8.0
CNTK 2.3.1 GPU version

I have tried tricks like 
```
export LD_LIBRARY_PATH (cuda something)
```
and
```
sudo ldconfig
```
but it doesn't work. Setting CUDA version to 7.0 works though, but I would stick to 8.0 if the bug can be fixed. I wonder if this is because CNTK searches for CUDA 7.0 libraries for older GPUs like K40? Thanks!

**Comment by KeDengMS** [comment]
Can you try this?
```
ldd /home/m092926/miniconda3/envs/neon/lib/python3.5/site-packages/cntk/libs/libCntk.Math-2.3.1.so
```
It should link with libcudart.so.8.0. ldd should show you where the so file is.

**Comment by moderato** [comment]
The output looks like this:

```
	linux-vdso.so.1 =>  (0x00007fff662fc000)
	libcublas.so.8.0 => /usr/local/cuda-8.0/lib64/libcublas.so.8.0 (0x00007f35ff60e000)
	libcudart.so.8.0 => /usr/local/cuda-8.0/lib64/libcudart.so.8.0 (0x00007f35ff3a8000)
	libcurand.so.8.0 => /usr/local/cuda-8.0/lib64/libcurand.so.8.0 (0x00007f35fb432000)
	libcusparse.so.8.0 => /usr/local/cuda-8.0/lib64/libcusparse.so.8.0 (0x00007f35f8917000)
	libcudnn.so.6 => /usr/local/cuda-8.0/lib64/libcudnn.so.6 (0x00007f35ef3b5000)
	libnccl.so.2 => /home/m092926/miniconda3/envs/neon/lib/python3.5/site-packages/cntk/libs/libnccl.so.2 (0x00007f35e2e49000)
	libiomp5.so => /home/m092926/miniconda3/envs/neon/lib/python3.5/site-packages/cntk/libs/libiomp5.so (0x00007f35e2aa5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f35e2888000)
	libmklml_intel.so => /home/m092926/miniconda3/envs/neon/lib/python3.5/site-packages/cntk/libs/libmklml_intel.so (0x00007f35d9a45000)
	libCntk.PerformanceProfiler-2.3.1.so => /home/m092926/miniconda3/envs/neon/lib/python3.5/site-packages/cntk/libs/libCntk.PerformanceProfiler-2.3.1.so (0x00007f35d981f000)
	libmpi_cxx.so.1 => /usr/lib/libmpi_cxx.so.1 (0x00007f35d9604000)
	libmpi.so.12 => /usr/lib/libmpi.so.12 (0x00007f35d932e000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f35d8fac000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f35d8ca3000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f35d8a8c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f35d86c2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f360603e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f35d84ba000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f35d82b6000)
	libibverbs.so.1 => /usr/lib/libibverbs.so.1 (0x00007f35d809d000)
	libopen-rte.so.12 => /usr/lib/libopen-rte.so.12 (0x00007f35d7e23000)
	libopen-pal.so.13 => /usr/lib/libopen-pal.so.13 (0x00007f35d7b86000)
	libnl-route-3.so.200 => /usr/lib/x86_64-linux-gnu/libnl-route-3.so.200 (0x00007f35d7923000)
	libnl-3.so.200 => /lib/x86_64-linux-gnu/libnl-3.so.200 (0x00007f35d7704000)
	libhwloc.so.5 => /usr/lib/x86_64-linux-gnu/libhwloc.so.5 (0x00007f35d74ca000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f35d72c7000)
	libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f35d70bc000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f35d6eb2000)
```
Looks like libcudart.so.8.0 is linked correctly but when I  run the program it still gives me the same error...

**Comment by KeDengMS** [comment]
My guess is that your python environment loads libCntk.Math.so from some other places. Please use gdb -p <pid> to attach to a running python process, then "i sh" to check the where modules are loaded from.
