### ISSUE TITLE
Loading squeezenet ONNX model failed

### ISSUE THREAD

**Issue by star-rat** [Microsoft/CNTK#2907]
I am trying to load squeezenet model whith cntk 2.3.1. Got the model from the repository for storing ONNX models [https://github.com/onnx/models](https://github.com/onnx/models).

`import cntk as C`

`z = C.Function.load("model.pb", device=C.device.cpu(), format=C.ModelFormat.ONNX)`

Output: 
` Traceback (most recent call last):`
`  File "my_sqz.py", line 2, in <module>`
`    z = C.Function.load("model.pb", device=C.device.cpu(), format=C.ModelFormat.ONNX)`
`  File "C:\Anaconda3\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper`
`    result = f(*args, **kwds)`
`  File "C:\Anaconda3\lib\site-packages\cntk\ops\functions.py", line 1580, in load`
`    return cntk_py.Function.load(str(model), device, format.value)`
`ValueError: Convolution operation requires that kernel dim 128 <= input dim 64.`

But the same code works well with VGG16 model.  What's wrong with squeezenet ONNX model ?

**Comment by star-rat** [comment]
It works for me on cntk 2.4.0.
