### ISSUE TITLE
Data loading issue

### ISSUE THREAD

**Issue by yexing99** [Microsoft/CNTK#2957]
I put train.zip and train_map.txt into folder /home/adminye/ImageNet. I set data_path to the same directory. But when I run the script, it keeps complaining the train.zip is not available. Please see the error msg below: 

lxyemultigpu:72598] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Traceback (most recent call last):
  File "AlexNet_ImageNet_Distributed.py", line 257, in <module>
    gen_heartbeat=True)
  File "AlexNet_ImageNet_Distributed.py", line 200, in alexnet_train_and_eval
    train_source = create_image_mb_source(train_data, True, total_number_of_samples=max_epochs * epoch_size)
  File "AlexNet_ImageNet_Distributed.py", line 63, in create_image_mb_source
    multithreaded_deserializer=True)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/cntk/io/__init__.py", line 226, in __init__
    source = cntk_py.create_composite_minibatch_source(config)
RuntimeError: Failed to open train.zip, zip library error: No such file

**Comment by KeDengMS** [comment]
Probably an issue in train.zip in relative path in train_map.txt. Please either modify the map file using absolute path, or change pwd in your script to where train_map.txt is (not recommended)

**Comment by yexing99** [comment]
Yes, Thank you.
