### ISSUE TITLE
Does C.layer.Delay() support the word sequence of sparse form 

### ISSUE THREAD

**Issue by ZaberKo** [Microsoft/CNTK#2960]
I'm writing a seq2seq model, following CNTK_204 tutorial.
When i write down the following code ,it rises "RuntimeError: TensorOp: Tensor operations are currently not supported for sparse matrices."

```
def model_train_factory(self,s2smodel):
        @C.Function
        def model_train(question, passage, answer):
            past_answer = Delay(initial_state=self.start_word)(answer)
            return s2smodel(question, passage, past_answer)

        return model_train
```
the detailed error infos:
```
Traceback (most recent call last):
  File "E:/Python/team_xyz/script/train.py", line 109, in <module>
    train(data_path, model_path, log_path, config_file)
  File "E:/Python/team_xyz/script/train.py", line 95, in train
    session.train()
  File "C:\Program Files\Python36\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Program Files\Python36\lib\site-packages\cntk\train\training_session.py", line 333, in train
    super(TrainingSession, self).train(device)
  File "C:\Program Files\Python36\lib\site-packages\cntk\cntk_py.py", line 3494, in train
    return _cntk_py.TrainingSession_train(self, computeDevice)
RuntimeError: TensorOp: Tensor operations are currently not supported for sparse matrices.

[CALL STACK]
    > Microsoft::MSR::CNTK::Matrix<double>::BatchNormalizationForward<double>  
    - Microsoft::MSR::CNTK::Matrix<float>::  TensorOp
    - Microsoft::MSR::CNTK::TensorView<float>::  DoUnaryOpOf
    - Microsoft::MSR::CNTK::TensorView<float>::  AssignCopyOf
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this (x3)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfUnitsSeen
    - CNTK::Trainer::  TrainMinibatch (x2)
    - CNTK::TrainingSession::  Train
```

I'm sure i just follow the tutorial, and the reason comes from there (because when i change it to `s2smodel(question, passage, answer)`  everything goes well)

**Comment by ZaberKo** [comment]
PS: here is my reader
```
def argument_by_name(func, name):
    found = [arg for arg in func.arguments if arg.name == name]
    if len(found) == 0:
        raise ValueError('no matching names in arguments')
    elif len(found) > 1:
        raise ValueError('multiple matching names in arguments')
    else:
        return found[0]


def create_mb_and_map(func, data_file, vocab_dim, randomize=True, repeat=False):
    mb_source = C.io.MinibatchSource(
        C.io.CTFDeserializer(
            data_file,
            C.io.StreamDefs(
                select_context_words=C.io.StreamDef('mw', shape=vocab_dim, is_sparse=True),
                query_words=C.io.StreamDef('qw', shape=vocab_dim, is_sparse=True),
                answer_words=C.io.StreamDef('aw', shape=vocab_dim, is_sparse=True)
            )),
        randomize=randomize,
        max_sweeps=C.io.INFINITELY_REPEAT if repeat else 1)
    input_map = {
        argument_by_name(func, 'passage'): mb_source.streams.select_context_words,
        argument_by_name(func, 'question'): mb_source.streams.query_words,
        argument_by_name(func, 'answer'): mb_source.streams.answer_words
    }
    return mb_source, input_map
```

**Comment by KeDengMS** [comment]
Delay is supposed to be use inside RNN loop. In your case, please try sequence.slice(answer, 1, 0)

**Comment by ZaberKo** [comment]
@KeDengMS The original sequence doesn't contain the BOS, and what i need is the seq that can be used as the input for decoder. 
Anyway, i solved it by set the` C.sequence.input_variable.is_sparse` to False, then it works well.
