### ISSUE TITLE
RuntimeError: OptimizedRNNStackNode configured for sequence mode, but minibatch only has one time step.

### ISSUE THREAD

**Issue by CSSE-NULL** [Microsoft/CNTK#3019]
When I was trying to training a seq2seq model, an error occured:
```
Traceback (most recent call last):
  File "my_train.py", line 61, in <module>
    train(s2s_obj, 300, 2500)
  File "my_train_ss.py", line 40, in train
    criterion.arguments[1]: mb_train[train_reader.streams.id]})
  File "/usr/local/python3/lib/python3.5/site-packages/cntk/train/trainer.py", line 181, in train_minibatch
    arguments, device)
  File "/usr/local/python3/lib/python3.5/site-packages/cntk/cntk_py.py", line 2853, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
RuntimeError: OptimizedRNNStackNode configured for sequence mode, but minibatch only has one time step.
```
What does `RuntimeError: OptimizedRNNStackNode configured for sequence mode, but minibatch only has one time step.` mean here? I've already run 25 epoches before the error occurred. What's gone wrong?

**Comment by KeDengMS** [comment]
Thanks for reporting, the bug is fixed.
