### ISSUE TITLE
Function.load on Faster RCNN eval model yields unhelpful "SWIG director method" error

### ISSUE THREAD

**Issue by riverar** [Microsoft/CNTK#3035]
Using CNTK v2.4 release on Windows.

```
>>> import cntk as C
>>> z = C.Function.load("Output/faster_rcnn_eval_AlexNet_e2e.model", device=C.device.cpu())

Traceback (most recent call last):
  File "C:\Users\Rafael\py3\lib\site-packages\cntk\internal\__init__.py", line 54, in __call__
    exec("from {} import {}".format(module, cls))
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'utils'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Rafael\py3\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\Rafael\py3\lib\site-packages\cntk\ops\functions.py", line 1580, in load
    return cntk_py.Function.load(str(model), device, format.value)
RuntimeError: SWIG director method error.
```

**Comment by springkim** [comment]
Copy [https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/utils](https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/utils) folder into your main python script.

**Comment by riverar** [comment]
Thanks, good enough for now.
