### ISSUE TITLE
CUDA failure 2: out of memory when training model with keras

### ISSUE THREAD

**Issue by bmigette** [Microsoft/CNTK#3040]
I am trying to train a model using Keras and cntk2.4. Everytime I call the fit function, I get a cuda out of memory error.

My GPU has 11GB of RAM, and when it crashes, not even 1.5Gb are used. 

My network is a simple single layer LSTM with 5000 neurons:

```
def LSTM_5000(shape1, shape2,shapeout):
    model = Sequential()
    model.add(LSTM(5000,dropout=0.2,recurrent_dropout=0.2, 
                  input_shape=(shape1, shape2)
             )) #recurrent_dropout=0.2, 
    model.add(Dense(shapeout))
    model.add(Activation('sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics =["accuracy"])
    return model 
```

Full error:
```

Using CNTK backend
Selected GPU[0] GeForce GTX 1080 Ti as the process wide default device.
...
C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\cntk\core.py:361: UserWarning: your data is of type "float64", but your input variable (uid "Input664") expects "<class 'numpy.float32'>". Please convert your data beforehand to speed up training.
  (sample.dtype, var.uid, str(var.dtype)))
C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\cntk\core.py:361: UserWarning: your data is of type "float64", but your input variable (uid "Input4") expects "<class 'numpy.float32'>". Please convert your data beforehand to speed up training.
    ...

CUDA failure 2: out of memory ; GPU=0 ; hostname=XXX-PC ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * AsMultipleOf(numElements, 2))
    Traceback (most recent call last):
      File ".\run_tests.py", line 181, in <module>
        runtest(settings,period+'_p'+str(j)+'_'+models_name[i])
      File ".\run_tests.py", line 138, in runtest
        verbose=1, shuffle=False)
      File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\models.py", line 963, in fit
        validation_steps=validation_steps)
      File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1712, in fit
        validation_steps=validation_steps)
      File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1235, in _fit_loop
        outs = f(ins_batch)
      File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\cntk_backend.py", line 1823, in __call__
        input_dict, self.trainer_output)
      File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\cntk\train\trainer.py", line 171, in train_minibatch
        output_map, device)
      File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\cntk\cntk_py.py", line 2978, in train_minibatch
        return _cntk_py.Trainer_train_minibatch(self, *args)
    RuntimeError: CUDA failure 2: out of memory ; GPU=0 ; hostname=XXX-PC ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * AsMultipleOf(numElements, 2))

    [CALL STACK]
        > Microsoft::MSR::CNTK::CudaTimer::  Stop
        - Microsoft::MSR::CNTK::CudaTimer::  Stop (x2)
        - Microsoft::MSR::CNTK::GPUMatrix<float>::  Resize
        - Microsoft::MSR::CNTK::Matrix<float>::  Resize
        - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>
        - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this (x3)
        - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
        - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this
        - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
        - CNTK::Function::  Forward
        - CNTK::  UniversalLearner
        - CNTK::TrainingParameterSchedule<unsigned __int64>::  Transform
        - CNTK::Trainer::  TotalNumberOfUnitsSeen
```

**Comment by KeDengMS** [comment]
CUDA reports OOM when trying to allocate a big buffer that exceeds existing memory. Have you tried the same model in other backends? How much memory does it take if no OOM in those backends?

**Comment by bmigette** [comment]
I've tried with tensorflow, it used approx 9Gb out of 11. Maybe that's just too much then ?

**Comment by KeDengMS** [comment]
There are some overheads in CNTK keras backend. Please try save the model in CNTK format and eval using CNTK function directly.

**Comment by bmigette** [comment]
I'm not sure how to do that... In any case, I am fine using tensorflow for fitting, and either CNTK or tensorflow for predicting later...
Note: I tried to save trained model from Keras using C.combine(model.model.outputs).save(name+".cntkmodel")
But it gave me an error that it could not convert list to CNTK::Variable if I recall correctly.

**Comment by KeDengMS** [comment]
Can you save it to keras first and then load, like [this](https://stackoverflow.com/questions/44943064/how-to-save-a-keras-model-in-the-cntk-format)?

**Comment by KeDengMS** [comment]
Yes, load the keras model in CNTK backend please.

**Comment by ahmadalli** [comment]
any update on this? I'm getting the same error with lstm model while tensorflow backend works fine
