### ISSUE TITLE
KeyError: 'pip._vendor.urllib3.contrib'

### ISSUE THREAD

**Issue by malkiebr** [Microsoft/CNTK#3047]
This is what happens when I "from cntk import load_model":

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ferna\AppData\local\AmlWorkbench\Python\lib\site-packages\cntk\__init__.py", line 34, in <module>
    from .sample_installer import install_samples
  File "C:\Users\ferna\AppData\local\AmlWorkbench\Python\lib\site-packages\cntk\sample_installer.py", line 17, in <module>
    import pip
  File "C:\Users\ferna\AppData\local\AmlWorkbench\Python\lib\site-packages\pip\__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Users\ferna\AppData\local\AmlWorkbench\Python\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "C:\Users\ferna\AppData\local\AmlWorkbench\Python\lib\site-packages\pip\download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "C:\Users\ferna\AppData\local\AmlWorkbench\Python\lib\site-packages\pip\_vendor\requests\__init__.py", line 98, in <module>
    from . import packages
  File "C:\Users\ferna\AppData\local\AmlWorkbench\Python\lib\site-packages\pip\_vendor\requests\packages.py", line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'`

**Comment by ElliottTradeLaboratory** [comment]
The easiest and quickest solution(but temporary) is to comment out as follows:
·File
  C:\Users\ferna\AppData\local\AmlWorkbench\Python\lib\site-packages\cntk\__init__.py
·Line 34
   from .sample_installer import install_samples

**Comment by malkiebr** [comment]
There was an AML Workbench update today.
Now the error changed to: *KeyError:
'pip._vendor.urllib3.packages.backports' *

Tracelog:

File "libraries\helpers_cntk.py", line 3, in <module>
    from cntk import load_model, Trainer, UnitType,
use_default_device, placeholder, constant, cross_entropy_with_softmax,
classification_error
  File "C:\Users\fernlee\AppData\local\AmlWorkbench\Python\lib\site-packages\cntk\__init__.py",
line 34, in <module>
    from .sample_installer import install_samples
  File "C:\Users\fernlee\AppData\local\AmlWorkbench\Python\lib\site-packages\cntk\sample_installer.py",
line 17, in <module>
    import pip
  File "C:\Users\fernlee\AppData\local\AmlWorkbench\Python\lib\site-packages\pip\__init__.py",
line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Users\fernlee\AppData\local\AmlWorkbench\Python\lib\site-packages\pip\vcs\mercurial.py",
line 9, in <module>
    from pip.download import path_to_url
  File "C:\Users\fernlee\AppData\local\AmlWorkbench\Python\lib\site-packages\pip\download.py",
line 40, in <module>
    from pip._vendor import requests, six
  File "C:\Users\fernlee\AppData\local\AmlWorkbench\Python\lib\site-packages\pip\_vendor\requests\__init__.py",
line 98, in <module>
    from . import packages
  File "C:\Users\fernlee\AppData\local\AmlWorkbench\Python\lib\site-packages\pip\_vendor\requests\packages.py",
line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] =
sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.packages.backports'

**Comment by KeDengMS** [comment]
Seems like a [pip bug](https://github.com/pypa/pip/issues/5079). Is it possible to go back to an older version of pip?
