### ISSUE TITLE
RuntimeError: CUDA failure 77: an illegal memory access was encountered 

### ISSUE THREAD

**Issue by vinay453** [Microsoft/CNTK#3073]
I have NC6 Linux VM with Python 3.5.2 and CNTK 2.0 GPU wheel.  I am getting "RuntimeError: CUDA failure 77: an illegal memory access was encountered " error.  Not really sure about the cause of problem, please help if this information is not enough, I will provide further info. 

```

$ python --version
Python 3.5.2 :: Anaconda custom (64-bit

```

```

$ cntk
-------------------------------------------------------------------
Build info: 

        Built time: Sep 15 2017 07:30:54
        Last modified date: Fri Sep 15 04:28:48 2017
        Build type: release
        Build target: GPU
        With 1bit-SGD: no
        With ASGD: yes
        Math lib: mkl
        CUDA version: 9.0.0
        CUDNN version: 6.0.21
        Build Branch: HEAD
        Build SHA1: 23878e5d1f73180d6564b6f907b14fe5f53513bb
        MPI distribution: Open MPI
        MPI version: 1.10.7
-------------------------------------------------------------------
No command-line argument given.
-------------------------------------------------------------------
Usage: cntk configFile=yourConfigFile
For detailed information please consult the CNTK book
"An Introduction to Computational Networks and the Computational Network Toolkit”

```

```
* $ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

```

```
Loading DNN..
Selected GPU[0] Tesla K80 as the process wide default device.
Time loading DNN [ms]: 689.84
Loading svm weights..
Time loading svm [ms]: 40.714
roi_minDim 105.00000000000001
roi_maxDim 1500.0
roi_minNrPixels 22050.000000000004
roi_maxNrPixels 742500.0
ss_kvals (50, 500, 6)
ss_minSize 20
ss_max_merging_iterations 20
ss_nmsThreshold 0.85
Calling selective search..
   Number of rois detected using selective search: 36948
   Number of rois on grid added: 1772
   Number of ROIs before filtering  = 38720
   Number of ROIs after filtering  = 5849
Time roi computation [ms]: 44098.368
Time cnkt input generation [ms]: 76.001
Running model.
Traceback (most recent call last):
  File "/home/k***ssh/ObjectDetectionAzure/OCR_Object.py", line 272, in <module>
    dnnOutputs = model.eval(arguments)[0]
  File "/anaconda/envs/py35/lib/python3.5/site-packages/cntk/ops/functions.py", line 626, in eval
    _, output_map = self.forward(arguments, outputs, device=device, as_numpy=as_numpy)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/cntk/ops/functions.py", line 760, in forward
    keep_for_backward)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 1568, in _forward
    return _cntk_py.Function__forward(self, *args)
RuntimeError: CUDA failure 77: an illegal memory access was encountered ; GPU=0 ; hostname=***** ; expr=cudaFree((void*) bufferPtr)

[CALL STACK]
[0x7f7ee5ebe7ac]                                                       + 0x4f17ac
[0x7f7ee33abae3]                                                       + 0x82dae3
[0x7f7ee33d7d0b]    void Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  Free  <float>(int,  float*,  bool) + 0x4b
[0x7f7ee33dc313]    Microsoft::MSR::CNTK::GPUMatrix<float>::  Resize  (unsigned long,  unsigned long,  bool) + 0x73
[0x7f7ee333a715]    Microsoft::MSR::CNTK::Matrix<float>::  Resize  (unsigned long,  unsigned long,  unsigned long,  bool) + 0xb5
[0x7f7ee614da29]    Microsoft::MSR::CNTK::ComputationNode<float>::  BeginForwardProp  () + 0xe9
[0x7f7ee5f757a9]    Microsoft::MSR::CNTK::BinaryElementWiseNode<float>::  BeginForwardProp  () + 0x9
[0x7f7ee61d1621]    Microsoft::MSR::CNTK::ComputationNetwork::PARTraversalFlowControlNode::  ForwardProp  (std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&,  Microsoft::MSR::CNTK::FrameRange const&) + 0x41
[0x7f7ee606aef5]    std::_Function_handler<void (std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&),void Microsoft::MSR::CNTK::ComputationNetwork::ForwardProp<std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>>>(std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>> const&)::{lambda(std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&)#1}>::  _M_invoke  (std::_Any_data const&,  std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&) + 0x35
[0x7f7ee609276d]    void Microsoft::MSR::CNTK::ComputationNetwork::  TravserseInSortedGlobalEvalOrder  <std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>>>(std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>> const&,  std::function<void (std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&)> const&) + 0x3ed
[0x7f7ee60610de]    CNTK::CompositeFunction::  Forward  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&) + 0x7ae
[0x7f7ee60234b1]    CNTK::Function::  Forward  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&) + 0x81
[0x7f7ee68acc64]                                                       + 0x57c64
[0x7f7ee6aa983b]                                                       + 0x25483b
[0x7f7f1e78e5e9]    PyCFunction_Call                                   + 0xf9
[0x7f7f1e8137c0]    PyEval_EvalFrameEx                                 + 0x6ba0
[0x7f7f1e816b49]                                                       + 0x144b49
[0x7f7f1e815df5]    PyEval_EvalFrameEx                                 + 0x91d5
[0x7f7f1e816b49]                                                       + 0x144b49
[0x7f7f1e816cd8]    PyEval_EvalCodeEx                                  + 0x48
[0x7f7f1e76c661]                                                       + 0x9a661
[0x7f7f1e739236]    PyObject_Call                                      + 0x56
[0x7f7f1e813234]    PyEval_EvalFrameEx                                 + 0x6614
[0x7f7f1e816b49]                                                       + 0x144b49
[0x7f7f1e815df5]    PyEval_EvalFrameEx                                 + 0x91d5
[0x7f7f1e816b49]                                                       + 0x144b49
[0x7f7f1e815df5]    PyEval_EvalFrameEx                                 + 0x91d5
[0x7f7f1e816b49]                                                       + 0x144b49
[0x7f7f1e816cd8]    PyEval_EvalCodeEx                                  + 0x48
[0x7f7f1e816d1b]    PyEval_EvalCode                                    + 0x3b
[0x7f7f1e83c020]    PyRun_FileExFlags                                  + 0x130
[0x7f7f1e83d623]    PyRun_SimpleFileExFlags                            + 0x173
[0x7f7f1e8588c7]    Py_Main                                            + 0xca7
[0x400add]          main                                               + 0x15d
[0x7f7f1d7f3830]    __libc_start_main                                  + 0xf0
[0x4008b9]                                 
```

**Comment by KeDengMS** [comment]
Is it possible to try a more recent version? It might be a fixed bug.

**Comment by vinay453** [comment]
I upgraded by installing higher versions like CNTK 2.1, 2.2, 2.3,2.4, 2.5, but I am unable to use these versions. I get following error messages. 

```
$ python -c "import cntk; print(cntk.__version__)"
Traceback (most recent call last):
  File "/home/kssh/.conda/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/kssh/.conda/envs/cntk-py35/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ImportError: No module named 'cntk._cntk_py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kssh/.conda/envs/cntk-py35/lib/python3.5/site-packages/cntk/__init__.py", line 17, in <module>
    from . import cntk_py
  File "/home/kssh/.conda/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "/home/kssh/.conda/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "/home/kssh/.conda/envs/cntk-py35/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory
```
