### ISSUE TITLE
"Feature Not Implemented" error when using Tensorboard

### ISSUE THREAD

**Issue by sjsy** [Microsoft/CNTK#3086]
Hi,
Without using tensorboard, my program works normally. 
`trainer = C.Trainer(z, (ce, pe), [sgd(z.parameters, lr=lr_per_minibatch)], [progress_printer])`

But when I switch to tensorboard, the errors appear.

`tensorboard_writer = TensorBoardProgressWriter(freq=10, log_dir='log', model=my_model)`
`...`
`trainer = C.Trainer(z, (ce, pe), [sgd(z.parameters, lr=lr_per_minibatch)], tensorboard_writer)`

error message:

Selected GPU[0] GeForce GTX 1060 as the process wide default device.
-------------------------------------------------------------------
Build info: 

		Built time: Mar 16 2018 21:05:03
		Last modified date: Fri Mar 16 21:01:57 2018
		Build type: release
		Build target: GPU
		With ASGD: yes
		Math lib: mkl
		CUDA version: 9.0.0
		CUDNN version: 7.0.4
		Build Branch: HEAD
		Build SHA1: f038cac92dfe3a2881b50bb0fad17d403f8db656
		MPI distribution: Open MPI
		MPI version: 1.10.7
-------------------------------------------------------------------
/opt/anaconda3/envs/cntk-py36/lib/python3.6/site-packages/cntk/core.py:361: UserWarning: your data is of type "float64", but your input variable (uid "Input4") expects "<class 'numpy.float32'>". Please convert your data beforehand to speed up training.
  (sample.dtype, var.uid, str(var.dtype)))
Inside File: Source/CNTKv2LibraryDll/tensorboard/TensorBoardUtils.cpp  Line: 52  Function: GetDataType  -> Feature Not Implemented.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/cntk-py36/lib/python3.6/site-packages/cntk/logging/progress_print.py", line 506, in on_write_training_update
    self.write_value('minibatch/avg_loss', _avg(aggregate_loss, samples), self.total_training_updates())
  File "/opt/anaconda3/envs/cntk-py36/lib/python3.6/site-packages/cntk/logging/progress_print.py", line 472, in write_value
    self.writer.write_value(str(name), float(value), int(step))
  File "/opt/anaconda3/envs/cntk-py36/lib/python3.6/site-packages/cntk/cntk_py.py", line 402, in write_value
    return _cntk_py.TensorBoardFileWriter_write_value(self, name, value, step)
RuntimeError: Inside File: Source/CNTKv2LibraryDll/tensorboard/TensorBoardUtils.cpp  Line: 52  Function: GetDataType  -> Feature Not Implemented.

[CALL STACK]
[0x7feec9885ef9]                                                       + 0x8aeef9
[0x7feec9a859f6]                                                       + 0xaae9f6
[0x7feec9a86c14]                                                       + 0xaafc14
[0x7feec9a87207]    CNTK::Internal::  CreateTensorBoardGraph  (std::shared_ptr<CNTK::Function> const&,  tensorflow::GraphDef&) + 0x287
[0x7feec9a81a72]    CNTK::Internal::TensorBoardFileWriter::  WriteModel  () + 0x72
[0x7feec9a820fd]    CNTK::Internal::TensorBoardFileWriter::  Init  ()  + 0x44d
[0x7feec9a82621]    CNTK::Internal::TensorBoardFileWriter::  WriteRecord  (std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>> const&) + 0x381
[0x7feec9a8282c]    CNTK::Internal::TensorBoardFileWriter::  WriteValue  (std::__cxx11::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> const&,  float,  unsigned long) + 0x1ac
[0x7feeca622d6a]                                                       + 0x1c2d6a
[0x7feee3f67a29]    _PyCFunction_FastCallDict                          + 0x229
[0x7feee3fecf4c]                                                       + 0x147f4c
[0x7feee3fefbbd]    _PyEval_EvalFrameDefault                           + 0x26fd
[0x7feee3fea8d4]                                                       + 0x1458d4
[0x7feee3fed048]                                                       + 0x148048
[0x7feee3fefbbd]    _PyEval_EvalFrameDefault                           + 0x26fd
[0x7feee3fea8d4]                                                       + 0x1458d4
[0x7feee3fed048]                                                       + 0x148048
[0x7feee3fefbbd]    _PyEval_EvalFrameDefault                           + 0x26fd
[0x7feee3fea8d4]                                                       + 0x1458d4
[0x7feee3feb8d5]    _PyFunction_FastCallDict                           + 0x285
[0x7feee3f109f6]    _PyObject_FastCallDict                             + 0x166
[0x7feee3f10c4c]    _PyObject_Call_Prepend                             + 0xcc
[0x7feee3f10ce6]    PyObject_Call                                      + 0x56
[0x7feee3f10dcd]                                                       + 0x6bdcd
[0x7feee3f10e7d]                                                       + 0x6be7d
[0x7feee3f143f6]    PyObject_CallMethod                                + 0xe6
[0x7feeca4f3a47]    SwigDirector_ProgressWriter::  OnWriteTrainingUpdate  (std::pair<unsigned long,unsigned long> const&,  std::pair<unsigned long,unsigned long> const&,  std::pair<double,double> const&,  std::pair<double,double> const&) + 0x267
[0x7feec9a7658a]    CNTK::ProgressWriter::  UpdateTraining  (unsigned long,  std::shared_ptr<CNTK::Value> const&,  std::shared_ptr<CNTK::Value> const&) + 0x18a
[0x7feec99f9fec]    CNTK::Trainer::  UpdateTrainingProgress  (unsigned long,  std::shared_ptr<CNTK::Value> const&,  std::shared_ptr<CNTK::Value> const&,  CNTK::DeviceDescriptor const&) + 0xdc
[0x7feec9a00a7c]    CNTK::Trainer::  TrainMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  bool,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&) + 0x7c
[0x7feec9a00b22]    CNTK::Trainer::  TrainMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  bool,  CNTK::DeviceDescriptor const&) + 0x52
[0x7feeca677ee5]                                                       + 0x217ee5
[0x7feee3f67ca9]    PyCFunction_Call                                   + 0x119
[0x7feee3ff3b3c]    _PyEval_EvalFrameDefault                           + 0x667c
[0x7feee3feb4c0]                                                       + 0x1464c0
[0x7feee3feceea]                                                       + 0x147eea
[0x7feee3fefbbd]    _PyEval_EvalFrameDefault                           + 0x26fd
[0x7feee3feb4c0]                                                       + 0x1464c0
[0x7feee3feceea]                                                       + 0x147eea
[0x7feee3fefbbd]    _PyEval_EvalFrameDefault                           + 0x26fd
[0x7feee3feb4c0]                                                       + 0x1464c0
[0x7feee3feb943]    PyEval_EvalCodeEx                                  + 0x63
[0x7feee3feb98b]    PyEval_EvalCode                                    + 0x3b
[0x7feee401e100]    PyRun_FileExFlags                                  + 0x130
[0x7feee401f6f3]    PyRun_SimpleFileExFlags                            + 0x173
[0x7feee403aa41]    Py_Main                                            + 0xd41
[0x400c1d]          main                                               + 0x16d
[0x7feee2fc6830]    __libc_start_main                                  + 0xf0
[0x4009e9]                                                            

Traceback (most recent call last):
  File "/home/seyyed/PycharmProjects/try_cntk/try_1_k2k.py", line 275, in <module>
    trainer.train_minibatch({features: x_batch, label: y_batch})
  File "/opt/anaconda3/envs/cntk-py36/lib/python3.6/site-packages/cntk/train/trainer.py", line 184, in train_minibatch
    device)
  File "/opt/anaconda3/envs/cntk-py36/lib/python3.6/site-packages/cntk/cntk_py.py", line 3027, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: SWIG director method error.

Process finished with exit code 1

**Comment by KeDengMS** [comment]
Are you using FP16?
