### ISSUE TITLE
C# error on examples

### ISSUE THREAD

**Issue by galvanchi** [Microsoft/CNTK#3088]
Hi,

I installed CNTK-2-5 from this tutorial https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Binary-Script

But when tried to run C# example from here CNTK-2-5\cntk\Examples\TrainingCSharp an error occur. Stack trace below:
```
   at CNTK.CNTKLibPINVOKE.SGDLearner__SWIG_1(HandleRef jarg1, HandleRef jarg2)
   at CNTK.CNTKLib.SGDLearner(ParameterVector parameters, TrainingParameterScheduleDouble learningRateSchedule)
   at CNTK.CSTrainingExamples.LogisticRegression.TrainAndEvaluate(DeviceDescriptor device) in C:\Projects\CNTK-2-5\cntk\Examples\TrainingCSharp\Common\LogisticRegression.cs:line 30
   at CNTK.CSTrainingExamples.Program.Main(String[] args) in C:\Projects\CNTK-2-5\cntk\Examples\TrainingCSharp\CSTrainingGPUExamples\Program.cs:line 15
```

Please can you help me? What I miss? Maybe am I need to install something additional?

**Comment by galvanchi** [comment]
Hi, got another one error in the same GPU project. Thrace below.

   at CNTK.MinibatchSource.TextFormatMinibatchSourceInternal(String dataFilePath, StreamConfigurationVector streamConfigs, UInt64 epochSize)
   at CNTK.CSTrainingExamples.MNISTClassifier.TrainAndEvaluate(DeviceDescriptor device, Boolean useConvolution, Boolean forceRetrain) in C:\Projects\CNTK-2-5\cntk\Examples\TrainingCSharp\Common\MNISTClassifier.cs:line 79
   at CNTK.CSTrainingExamples.Program.Main(String[] args) in C:\Projects\CNTK-2-5\cntk\Examples\TrainingCSharp\CSTrainingGPUExamples\Program.cs:line 18

**Comment by nmfisher** [comment]
I vaguely recall having a similar issue when first trying the binaries directly - IIRC there were some missing dependencies that were causing issues.

Is installing via Nuget an option for you?

**Comment by galvanchi** [comment]
Mhm, if I create new console project, add nuget packages for CPU and test classes for MNIST, then application goes to break mode.

**Comment by nmfisher** [comment]
I assume this is Visual Studio entering break mode because an exception is thrown - can you post a screenshot of the exception/call stack?
