### ISSUE TITLE
CNTK: Fatal Error installing on Windows 7 or 10, 64-bit CPU version

### ISSUE THREAD

**Issue by milesjm** [Microsoft/CNTK#3097]
Apologies if this was already addressed but I cannot find it. I am trying to setup CNTK (on Windows 7 and 10) from: https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Binary-Script

and while trying the initial install.bat in Step 2 throws the following error after "Performing download operations". Any thoughts anyone?

FYI This is from the 64-bit, CPU only version

    Fatal error during script execution!
     System.Management.Automation.RuntimeException: The variable '$SourceFile' cannot be retrieved because it has not been set.
       at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
       at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
       at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
       at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
       at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
       at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
       at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
       at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
       at System.Management.Automation.CommandProcessorBase.Complete()
    
    Error during install operation

**Comment by KeDengMS** [comment]
#3074? Please try upgrade your PowerShell version.
