### ISSUE TITLE
Reading data error when running alexnet: RuntimeError: Cannot open file 'ILSVRC2012_img_train/n02494079/n02494079_268.JPEG'

### ISSUE THREAD

**Issue by woskii** [Microsoft/CNTK#3123]
I am trying to run the Alexnet example in [this page](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/AlexNet/Python/AlexNet_ImageNet_Distributed.py), and dataset is prepared. But an error came out:
```
Traceback (most recent call last):
  File "AlexNet_ImageNet_Distributed.py", line 260, in <module>
    gen_heartbeat=True)
  File "AlexNet_ImageNet_Distributed.py", line 209, in alexnet_train_and_eval
    train_and_test(network, trainer, train_source, test_source, minibatch_size, epoch_size, restore)
  File "AlexNet_ImageNet_Distributed.py", line 185, in train_and_test
    test_config= TestConfig(test_source, minibatch_size=minibatch_size)
  File "/data/users/lsq/CNTK-master/bindings/python/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/data/users/lsq/CNTK-master/bindings/python/cntk/train/training_session.py", line 333, in train
    super(TrainingSession, self).train(device)
  File "/data/users/lsq/CNTK-master/bindings/python/cntk/cntk_py.py", line 3371, in train
    return _cntk_py.TrainingSession_train(self, computeDevice)
RuntimeError: Cannot open file '/data/users/lsq/CNTK-master/Examples/Image/DataSets/ImageNet/ILSVRC2012_img_train/n02494079/n02494079_268.JPEG'

[CALL STACK]
[0x7f2fb3dc626c]                                                       + 0x3b26c
[0x7f2fb3dcf81d]    CNTK::ImageDataDeserializer::ImageChunk::  GetSequence  (unsigned long,  std::vector<std::shared_ptr<CNTK::SequenceDataBase>,std::allocator<std::shared_ptr<CNTK::SequenceDataBase>>>&) + 0x2ad
[0x7f2fdd90f5af]                                                       + 0xca95af
[0x7f2fe615bcb3]    __kmp_invoke_microtask                             + 0x93
[0x7f2fe612a437]                                                       + 0x73437
[0x7f2fe6129b15]                                                       + 0x72b15
[0x7f2fe615c033]                                                       + 0xa5033
[0x7f2fec0d1184]                                                       + 0x8184
[0x7f2feb4e8ffd]    clone                                              + 0x6d

```
My train_map.txt is like this:
`/data/users/lsq/CNTK-master/Examples/Image/DataSets/ImageNet/ILSVRC2012_img_train/n02494079/n02494079_268.JPEG	447`
using absolute path. And I checked that the file is indeed exist. Is there anything wrong? Thanks in advance! I am using CNTK-2.3.1 on Ubuntu14.04.

**Comment by woskii** [comment]
It seems that just the file is damaged...Although I can open it, openCV is unable to read it. The problem is solved after I change to another version of datasets.
