### ISSUE TITLE
Unable to perform 16 bit inference on trained network.

### ISSUE THREAD

**Issue by rajat95** [Microsoft/CNTK#3184]
I have tried adding Cast layers to cloned model as well as passing 16 bit floats directly but nothing works.  

For the first case I cloned the model as follows
```
for node in node_outputs: print("name: {0} shape : {1}". format(node.name, node.shape))
last_node = C.logging.find_by_name(out, 'sig12')

cloned_layers = C.combine([last_node.owner]).clone(C.CloneMethod.freeze)
input1 = C.input_variable((3,  C.FreeDimension, C.FreeDimension), dtype=np.float32)
input2 = C.input_variable((1), dtype=np.float32)

fp16_inp = C.cast(input1, dtype=np.float16)
fp16_inp2 = C.cast(input2, dtype=np.float16)

fp16_mod = cloned_layers(fp16_inp2,fp16_inp)

```
The above snippet gives following error:
`
TypeError: positional argument 0's type Tensor[1] is incompatible with the type Tensor[np.float16,1] of the passed Variable`

I have also tried setting the dtype of input1 and input2 as np.float16 directly, but I get the same error.

If I pass a 16bit numpy array directly I get following warning thats ends up changing dtype back to float32 as can be seen from source code.

`core.py:361: UserWarning: your data is of type "float16", but your input variable (uid "Input282") expects "<type 'numpy.float32'>". Please convert your data beforehand to speed up training.
  (sample.dtype, var.uid, str(var.dtype)))
`

Also refer to issue here #3142

**Comment by KeDengMS** [comment]
Did you train your model with fp32 data? If so the input variable of the saved model is already fp32. The cast above is only needed if you trained the model with fp16 directly (via np.float16 inputs).

**Comment by rajat95** [comment]
I trained it with fp32 and did not have any casting layers because that was prior to when fp16 support was added. Even so, I am trying both fp16 and fp32 (along with cast) for input_variable and have also  tried passing in 16 bit numpy floats directly.

Is it the case that for 16 bit inference, you need to train the model explicitly with 16 bit floats? Preferably, one should be able to decide inference precision independent of training precision considering high costs involved in training.

**Comment by KeDengMS** [comment]
Simply casting trained weights of fp32 into fp16 may not work, as usually precision affects weight a lot. Training and inference are expected to be in the same precision.

But if you want to try, you can create a model with fp16 parameters and assign the values from fp32 model to it. In that case, your model takes fp16 input and you need to add cast to convert fp32 to fp16 if raw data is in fp32.

**Comment by rajat95** [comment]
Thanks for the prompt response. I have been attempting training in FP16 precision too and have been getting the following error. Can you look at the same and tell me if it's an error on my part or if I should log another bug for the issue.

`Selected GPU[0] TITAN V as the process wide default device.
-------------------------------------------------------------------
Build info: 

		Built time: Apr 13 2018 22:23:32
		Last modified date: Fri Apr 13 22:20:38 2018
		Build type: release
		Build target: GPU
		With ASGD: yes
		Math lib: mkl
		CUDA version: 9.0.0
		CUDNN version: 7.0.4
		Build Branch: HEAD
		Build SHA1: 11c82c8019b78323b4f5169a2d8c90fba5ae49da
		MPI distribution: Open MPI
		MPI version: 1.10.7
-------------------------------------------------------------------
/usr/local/lib/python2.7/dist-packages/cntk/core.py:361: UserWarning: your data is of type "float64", but your input variable (uid "Input3") expects "<type 'numpy.float32'>". Please convert your data beforehand to speed up training.
  (sample.dtype, var.uid, str(var.dtype)))
Learning rate per minibatch: 0.0025
Traceback (most recent call last):
  File "test_fp16.py", line 19, in <module>
    trainer.train_minibatch({   input : batch
  File "/usr/local/lib/python2.7/dist-packages/cntk/train/trainer.py", line 184, in train_minibatch
    device)
  File "/usr/local/lib/python2.7/dist-packages/cntk/cntk_py.py", line 3027, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: NDArrayView::GetTensorView: The specified ElementType 4half does not match the DataType Float

[CALL STACK]
[0x7f93a9ddcef9]                                                       + 0x8aeef9
[0x7f93a9f48869]    Microsoft::MSR::CNTK::TensorView<half> const* CNTK::NDArrayView::  GetTensorView  <half>() const + 0x49
[0x7f93a9f4a844]    std::shared_ptr<Microsoft::MSR::CNTK::Matrix<half>> CNTK::NDArrayView::  GetWritableMatrix  <half>(unsigned long) + 0x24
[0x7f93a9f9e870]    void CNTK::LearnerAdam::  Update  <half>(CNTK::Parameter const&,  std::shared_ptr<CNTK::NDArrayView> const&,  std::shared_ptr<CNTK::NDArrayView> const&,  unsigned long) const + 0x40
[0x7f93a9fa3207]    void CNTK::LearnerBase::  Update  <half>(CNTK::Parameter const&,  std::shared_ptr<CNTK::NDArrayView> const&,  std::shared_ptr<CNTK::NDArrayView> const&,  unsigned long) + 0x67
[0x7f93a9f99d04]    CNTK::LearnerBase::  Update  (std::unordered_map<CNTK::Parameter,std::shared_ptr<CNTK::NDArrayView>,std::hash<CNTK::Parameter>,std::equal_to<CNTK::Parameter>,std::allocator<std::pair<CNTK::Parameter const,std::shared_ptr<CNTK::NDArrayView>>>>&,  unsigned long,  bool) + 0x334
[0x7f93a9f6601b]    CNTK::Learners::  Update  (std::unordered_map<CNTK::Parameter,std::shared_ptr<CNTK::NDArrayView>,std::hash<CNTK::Parameter>,std::equal_to<CNTK::Parameter>,std::allocator<std::pair<CNTK::Parameter const,std::shared_ptr<CNTK::NDArrayView>>>>&,  unsigned long,  bool) + 0x57b
[0x7f93a9f56ad9]    CNTK::Trainer::  TrainLocalMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  bool,  CNTK::DeviceDescriptor const&) + 0x1a9
[0x7f93a9f57a5a]    CNTK::Trainer::  TrainMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  bool,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&) + 0x5a
[0x7f93a9f57b22]    CNTK::Trainer::  TrainMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  bool,  CNTK::DeviceDescriptor const&) + 0x52
[0x7f93aabcf2f5]                                                       + 0x2182f5
[0x4c30ce]          PyEval_EvalFrameEx                                 + 0x729e
[0x4b9ab6]          PyEval_EvalCodeEx                                  + 0x306
[0x4c1e6f]          PyEval_EvalFrameEx                                 + 0x603f
[0x4b9ab6]          PyEval_EvalCodeEx                                  + 0x306
[0x4c16e7]          PyEval_EvalFrameEx                                 + 0x58b7
[0x4b9ab6]          PyEval_EvalCodeEx                                  + 0x306
[0x4eb30f]                                                            
[0x4e5422]          PyRun_FileExFlags                                  + 0x82
[0x4e3cd6]          PyRun_SimpleFileExFlags                            + 0x186
[0x493ae2]          Py_Main                                            + 0x612
[0x7f93c1f7f830]    __libc_start_main                                  + 0xf0
[0x4933e9]          _start                                             + 0x29
`

I can repro this using following code on my machine 

`import numpy as np
import cntk as C
C.device.try_set_default_device(C.device.gpu(0))
with C.default_options(dtype=np.float16):
    input = C.input_variable((3,  C.FreeDimension, C.FreeDimension), dtype = np.float32)
    fp16_inp = C.cast(input, dtype=np.float16)
    net = C.layers.Convolution((3,3), num_filters = 3, pad = True, strides = (1,1),name = 'conv', init = C.initializer.normal(0.01))(fp16_inp)
    net = C.relu(net)
#    net = C.sigmoid(net, name = 'sig12')
    loss = C.cast(C.squared_error(fp16_inp,net), dtype=np.float32)

    learner = C.adam(net.parameters, 0.0025, 0.9)

    progress_writer = C.logging.ProgressPrinter(500)

    trainer = C.Trainer(net, (loss), learner, progress_writer)
batch = np.ones((4,3,256,256))

trainer.train_minibatch({   input : batch
                                    })
`

**Comment by rajat95** [comment]
Got it.. Error is with Adam Optimizer, Is it a bug or Adam isn't supported for now?

**Comment by KeDengMS** [comment]
Adam in FP16 is not supported yet (#2941).

**Comment by rajat95** [comment]
Thanks for all the help. Closing the issue.
