### ISSUE TITLE
module 'cntk' has no attribute 'learning_parameter_per_sample'

### ISSUE THREAD

**Issue by Chinese-Xu** [Microsoft/CNTK#3188]
**Env**

Win10 / Py3.6 / cntk2.5.1 cpu-only / VSCode

**Case**

Run 1stSteps/MNIST_Complex_Training.py

**Error message**

AttributeError: module 'cntk' has no attribute 'learning_parameter_per_sample'

**Detail**

Finished Epoch[10]: loss = 0.035307 * 54000, metric = 1.08% * 54000 40.146s (1345.1 samples/s);
Finished Epoch[11]: loss = 0.033584 * 54000, metric = 1.01% * 54000 36.936s (1462.0 samples/s);
Finished Epoch[12]: loss = 0.030132 * 54000, metric = 0.96% * 54000 35.926s (1503.1 samples/s);
Finished Evaluation [4]: Minibatch[1-24]: metric = 0.88% * 6000;
Finished Epoch[13]: loss = 0.027583 * 54000, metric = 0.85% * 54000 40.129s (1345.7 samples/s);
Finished Epoch[14]: loss = 0.026562 * 54000, metric = 0.81% * 54000 43.097s (1253.0 samples/s);
Finished Epoch[15]: loss = 0.024385 * 54000, metric = 0.76% * 54000 42.182s (1280.2 samples/s);
Finished Evaluation [5]: Minibatch[1-24]: metric = 0.90% * 6000;
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\cntk\train\training_session.py", line 349, in on_cross_validation_end
    return self.cv_callback(index, average_error, num_samples, num_minibatches)
  File "c:/cntk/CNTK-Samples-2-5-1/Examples/1stSteps/MNIST_Complex_Training.py", line 117, in adjust_lr_callback
    learner.reset_learning_rate(C.learning_parameter_per_sample(learner.learning_rate() / 2))
AttributeError: module 'cntk' has no attribute 'learning_parameter_per_sample'
Traceback (most recent call last):
  File "c:/cntk/CNTK-Samples-2-5-1/Examples/1stSteps/MNIST_Complex_Training.py", line 150, in <module>
    callbacks=[progress_writer, checkpoint_callback_config, cv_callback_config, test_callback_config])
  File "C:\Python36\lib\site-packages\cntk\ops\functions.py", line 1461, in train
    ts.train()
  File "C:\Python36\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Python36\lib\site-packages\cntk\train\training_session.py", line 333, in train
    super(TrainingSession, self).train(device)
  File "C:\Python36\lib\site-packages\cntk\cntk_py.py", line 3546, in train
    return _cntk_py.TrainingSession_train(self, computeDevice)
RuntimeError: SWIG director method error.

**Comment by tangyuq** [comment]
It should be C.learning_parameter_schedule_per_sample. Please see: 
https://cntk.ai/pythondocs/cntk.learners.html?highlight=learning_parameter#cntk.learners.learning_parameter_schedule_per_sample
