### ISSUE TITLE
 ValueError: Specified GPU device id (0) is invalid. 

### ISSUE THREAD

**Issue by JONYJONS** [Microsoft/CNTK#3210]
When try to run Faster RCNN toy example.
Can't do the  running, due to,  ValueError: Specified GPU device id (0) is invalid. 
I tried defining CPU or GPU,  the same error accrues. 
In fast RCNN example, there is no problem.
The full description:

python run_faster_rcnn.py
Traceback (most recent call last):
  File "run_faster_rcnn.py", line 31, in <module>
    cntk.device.try_set_default_device(cntk.device.gpu(cfg.GPU_ID))
  File "C:\Users\USER\AppData\Local\Programs\Python\Python35\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python35\lib\site-packages\cntk\device.py", line 96, in gpu
    return cntk_py.DeviceDescriptor.gpu_device(device_id)
ValueError: Specified GPU device id (0) is invalid.

[CALL STACK]
    > CNTK::Parameter::  SetValue
    - CNTK::DeviceDescriptor::  GPUDevice
    - PyInit__cntk_py
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)
    - PyFunction_SetAnnotations
    - PyObject_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)
    - PyEval_GetFuncDesc (x2)
    - PyEval_EvalFrameEx (x2)

**Comment by KeDengMS** [comment]
Seems you don't have CUDA setup correctly. Can you try below and see if GPU device could be initialized?
```
import cntk as C
C.constant(0)
```
Or just try in numba
```
from numba import cuda
cuda.detect()
```

**Comment by JONYJONS** [comment]
Solved the problem by using version 2.2 instead of 2.5+
