### ISSUE TITLE
RuntimeError: Plugin not found: 'Cntk.Deserializers.Image-2.5.1.dll'

### ISSUE THREAD

**Issue by StoneMa** [Microsoft/CNTK#3221]
Hello there,
    I clone this project to my computer, and try to run the example in the project, link is here:
[https://github.com/Microsoft/CNTK/tree/release/latest/Examples/Image/TransferLearning](https://github.com/Microsoft/CNTK/tree/release/latest/Examples/Image/TransferLearning). I do it just follow the step, but there are problems:
![image](https://user-images.githubusercontent.com/6917909/40537585-e1e40436-6041-11e8-844d-bc373dacafa3.png)

```
PS D:\VSCodeWorkSpace\DeepLearning\CNTK\Examples\Image\TransferLearning> python .\TransferLearning.py
Traceback (most recent call last):
  File ".\TransferLearning.py", line 217, in <module>
    max_epochs, freeze=freeze_weights)
  File ".\TransferLearning.py", line 101, in train_model
    minibatch_source = create_mb_source(train_map_file, image_width, image_height, num_channels, num_classes)
  File ".\TransferLearning.py", line 69, in create_mb_source
    randomize=randomize)
  File "C:\Anaconda3\lib\site-packages\cntk\io\__init__.py", line 226, in __init__
    source = cntk_py.create_composite_minibatch_source(config)
RuntimeError: Plugin not found: 'Cntk.Deserializers.Image-2.5.1.dll'

[CALL STACK]
    > CreateCompositeDataReader
    - CreateCompositeDataReader (x4)
    - CNTK::  UniversalLearner
    - CNTK::  CreateCompositeMinibatchSource
    - PyInit__cntk_py
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)
    - PyFunction_SetAnnotations
    - PyObject_Call
    - PyMethod_New
    - PyObject_Call

```

**Comment by KeDengMS** [comment]
If you build from source, please set environment variable `set PYTHONPATH=<your repo>\bindings\python`

**Comment by DaZiYuan** [comment]
same issue

**Comment by DaZiYuan** [comment]
```
python .\TransferLe
arning.py
Traceback (most recent call last):
  File ".\TransferLearning.py", line 217, in <module>
    max_epochs, freeze=freeze_weights)
  File ".\TransferLearning.py", line 101, in train_model
    minibatch_source = create_mb_source(train_map_file, image_width, image_height, num_channels, num_classes)
  File ".\TransferLearning.py", line 69, in create_mb_source
    randomize=randomize)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\cntk\io\__init__.py", line 226, in __init__
    source = cntk_py.create_composite_minibatch_source(config)
RuntimeError: Plugin not found: 'Cntk.Deserializers.Image-2.5.1.dll'

[CALL STACK]
    > CreateCompositeDataReader
    - CreateCompositeDataReader (x4)
    - CNTK::  UniversalLearner
    - CNTK::  CreateCompositeMinibatchSource
    - PyInit__cntk_py
    - PyCFunction_FastCallDict
    - PyObject_CallFunctionObjArgs
    - PyEval_EvalFrameDefault
    - Py_CheckFunctionResult
    - PyFunction_FastCallDict
    - PyObject_IsInstance
    - PyType_GenericAlloc
    - PyFrame_New
```

**Comment by HardesFaktor** [comment]
Hey,

had also the same problem like @DaZiYuan and @StoneMa and the problem is the "zip.dll" file in the same folder where you can find the Cntk.Deserializers.Image-2.5.1.dll. The Problem is, CNTK doesnt use this zip.dll because there is already an older zip.dll file somewhere in your system installes, e.g. java has also an zip.dll but older which CNTK missing some features and java has also an system enviorment PATH which causes that CNTK use the zip.dll from java and not from the same folder.
