### ISSUE TITLE
Unable to convert a net with division op to ONNX

### ISSUE THREAD

**Issue by rajat95** [Microsoft/CNTK#3254]
Consider following code snippet

```
import cntk as C
net = C.layers.Convolution((3,3), num_filters = 3, pad = True, strides = (1,1),name = 'conv', init = C.initializer.normal(0.01))(a)
mean = C.reduce_mean(net, axis = [1,2])
variance = C.reduce_mean(C.square(net-mean), axis = [1,2])
out = x/variance
# But the line below works
# out = x-mean
out.save('model.onnx', format = C.ModelFormat.ONNX)
```
the above snippet fails with following error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/cntk/ops/functions.py", line 1532, in save
    return super(Function, self).save(filename, format.value)
  File "/usr/local/lib/python2.7/dist-packages/cntk/cntk_py.py", line 2064, in save
    return _cntk_py.Function_save(self, *args)
RuntimeError: Error: two nodes with same node name (_static_axes_subop).

[CALL STACK]
[0x7fb7f1fe4ef9]                                                       + 0x8aeef9
[0x7fb7f224a6fc]    CNTK::CNTKToONNX::  CreateModel  (std::shared_ptr<CNTK::Function> const&) + 0x1dc
[0x7fb7f2272d56]    CNTK::ONNXFormat::  Save  (std::shared_ptr<CNTK::Function> const&,  std::__cxx11::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> const&) + 0x36
[0x7fb7f1fe9e1d]    CNTK::Function::  Save  (std::__cxx11::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> const&,  CNTK::ModelFormat) + 0x3d
[0x7fb7f2d7d84b]                                                       + 0x1be84b
[0x4c30ce]          PyEval_EvalFrameEx                                 + 0x729e
[0x4b9ab6]          PyEval_EvalCodeEx                                  + 0x306
[0x4c1e6f]          PyEval_EvalFrameEx                                 + 0x603f
[0x4b9ab6]          PyEval_EvalCodeEx                                  + 0x306
[0x4d55f3]                                                            
[0x4a577e]          PyObject_Call                                      + 0x3e
[0x4bed3d]          PyEval_EvalFrameEx                                 + 0x2f0d
[0x4b9ab6]          PyEval_EvalCodeEx                                  + 0x306
[0x4c1e6f]          PyEval_EvalFrameEx                                 + 0x603f
[0x4b9ab6]          PyEval_EvalCodeEx                                  + 0x306
[0x4eb30f]                                                            
[0x44a7a2]          PyRun_InteractiveOneFlags                          + 0x190
[0x44a56d]          PyRun_InteractiveLoopFlags                         + 0xba
[0x43092e]                                                            
[0x493ae2]          Py_Main                                            + 0x612
[0x7fb80a7fe830]    __libc_start_main                                  + 0xf0
[0x4933e9]          _start                                             + 0x29

**Comment by KeDengMS** [comment]
Thanks for reporting. It's a bug in CNTK to ONNX converter. To work around it, please give a name to reduce_mean op:
```
mean = C.reduce_mean(net, axis = [1,2], name='mean')
```
