### ISSUE TITLE
Unable to install CNTK for Keras using PyPi and use on Linux

### ISSUE THREAD

**Issue by vineetparikh** [Microsoft/CNTK#3260]
I'm planning on using CNTK with Keras (https://docs.microsoft.com/en-us/cognitive-toolkit/using-cntk-with-keras) and thus I've been attempting to install it using PyPi with this tutorial(https://docs.microsoft.com/en-us/cognitive-toolkit/setup-linux-python?tabs=cntkpy251#prerequisites). However, when I run `python3 -c "import cntk;print(cntk.__version__)", I receive this error:
```Traceback (most recent call last):
  File "/home_bunch/vinparik/.local/lib/python3.6/site-packages/cntk/cntk_py.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/cm/shared/apps/python3/3.6.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cntk._cntk_py'
```
Reinstalling CNTK using the wheel files and following the fix presented by this issue (https://github.com/Microsoft/CNTK/issues/1887) didn't really help either. How exactly would I be able to fix this error?

**Comment by thiagocrepaldi** [comment]
Could you show the full backtrace ? Maybe it is not finding libpython3.6.so, which is a bug on Anaconda or Python 3.6

Also, try creating a python 3.5 environment and install CNTK 2.5.1 on it. That will test the previous hypothesis.
