### ISSUE TITLE
Fast RCNN not working for object detection, but Faster RCNN is working

### ISSUE THREAD

**Issue by Jayu8** [Microsoft/CNTK#3267]
```
Selected CPU as the process wide default device.
Using base model:   AlexNet
lr_per_sample:      [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0001]
Training model for 20 epochs.
Training 57216469 parameters in 21 parameter tensors.
-------------------------------------------------------------------
Build info:

                Built time: Apr 13 2018 22:36:42
                Last modified date: Fri Apr 13 22:27:37 2018
                Build type: Release
                Build target: CPU-only
                With ASGD: yes
                Math lib: mkl
                Build Branch: HEAD
                Build SHA1: 11c82c8019b78323b4f5169a2d8c90fba5ae49da
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
Traceback (most recent call last):
  File "run_fast_rcnn.py", line 32, in <module>
    trained_model = train_fast_rcnn(cfg)
  File "D:\2_Aquired_Interests\4_AI\CNTK\Examples\Image\Detection\FastRCNN\FastRCNN_train.py", line 345, in train_fast_rcnn
    data = od_minibatch_source.next_minibatch(min(cfg.MB_SIZE, cfg["DATA"].NUM_TRAIN_IMAGES - sample_count), input_map=input_map)
  File "D:\2_Aquired_Interests\4_AI\CNTK\Examples\Image\Detection\FastRCNN\..\utils\od_mb_source.py", line 70, in next_minibatch
    img_data, roi_data, img_dims, proposals, label_targets, bbox_targets, bbox_inside_weights = self.od_reader.get_next_input()
  File "D:\2_Aquired_Interests\4_AI\CNTK\Examples\Image\Detection\FastRCNN\..\utils\od_reader.py", line 63, in get_next_input
    img_data, img_dims = self._load_resize_and_pad_image(index)
  File "D:\2_Aquired_Interests\4_AI\CNTK\Examples\Image\Detection\FastRCNN\..\utils\od_reader.py", line 215, in _load_resize_and_pad_image
    self._prepare_annotations_proposals_and_stats(index, img)
  File "D:\2_Aquired_Interests\4_AI\CNTK\Examples\Image\Detection\FastRCNN\..\utils\od_reader.py", line 181, in _prepare_annotations_proposals_and_stats
    proposals = self._proposal_provider.get_proposals(index, img)
  File "D:\2_Aquired_Interests\4_AI\CNTK\Examples\Image\Detection\FastRCNN\..\utils\proposal_helpers.py", line 277, in get_proposals
    return compute_proposals(img, num_proposals, self._proposal_cfg)
  File "D:\2_Aquired_Interests\4_AI\CNTK\Examples\Image\Detection\FastRCNN\..\utils\proposal_helpers.py", line 100, in compute_proposals
    if not ss_lib_loaded: load_selective_search_lib()
  File "D:\2_Aquired_Interests\4_AI\CNTK\Examples\Image\Detection\FastRCNN\..\utils\proposal_helpers.py", line 22, in load_selective_search_lib
    from dlib import find_candidate_object_locations as algo
ImportError: No module named 'dlib'
```
<br>
I tried this on normal Grocery dataset example provided.<br>
 I am using Anaconda latest version, with python 3.5 as a virtual environment, I also have CMake in my PATH variable.<br>
Why is this happening?<br>

**Comment by dregala3** [comment]
Was the dlib module installed properly? Also, are you using visual studio? Because if so, you need to restart visual studio after adding something in the PATH variable for the visual studio to access PATH

**Comment by Jayu8** [comment]
Yes the dlib was installed properly, and the dlib  for windows is for only 3.5 which I want to use anyway. 
I am not using visual studio.

**Comment by KeDengMS** [comment]
Does `import dlib` work in your virtual environment?

**Comment by Jayu8** [comment]
This seems to work now. Thank you @KeDengMS .

**Comment by MiqueiasBelarmino** [comment]
I has solve following this...(my trouble was dlib)(SORRY ANY LANGUAGE ERROR)
https://www.learnopencv.com/install-opencv-3-and-dlib-on-windows-python-only/
