### ISSUE TITLE
Error to import CNTK

### ISSUE THREAD

**Issue by neopedro** [Microsoft/CNTK#3309]
Error while trying to import CNTK. Does anyone have a solution to this problem?

>>> import cntk
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\cntk\cntk_py.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cntk._cntk_py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import cntk
  File "C:\Program Files\Python36\lib\site-packages\cntk\__init__.py", line 17, in <module>
    from . import cntk_py
  File "C:\Program Files\Python36\lib\site-packages\cntk\cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "C:\Program Files\Python36\lib\site-packages\cntk\cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by delzac** [comment]
There's quite a few issues opened on this, mostly its due to path (you need to add the correct path). #1887 might be a reference. A google search will turn up more possible solutions.
