### ISSUE TITLE
Importing ONNX to CNTK results in NaNs on opset 3 and RuntimeError in opset >= 6

### ISSUE THREAD

**Issue by tsocha** [Microsoft/CNTK#3310]
We are seeing `NaN`s results when running ResNet 50 from the ONNX model ZOO in opset 3 and we are seeing `RuntimeError`s during import on higher opsets.

Steps to reproduce:

1. Download the ResNet model (opset 3) from: 
https://s3.amazonaws.com/download.onnx/models/opset_3/resnet50.tar.gz

2. Run by this script:
```
import cntk
import numpy as np

data = np.ones((1, 3, 224, 224), dtype = np.float32)

cntk_model = cntk.Function.load("model.onnx", device=cntk.device.cpu(), format=cntk.ModelFormat.ONNX)

results = np.squeeze(cntk_model.eval({cntk_model.arguments[0]:[data]}))

print(results)
```

Actual result:
```
Selected CPU as the process wide default device.
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
...
```

Expected result would be different.

System `Ubuntu 16.04`
ONNX version `1.2.2`
CNTK version `2.5.1`
Models are downloaded from here: https://github.com/onnx/models/tree/master/resnet50
CNTK installed via `pip install cntk`

For models with opset 6-8 result is:
```
Inside File: Source/CNTKv2LibraryDll/proto/onnx/ONNXToCNTK.cpp  Line: 493  Function: CreateConstant  -> Feature Not Implemented.
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    cntk_model = cntk.Function.load("model.onnx", device=cntk.device.cpu(), format=cntk.ModelFormat.ONNX)
  File "/usr/local/lib/python3.5/dist-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/cntk/ops/functions.py", line 1608, in load
    return cntk_py.Function.load(str(model), device, format.value)
RuntimeError: Inside File: Source/CNTKv2LibraryDll/proto/onnx/ONNXToCNTK.cpp  Line: 493  Function: CreateConstant  -> Feature Not Implemented.


[CALL STACK]
[0x7f49d1f6ceb9]                                                       + 0x8a0eb9
[0x7f49d21e03a8]    CNTK::ONNXToCNTKHelper::  CreateConstant  (onnx::TensorProto const&,  std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>> const&,  CNTK::DeviceDescriptor const&) + 0x568
[0x7f49d21f25f5]    CNTK::ONNXToCNTKHelper::  CreateLeafVariableOrConstant  (ONNXIR::NodeArg const*,  ONNXIR::Node const*,  ONNXIR::Graph const*,  CNTK::DeviceDescriptor const&) + 0xd5
[0x7f49d21f47b0]    CNTK::ONNXToCNTKHelper::  CreateCNTKInputsStartingFromIndex  (ONNXIR::Node const*,  std::unordered_map<ONNXIR::Node const*,std::vector<std::shared_ptr<CNTK::Function>,std::allocator<std::shared_ptr<CNTK::Function>>>,std::hash<ONNXIR::Node const*>,std::equal_to<ONNXIR::Node const*>,std::allocator<std::pair<ONNXIR::Node const* const,std::vector<std::shared_ptr<CNTK::Function>,std::allocator<std::shared_ptr<CNTK::Function>>>>>>&,  std::unordered_map<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>,CNTK::Variable,std::hash<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>>,std::equal_to<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>>,std::allocator<std::pair<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>> const,CNTK::Variable>>>&,  ONNXIR::Graph const*,  unsigned long,  CNTK::DeviceDescriptor const&) + 0x2a0
[0x7f49d21f48b2]    CNTK::ONNXToCNTKHelper::  CreateCNTKInputs  (ONNXIR::Node const*,  std::unordered_map<ONNXIR::Node const*,std::vector<std::shared_ptr<CNTK::Function>,std::allocator<std::shared_ptr<CNTK::Function>>>,std::hash<ONNXIR::Node const*>,std::equal_to<ONNXIR::Node const*>,std::allocator<std::pair<ONNXIR::Node const* const,std::vector<std::shared_ptr<CNTK::Function>,std::allocator<std::shared_ptr<CNTK::Function>>>>>>&,  std::unordered_map<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>,CNTK::Variable,std::hash<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>>,std::equal_to<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>>,std::allocator<std::pair<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>> const,CNTK::Variable>>>&,  ONNXIR::Graph const*,  CNTK::DeviceDescriptor const&) + 0x22
[0x7f49d21f3672]    CNTK::ONNXToCNTKHelper::  FromONNXNode  (ONNXIR::Node const*,  std::unordered_map<ONNXIR::Node const*,std::vector<std::shared_ptr<CNTK::Function>,std::allocator<std::shared_ptr<CNTK::Function>>>,std::hash<ONNXIR::Node const*>,std::equal_to<ONNXIR::Node const*>,std::allocator<std::pair<ONNXIR::Node const* const,std::vector<std::shared_ptr<CNTK::Function>,std::allocator<std::shared_ptr<CNTK::Function>>>>>>&,  std::unordered_map<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>,CNTK::Variable,std::hash<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>>,std::equal_to<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>>,std::allocator<std::pair<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>> const,CNTK::Variable>>>&,  ONNXIR::Graph const*,  CNTK::DeviceDescriptor const&) + 0xd2
[0x7f49d21f3d2e]    CNTK::ONNXToCNTK::  CreateGraph  (ONNXIR::Graph*,  CNTK::DeviceDescriptor const&) + 0x17e
[0x7f49d21f8969]    CNTK::ONNXFormat::  Load  (std::__cxx11::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> const&,  CNTK::DeviceDescriptor const&) + 0x89
[0x7f49d1f71a55]    CNTK::Function::  Load  (std::__cxx11::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> const&,  CNTK::DeviceDescriptor const&,  CNTK::ModelFormat) + 0x65
[0x7f49d2c0d0a6]                                                       + 0x1bd0a6
[0x4e9b7f]          PyCFunction_Call                                   + 0x4f
[0x5372f4]          PyEval_EvalFrameEx                                 + 0x614
[0x540f9b]          PyEval_EvalCodeEx                                  + 0x13b
[0x4ebe37]
[0x5c1797]          PyObject_Call                                      + 0x47
[0x53920b]          PyEval_EvalFrameEx                                 + 0x252b
[0x5406df]
[0x53c1d0]          PyEval_EvalFrameEx                                 + 0x54f0
[0x540199]
[0x540e4f]          PyEval_EvalCode                                    + 0x1f
[0x60c272]
[0x60e71a]          PyRun_FileExFlags                                  + 0x9a
[0x60ef0c]          PyRun_SimpleFileExFlags                            + 0x1bc
[0x63fb26]          Py_Main                                            + 0x456
[0x4cfeb1]          main                                               + 0xe1
[0x7f4a769c9830]    __libc_start_main                                  + 0xf0
[0x5d6049]          _start                                             + 0x29
```

**Comment by KeDengMS** [comment]
We are working on opset 7 support in CNTK. This should be fixed in next release.

**Comment by tsocha** [comment]
Thanks for your reply.
