### ISSUE TITLE
Where are CNTK logs located + SEHEException (0x80004005)

### ISSUE THREAD

**Issue by oridayne** [Microsoft/CNTK#3370]
We are trying to deploy a CNTK C# classifier into production. The production VM does not have visual studio, so I manually copied over all the DLLs.
This includes the redistributables.

I can run my CNTK C# classifier with success in the VM by copying over an executable. It works fine, no problem. However, my class that uses the CNTK C# model is within our cloud service and is included in other code in production. When the code is run we get a:
thread2712:17 running main program failed System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
at CNTK.CNTKLibPINVOKE.Function__Load__SWIG_3(Byte[] jarg1, UInt32 jarg2, HandleRef jarg3)

   at CNTK.Function._Load(Byte[] buffer, UInt32 length, DeviceDescriptor computeDevice)

I'm really at a loss, because I've verified that all the dependencies of running CNTK C# have been satisfied, they're all in the System 32 folder, like vcruntime, vcomp140,etc.

I am now trying to figure out a way to debug this, and I notice that the C++ library does output logs somewhere.

**Comment by oridayne** [comment]
Problem is solved. I need to have all the dependencies in System32. Some of them were not in System 32 and were in the current folder I was running the executable in. I just put all the dlls associated with CNTK in System 32 and it works fine now.
