### ISSUE TITLE
Dilated 2D convolution failed if number of channel > 1

### ISSUE THREAD

**Issue by yanboliang** [Microsoft/CNTK#3371]
[This example](https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/ops/__init__.py#L312) can run well. If I set ```dilation = (2, 2)```, it still works well. But if I set ```dilation = (2, 2)``` and set input image with 3 channel(see following code), it throws exception.
code:
```
img = np.reshape(np.arange(75.0, dtype = np.float32), (3, 5, 5))  # change number of channel
x = C.input_variable(img.shape)
filter = np.reshape(np.array([2, -1, -1, 2], dtype = np.float32), (1, 2, 2))
kernel = C.constant(value = filter)
y = np.round(C.convolution(kernel, x, auto_padding = [False], dilation = (2, 2)).eval({x: [img]}),5)
print(y)
```
exception:
```
Selected GPU[0] Tesla P100-PCIE-12GB as the process wide default device.
cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=c5a120403527 ; expr=workspaceSizeFinder()
Traceback (most recent call last):
  File "test3.py", line 19, in <module>
    y = np.round(C.convolution(kernel, x, auto_padding = [False], dilation = (2, 2)).eval({x: [img]}),5)
  File "/usr/lib64/python2.7/site-packages/cntk/ops/functions.py", line 708, in eval
    _, output_map = self.forward(arguments, outputs, device=device, as_numpy=as_numpy)
  File "/usr/lib64/python2.7/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/usr/lib64/python2.7/site-packages/cntk/ops/functions.py", line 842, in forward
    keep_for_backward)
  File "/usr/lib64/python2.7/site-packages/cntk/cntk_py.py", line 1962, in _forward
    return _cntk_py.Function__forward(self, *args)
RuntimeError: cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=c5a120403527 ; expr=workspaceSizeFinder()

[CALL STACK]
[0x7ffaf5125569]                                                       + 0x712569
[0x7ffaecf788bf]                                                       + 0xdb08bf
[0x7ffaecf81ccd]    void Microsoft::MSR::CNTK::CuDnnConvolutionEngine<float>::  FindBestAlgo  <Microsoft::MSR::CNTK::CuDnnConvolutionEngine<float>::ConvAlgoInfo<cudnnConvolutionFwdAlgoPerf_t>,Microsoft::MSR::CNTK::CuDnnConvolutionEngine<float>::ForwardCore(Microsoft::MSR::CNTK::Matrix<float> const&,Microsoft::MSR::CNTK::Matrix<float> const&,Microsoft::MSR::CNTK::Matrix<float>&,Microsoft::MSR::CNTK::Matrix<float>&)::{lambda()#4},Microsoft::MSR::CNTK::CuDnnConvolutionEngine<float>::ForwardCore(Microsoft::MSR::CNTK::Matrix<float> const&,Microsoft::MSR::CNTK::Matrix<float> const&,Microsoft::MSR::CNTK::Matrix<float>&,Microsoft::MSR::CNTK::Matrix<float>&)::{lambda(int&,cudnnConvolutionFwdAlgoPerf_t*)#3},Microsoft::MSR::CNTK::CuDnnConvolutionEngine<float>::ForwardCore(Microsoft::MSR::CNTK::Matrix<float> const&,Microsoft::MSR::CNTK::Matrix<float> const&,Microsoft::MSR::CNTK::Matrix<float>&,Microsoft::MSR::CNTK::Matrix<float>&)::{lambda(Microsoft::MSR::CNTK::CuDnnConvolutionEngine<float>::ForwardCore(Microsoft::MSR::[0x7ffaecf82663]    Microsoft::MSR::CNTK::CuDnnConvolutionEngine<float>::  ForwardCore  (Microsoft::MSR::CNTK::Matrix<float> const&,  Microsoft::MSR::CNTK::Matrix<float> const&,  Microsoft::MSR::CNTK::Matrix<float>&,  Microsoft::MSR::CNTK::Matrix<float>&) + 0x73
[0x7ffaf53dafa3]    Microsoft::MSR::CNTK::ConvolutionNode<float>::  ForwardProp  (Microsoft::MSR::CNTK::FrameRange const&) + 0xa3
[0x7ffaf5629bf4]    Microsoft::MSR::CNTK::ComputationNetwork::PARTraversalFlowControlNode::  ForwardProp  (std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&,  Microsoft::MSR::CNTK::FrameRange const&) + 0xf4
[0x7ffaf5346d93]    std::_Function_handler<void (std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&),void Microsoft::MSR::CNTK::ComputationNetwork::ForwardProp<std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>>>(std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>> const&)::{lambda(std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&)#1}>::  _M_invoke  (std::_Any_data const&,  std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&) + 0x63
[0x7ffaf53929b9]    void Microsoft::MSR::CNTK::ComputationNetwork::  TravserseInSortedGlobalEvalOrder  <std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>>>(std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>> const&,  std::function<void (std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&)> const&) + 0x5b9
[0x7ffaf533715a]    CNTK::CompositeFunction::  Forward  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&) + 0x158a
[0x7ffaf52d9473]    CNTK::Function::  Forward  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&,  std::unordered_set<CNTK::Variable,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<CNTK::Variable>> const&) + 0x93
[0x7ffaf5f041f9]                                                       + 0x681f9
[0x7ffb9d8aa20a]    PyEval_EvalFrameEx                                 + 0x730a
[0x7ffb9d8ac03d]    PyEval_EvalCodeEx                                  + 0x7ed
[0x7ffb9d8a953c]    PyEval_EvalFrameEx                                 + 0x663c
[0x7ffb9d8ac03d]    PyEval_EvalCodeEx                                  + 0x7ed
[0x7ffb9d835a6d]                                                       + 0x70a6d
[0x7ffb9d810a63]    PyObject_Call                                      + 0x43
[0x7ffb9d8a46fd]    PyEval_EvalFrameEx                                 + 0x17fd
[0x7ffb9d8ac03d]    PyEval_EvalCodeEx                                  + 0x7ed
[0x7ffb9d8a953c]    PyEval_EvalFrameEx                                 + 0x663c
[0x7ffb9d8ac03d]    PyEval_EvalCodeEx                                  + 0x7ed
[0x7ffb9d8a953c]    PyEval_EvalFrameEx                                 + 0x663c
[0x7ffb9d8ac03d]    PyEval_EvalCodeEx                                  + 0x7ed
[0x7ffb9d8ac142]    PyEval_EvalCode                                    + 0x32
[0x7ffb9d8c557f]                                                       + 0x10057f
[0x7ffb9d8c673e]    PyRun_FileExFlags                                  + 0x7e
[0x7ffb9d8c79c9]    PyRun_SimpleFileExFlags                            + 0xe9
[0x7ffb9d8d8b7f]    Py_Main                                            + 0xc9f
[0x7ffb9caf5445]    __libc_start_main                                  + 0xf5
[0x40066e]
```

Does anyone know how to fix it? Do I use it in the correct way? Thanks.

**Comment by yanboliang** [comment]
```C.convolution_transpose``` has the same issue. If number of input channel or output channel is not 1, it may throw exceptions.

**Comment by BowenBao** [comment]
In your example, you might want to try using filter shape (3, 2, 2), and dilation (1, 2, 2). Normally the kernel input channel size should match input channel size. Dilation should also be 1 for input channel axis.

```
img = np.reshape(np.arange(75.0, dtype = np.float32), (3, 5, 5))  # change number of channel
x = C.input_variable(img.shape)
filter = np.reshape(np.array([2, -1, -1, 2]*3, dtype = np.float32), (3, 2, 2))
kernel = C.constant(value = filter)
y = np.round(C.convolution(kernel, x, auto_padding = [False], dilation = (1, 2, 2)).eval({x: [img]}),5)
print(y)
```

**Comment by yanboliang** [comment]
@BowenBao Thanks for you reply, it does worked. I should check it carefully before.
