### ISSUE TITLE
DQNcar.py MemoryError(Ubuntu18.04)

### ISSUE THREAD

**Issue by yujianyuanhaha** [Microsoft/CNTK#3503]
OS: __Ubuntu18.4__
CNTK version __2.5__
UE4Editor version: 4.17
Airsim version: 4.18
I finally successfully install the cntk on Ubuntu18.04, and `hello_car.py` also runs well, while met new issue of __MemoryError__ when call the `DQNcar.py`, error shown as
```
/home/jet/anaconda3/envs/py2/lib/python2.7/site-packages/cntk/cntk_py_init.py:47: UserWarning: Unsupported Linux distribution (ubuntu-18.04). CNTK supports Ubuntu 16.04 and above, only.
  warnings.warn('Unsupported Linux distribution (%s-%s). CNTK supports Ubuntu 16.04 and above, only.' % (__my_distro__, __my_distro_ver__))
Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

Traceback (most recent call last):
  File "DQNcar.py", line 505, in <module>
    agent = DeepQAgent((NumBufferFrames, SizeRows, SizeCols), NumActions, monitor=True)
  File "DQNcar.py", line 270, in __init__
    self._memory = ReplayMemory(memory_size, input_shape[1:], 4)
  File "DQNcar.py", line 35, in __init__
    self._states = np.zeros((size,) + sample_shape, dtype=np.float32)
MemoryError

```
Anybody got a idea?

**Comment by yujianyuanhaha** [comment]
move to Airsim
