### ISSUE TITLE
CUBLAS failures 8 & 13 with basic python examples

### ISSUE THREAD

**Issue by sunnsurf** [Microsoft/CNTK#3566]
Hi, I'm experiencing CUBLAS failures (8 & 13) running some basic unedited CNTK 2.6 examples. 

Environment: 
                Visual Studio 15.9.5
                Anaconda 5.2.0
                GPU: 1 x GeForce RTX 2070 
-------------------------------------------------------------------
Build info:
                Built time: Sep 14 2018 01:47:43
                Last modified date: Fri Sep 14 01:06:49 2018
                Build type: Release
                Build target: GPU
                With ASGD: yes
                Math lib: mkl
                CUDA version: 9.0.0
                CUDNN version: 7.0.5
                Build Branch: HEAD
                Build SHA1: 7c1b0fadb64f83a41739020b24fb2d4950015229
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------

1. Both LogisticRegression_FunctionAPI.py, LogisticRegression_GraphAPI.py examples encounter 

RuntimeError: CUBLAS failure 13: CUBLAS_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=Z ; expr=cublasgemmHelper(cuHandle, transA, transB, m, n, k, &alpha, a.Data(), (int) a.m_numRows, b.Data(), (int) b.m_numRows, &beta, c.Data(), (int) c.m_numRows)

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::GPUMatrix<float>::  MultiplyAndWeightedAdd
    - Microsoft::MSR::CNTK::Matrix<float>::  MultiplyAndWeightedAdd
    - Microsoft::MSR::CNTK::TensorView<float>::  DoMatrixProductOf
    - Microsoft::MSR::CNTK::TensorView<float>::  AssignMatrixProductOf
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this (x2)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfUnitsSeen
    - CNTK::Trainer::  TrainMinibatch (x2)

2. MNIST_Complex_Training.py initially encounters a "CUBLAS failure 8" exception then after adding "C.debugging.force_deterministic(0)" the following result is observed

ping [requestnodes (before change)]: 1 nodes pinging each other
ping [requestnodes (after change)]: 1 nodes pinging each other
requestnodes [MPIWrapperMpi]: using 1 out of 1 MPI nodes on a single host (1 requested); we (0) are in (participating)
ping [mpihelper]: 1 nodes pinging each other
Finished Epoch[1]: loss = 0.553482 * 54000, metric = 18.01% * 54000 3.071s (17583.8 samples/s);
Finished Epoch[2]: loss = 0.137347 * 54000, metric = 3.98% * 54000 1.574s (34307.5 samples/s);
Finished Epoch[3]: loss = 0.092473 * 54000, metric = 2.68% * 54000 1.558s (34659.8 samples/s);
Finished Evaluation [1]: Minibatch[1-24]: metric = 1.53% * 6000;
Finished Epoch[4]: loss = 0.074115 * 54000, metric = 2.22% * 54000 1.621s (33312.8 samples/s);
Finished Epoch[5]: loss = 0.064430 * 54000, metric = 1.88% * 54000 1.541s (35042.2 samples/s);
Finished Epoch[6]: loss = 0.055592 * 54000, metric = 1.67% * 54000 1.524s (35433.1 samples/s);
Finished Evaluation [2]: Minibatch[1-24]: metric = 1.13% * 6000;
Finished Epoch[7]: loss = 0.047265 * 54000, metric = 1.41% * 54000 1.470s (36734.7 samples/s);
Finished Epoch[8]: loss = 0.043532 * 54000, metric = 1.27% * 54000 1.363s (39618.5 samples/s);
Finished Epoch[9]: loss = 0.039561 * 54000, metric = 1.20% * 54000 1.355s (39852.4 samples/s);
Finished Evaluation [3]: Minibatch[1-24]: metric = 0.97% * 6000;
Finished Epoch[10]: loss = 0.036050 * 54000, metric = 1.11% * 54000 1.438s (37552.2 samples/s);
Finished Epoch[11]: loss = 0.033511 * 54000, metric = 1.01% * 54000 1.348s (40059.3 samples/s);
Finished Epoch[12]: loss = 0.030113 * 54000, metric = 0.96% * 54000 1.357s (39793.7 samples/s);
Finished Evaluation [4]: Minibatch[1-24]: metric = 0.93% * 6000;
Improvement of metric from 0.010 to 0.009 insufficient. Halving learning rate to 0.0005.
Finished Epoch[13]: loss = 0.024029 * 54000, metric = 0.72% * 54000 1.447s (37318.6 samples/s);
Finished Epoch[14]: loss = 0.022297 * 54000, metric = 0.68% * 54000 1.350s (40000.0 samples/s);
Finished Epoch[15]: loss = 0.020955 * 54000, metric = 0.62% * 54000 1.359s (39735.1 samples/s);
Finished Evaluation [5]: Minibatch[1-24]: metric = 0.85% * 6000;
Finished Epoch[16]: loss = 0.019983 * 54000, metric = 0.62% * 54000 1.364s (39589.4 samples/s);
Finished Epoch[17]: loss = 0.017243 * 54000, metric = 0.55% * 54000 1.225s (44081.6 samples/s);
Finished Epoch[18]: loss = 0.017874 * 54000, metric = 0.57% * 54000 1.226s (44045.7 samples/s);
Finished Evaluation [6]: Minibatch[1-24]: metric = 0.80% * 6000;
Finished Epoch[19]: loss = 0.017196 * 54000, metric = 0.51% * 54000 1.315s (41064.6 samples/s);
Finished Epoch[20]: loss = 0.016136 * 54000, metric = 0.52% * 54000 1.221s (44226.0 samples/s);
Finished Epoch[21]: loss = 0.015683 * 54000, metric = 0.50% * 54000 1.224s (44117.6 samples/s);
Finished Evaluation [7]: Minibatch[1-24]: metric = 0.73% * 6000;
Finished Epoch[22]: loss = 0.015873 * 54000, metric = 0.50% * 54000 1.361s (39676.7 samples/s);
Finished Epoch[23]: loss = 427867.553185 * 54000, metric = 62.95% * 54000 1.196s (45150.5 samples/s);
Finished Epoch[24]: loss = 2.307748 * 54000, metric = 89.37% * 54000 1.160s (46551.7 samples/s);
Finished Evaluation [8]: Minibatch[1-24]: metric = 88.42% * 6000;
Improvement of metric from 0.007 to 0.884 insufficient. Halving learning rate to 0.00025.
Finished Epoch[25]: loss = 2.301462 * 54000, metric = 88.80% * 54000 1.237s (43654.0 samples/s);
Finished Epoch[26]: loss = 2.301342 * 54000, metric = 88.80% * 54000 1.149s (46997.4 samples/s);
Finished Epoch[27]: loss = 2.301326 * 54000, metric = 88.80% * 54000 1.149s (46997.4 samples/s);
Finished Evaluation [9]: Minibatch[1-24]: metric = 88.42% * 6000;
Improvement of metric from 0.884 to 0.884 insufficient. Halving learning rate to 0.000125.
Finished Epoch[28]: loss = 2.301281 * 54000, metric = 88.80% * 54000 1.231s (43866.8 samples/s);
Finished Epoch[29]: loss = 2.301275 * 54000, metric = 88.80% * 54000 1.142s (47285.5 samples/s);
Finished Epoch[30]: loss = 2.301273 * 54000, metric = 88.80% * 54000 1.154s (46793.8 samples/s);
Finished Evaluation [10]: Minibatch[1-24]: metric = 88.42% * 6000;
Improvement of metric from 0.884 to 0.884 insufficient. Halving learning rate to 6.25e-05.
Finished Epoch[31]: loss = 2.301246 * 54000, metric = 88.80% * 54000 1.323s (40816.3 samples/s);
Finished Epoch[32]: loss = 2.301246 * 54000, metric = 88.80% * 54000 1.175s (45957.4 samples/s);
Finished Epoch[33]: loss = 2.301246 * 54000, metric = 88.80% * 54000 1.170s (46153.8 samples/s);
Finished Evaluation [11]: Minibatch[1-24]: metric = 88.42% * 6000;
Improvement of metric from 0.884 to 0.884 insufficient. Halving learning rate to 3.125e-05.
Finished Epoch[34]: loss = 2.301233 * 54000, metric = 88.80% * 54000 1.260s (42857.1 samples/s);
Finished Epoch[35]: loss = 2.301233 * 54000, metric = 88.80% * 54000 1.177s (45879.4 samples/s);
Finished Epoch[36]: loss = 2.301232 * 54000, metric = 88.80% * 54000 1.185s (45569.6 samples/s);
Finished Evaluation [12]: Minibatch[1-24]: metric = 88.42% * 6000;
Improvement of metric from 0.884 to 0.884 insufficient. Halving learning rate to 1.5625e-05.
Finished Epoch[37]: loss = 2.301226 * 54000, metric = 88.80% * 54000 1.283s (42088.9 samples/s);
Finished Epoch[38]: loss = 2.301226 * 54000, metric = 88.80% * 54000 1.179s (45801.5 samples/s);
Finished Epoch[39]: loss = 2.301226 * 54000, metric = 88.80% * 54000 1.199s (45037.5 samples/s);
Finished Evaluation [13]: Minibatch[1-24]: metric = 88.42% * 6000;
Learning rate 7.8125e-06 too small. Training complete.
Finished Evaluation [14]: Minibatch[1-313]: metric = 88.65% * 10000;
Label    : [7, 2, 8, 8, 3, 6, 5, 8, 9, 2, 9, 7, 7, 4, 7, 9, 0, 2, 8, 1, 4, 4, 2, 1, 5]
Predicted: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

**Comment by sunnsurf** [comment]
Tracebacks:
1. LogisticRegression_FunctionalAPI.py
  File ".....\LogisticRegression_FunctionalAPI.py", line 65, in <module>
    progress = criterion.train((X_train, Y_train), parameter_learners=[learner], callbacks=[progress_writer])
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\cntk\ops\functions.py", line 1486, in train
    ts.train()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\cntk\train\training_session.py", line 333, in train
    super(TrainingSession, self).train(device)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\cntk\cntk_py.py", line 3588, in train
    return _cntk_py.TrainingSession_train(self, computeDevice)
RuntimeError: CUBLAS failure 13: CUBLAS_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=Z440 ; expr=cublasgemmHelper(cuHandle, transA, transB, m, n, k, &alpha, a.Data(), (int) a.m_numRows, b.Data(), (int) b.m_numRows, &beta, c.Data(), (int) c.m_numRows)

2. LogisticRegression_GraphAPI.py
  File ".....\LogisticRegression_GraphAPI.py", line 68, in <module>
    trainer.train_minibatch({data: x, label_one_hot: y})  # update model from one minibatch
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\cntk\train\trainer.py", line 184, in train_minibatch
    device)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\cntk\cntk_py.py", line 3065, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)

3. MNIST_Complex_Training.py
cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=Z ; expr=cudnnConvolutionForward(*m_cudnn, &C::One, m_inT, ptr(in), *m_kernelT, ptr(kernel), *m_conv, m_fwdAlgo.selectedAlgo, ptr(workspace), workspace.BufferSize(), &C::Zero, m_outT, ptr(out))
Traceback (most recent call last):
  File ".....\MNIST_Complex_Training.py", line 152, in <module>
    callbacks=[progress_writer, checkpoint_callback_config, cv_callback_config, test_callback_config])
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\cntk\ops\functions.py", line 1486, in train
    ts.train()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\cntk\train\training_session.py", line 333, in train
    super(TrainingSession, self).train(device)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\cntk\cntk_py.py", line 3588, in train
    return _cntk_py.TrainingSession_train(self, computeDevice)
RuntimeError: cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=Z440 ; expr=cudnnConvolutionForward(*m_cudnn, &C::One, m_inT, ptr(in), *m_kernelT, ptr(kernel), *m_conv, m_fwdAlgo.selectedAlgo, ptr(workspace), workspace.BufferSize(), &C::Zero, m_outT, ptr(out))

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop (x2)
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this (x2)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfUnitsSeen
    - CNTK::Trainer::  TrainMinibatch (x2)
    - CNTK::TrainingSession::  Train
    - PyInit__cntk_py
    - PyCFunction_FastCallDict

**Comment by sunnsurf** [comment]
The error with the MNIST example may be the same as for issue #3496

**Comment by pmfcdb** [comment]
Hi, I'm also having the same issue in python and in brainscript, both of this examples work with cpu.

Environment:
- win10 x64
- nvidia rtx 2070 ( driver version : 25.21.14.1917 driver date:20/02/2019)
- cntk 2.6 ( manual install)
-anaconda 4.1.1 (python 3.5.2)

Example: FeedForwardNet.py
Selected GPU[0] GeForce RTX 2070 as the process wide default device.
-------------------------------------------------------------------
Build info:

                Built time: Sep 14 2018 01:47:43
                Last modified date: Fri Sep 14 01:06:49 2018
                Build type: Release
                Build target: GPU
                With ASGD: yes
                Math lib: mkl
                CUDA version: 9.0.0
                CUDNN version: 7.0.5
                Build Branch: HEAD
                Build SHA1: 7c1b0fadb64f83a41739020b24fb2d4950015229
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------

About to throw exception 'CUBLAS failure 13: CUBLAS_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=CVIG-PB ; expr=cublasgemmHelper(cuHandle, transA, transB, m, n, k, &alpha, a.Data(), (int) a.m_numRows, b.Data(), (int) b.m_numRows, &beta, c.Data(), (int) c.m_numRows)'
CUBLAS failure 13: CUBLAS_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=CVIG-PB ; expr=cublasgemmHelper(cuHandle, transA, transB, m, n, k, &alpha, a.Data(), (int) a.m_numRows, b.Data(), (int) b.m_numRows, &beta, c.Data(), (int) c.m_numRows)
Traceback (most recent call last):
  File "FeedForwardNet.py", line 81, in <module>
    error = ffnet()
  File "FeedForwardNet.py", line 67, in ffnet
    trainer.train_minibatch({feature: features, label: labels})
  File "C:\Anaconda3\lib\site-packages\cntk\train\trainer.py", line 184, in train_minibatch
    device)
  File "C:\Anaconda3\lib\site-packages\cntk\cntk_py.py", line 3065, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: CUBLAS failure 13: CUBLAS_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=CVIG-PB ; expr=cublasgemmHelper(cuHandle, transA, transB, m, n, k, &alpha, a.Data(), (int) a.m_numRows, b.Data(), (int) b.m_numRows, &beta, c.Data(), (int) c.m_numRows)

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::GPUMatrix<float>::  MultiplyAndWeightedAdd
    - Microsoft::MSR::CNTK::Matrix<float>::  MultiplyAndWeightedAdd
    - Microsoft::MSR::CNTK::TensorView<float>::  DoMatrixProductOf
    - Microsoft::MSR::CNTK::TensorView<float>::  AssignMatrixProductOf
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this (x2)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfUnitsSeen
    - CNTK::Trainer::  TrainMinibatch (x2)


Example: cntk  configFile=ResNet20_CIFAR10.cntk
-------------------------------------------------------------------
Build info: 

		Built time: Sep 14 2018 01:47:43
		Last modified date: Fri Sep 14 01:06:49 2018
		Build type: Release
		Build target: GPU
		With ASGD: yes
		Math lib: mkl
		CUDA version: 9.0.0
		CUDNN version: 7.0.5
		Build Branch: HEAD
		Build SHA1: 7c1b0fadb64f83a41739020b24fb2d4950015229
		MPI distribution: Microsoft MPI
		MPI version: 7.0.12437.6
-------------------------------------------------------------------
-------------------------------------------------------------------
GPU info:

		Device[0]: cores = 6912; computeCapability = 7.5; type = "GeForce RTX 2070"; total memory = 8192 MB; free memory = 0 MB
-------------------------------------------------------------------

(...)

About to throw exception 'cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=CVIG-PB ; expr=cudnnConvolutionForward(*m_cudnn, &C::One, m_inT, ptr(in), *m_kernelT, ptr(kernel), *m_conv, m_fwdAlgo.selectedAlgo, ptr(workspace), workspace.BufferSize(), &C::Zero, m_outT, ptr(out))'
cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=CVIG-PB ; expr=cudnnConvolutionForward(*m_cudnn, &C::One, m_inT, ptr(in), *m_kernelT, ptr(kernel), *m_conv, m_fwdAlgo.selectedAlgo, ptr(workspace), workspace.BufferSize(), &C::Zero, m_outT, ptr(out))


[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop (x2)
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>   (x8)
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  __autoclassinit2 (x3)
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this
    - BaseThreadInitThunk

EXCEPTION occurred: cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=CVIG-PB ; expr=cudnnConvolutionForward(*m_cudnn, &C::One, m_inT, ptr(in), *m_kernelT, ptr(kernel), *m_conv, m_fwdAlgo.selectedAlgo, ptr(workspace), workspace.BufferSize(), &C::Zero, m_outT, ptr(out))
