### ISSUE TITLE
`classification_error ` bug when providing topN argument

### ISSUE THREAD

**Issue by abhaikollara** [Microsoft/CNTK#3582]
### [Python API]
Providing a `topN` argument to the [example](https://www.cntk.ai/pythondocs/cntk.metrics.html#cntk.metrics.classification_error) given in the docs for `classification_error` throws an error i.e

```python
C.classification_error([[1., 2., 3., 4.]], [[0., 0., 0., 1.]], topN=3).eval()
```
throws an error

```
About to throw exception 'Node 'ClassificationError6' (ClassificationError operation): Expected MBLayout in Input 0.'
Validating --> ClassificationError6 = ClassificationError (Constant4, Constant3, Constant5) : [4 x 1], [4 x 1], [] -> [] FAILED
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abhai/keras/lib/python3.6/site-packages/cntk/ops/functions.py", line 733, in eval
    _, output_map = self.forward(arguments, outputs, device=device, as_numpy=as_numpy)
  File "/home/abhai/keras/lib/python3.6/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/home/abhai/keras/lib/python3.6/site-packages/cntk/ops/functions.py", line 867, in forward
    keep_for_backward)
  File "/home/abhai/keras/lib/python3.6/site-packages/cntk/cntk_py.py", line 1980, in _forward
    return _cntk_py.Function__forward(self, *args)
RuntimeError: Node 'ClassificationError6' (ClassificationError operation): Expected MBLayout in Input 0.
```
I'm not sure if this is the correct usage since `topN` is not mentioned in the docs either.

**Comment by delzac** [comment]
There's no bug, its working as intended. Sample code below.

```
import cntk as C

a = C.input_variable(4)
b = C.input_variable(4)
c = C.classification_error(a, b, topN=2)

print(c.eval({a: [[1., 2., 3., 4.]], b: [[0., 1., 0., 0.]]}))  # outputs 1 (not in top 2)
print(c.eval({a: [[1., 2., 3., 4.]], b: [[0., 0., 1., 0.]]}))  # outputs 0 (in top 2)
```

**Comment by abhaikollara** [comment]
Thank you @delzac, your sample code works for me as well. But I'm still confused, is the code given in docs not the right way to do it ?

**Comment by delzac** [comment]
The issue is that the docs set topN=1. But based on the error you have given for topN>1, it seems that cntk requires the input to have a Minibatch layout in its inputs. Easiest way to provide that is to provide it a input_variable node.
