### ISSUE TITLE
RuntimeError: Failed to parse Dictionary from the input stream.

### ISSUE THREAD

**Issue by shikarE1** [Microsoft/CNTK#3650]
Hello!im completely new to cntk .i recently installed cntk 2.7 (GPU version)on my pc (windows 10) with GeForce 940MX GPU. im trying to set up cntk and the faster rcnn object-detection example provided in the link below
https://docs.microsoft.com/en-us/cognitive-toolkit/object-detection-using-faster-r-cnn
..im trying to run the toy example...

after running the install_data_and_model.py in Examples/Image/Detection/FastRCNN folder,
i run the run_faster_rcnn.py  Examples/Image/Detection/FasterRCNN folder
 i get the following error:
Selected GPU[0] GeForce 940MX as the process wide default device.

About to throw exception 'Failed to parse Dictionary from the input stream.'
Traceback (most recent call last):
  File "run_faster_rcnn.py", line 34, in <module>
    trained_model = train_faster_rcnn(cfg)
  File "C:\Users\HP-PC\Anaconda3\Lib\site-packages\cntk\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 291, in train_faster_rcnn
    eval_model = train_faster_rcnn_e2e(cfg)
  File "C:\Users\HP-PC\Anaconda3\Lib\site-packages\cntk\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 314, in train_faster_rcnn_e2e
    loss, pred_error = create_faster_rcnn_model(image_input, roi_input, dims_node, cfg)
  File "C:\Users\HP-PC\Anaconda3\Lib\site-packages\cntk\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 177, in create_faster_rcnn_model
    base_model = load_model(cfg['BASE_MODEL_PATH'])
  File "C:\Users\HP-PC\Anaconda3\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\HP-PC\Anaconda3\lib\site-packages\cntk\ops\functions.py", line 1721, in load_model
    return Function.load(model, device, format)
  File "C:\Users\HP-PC\Anaconda3\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\HP-PC\Anaconda3\lib\site-packages\cntk\ops\functions.py", line 1635, in load
    return cntk_py.Function.load(str(model), device, format.value)
RuntimeError: Failed to parse Dictionary from the input stream.

[CALL STACK]
    > CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::operator>>
    - CNTK::Function::  Load
    - PyInit__cntk_py (x2)
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)
    - PyFunction_SetAnnotations
    - PyObject_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)
    - PyEval_GetFuncDesc (x2)

Can someone help me with what the issue is all about?

**Comment by AllanYiin** [comment]
This error always happen when you shutdown cntk when last model was saving,so the model file break
