### ISSUE TITLE
Scripted install of CNTK prerequisites - Build fails.

### ISSUE THREAD

**Issue by IvanFarkas** [microsoft/CNTK#3670]
### Scripted install of CNTK prerequisites - Build fails.

I have tried the [massively outdated documentation](https://github.com/microsoft/CNTK/issues/3669) to set up the CNTK Development environment prerequisites and build the solution, but the build fails.

Subsequently, I tried the [Setup CNTK with script on Windows](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-with-script-on-Windows) instructions.
The setup, that is completely out of sync of the [manual process](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Windows), succeeded, but the build still fails.

Please provide at least one way to build the solution successfully!

**Build Errors**

```
1>------ Build started: Project: MathCUDA, Configuration: Release x64 ------
2>------ Build started: Project: SGDLib, Configuration: Release x64 ------
2>SimpleDistGradAggregatorHelper.cpp
1>Skipping CUDA source file GPUMatrixCUDAKernels.cuh (excluded from build).
1>Skipping CUDA source file MatrixQuantizer_kernel.cu (excluded from build).
1>Compiling CUDA source file GPUMatrix.cu...
1>
1>C:\local\CNTK\CNTK\Source\Math>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" --use-local-env -Xcompiler /WX -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64" -x cu  -IC:\local\CNTK\CNTK\Source\Common\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -I"C:\local\cub-1.8.0" -I"c:\local\cudnn-10.0-v7.3.1\cuda\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include"   -lineinfo --keep --keep-dir C:\local\CNTK\CNTK\x64\.build\Release\Source\Math\\MathCUDA -maxrregcount=0  --machine 64 --compile -cudart static -Xcudafe "--diag_suppress=field_without_dll_interface" -Xcompiler "/wd 4819"   -use_fast_math -DNO_SYNC -DWIN32 -D_WINDOWS -D_USRDLL -DMATH_EXPORTS -DUSE_CUDNN -D_UNICODE -DUNICODE -DNDEBUG -D"CNTK_VERSION=\"2.7\"" -D"CNTK_VERSION_BANNER=\"2.7+\"" -D"CNTK_COMPONENT_VERSION=\"2.7\"" -DHAS_MPI=1 -DCUDA_NO_HALF -D__CUDA_NO_HALF_OPERATORS__ -Xcompiler "/EHsc /W4 /nologo /O2 /FdC:\local\CNTK\CNTK\x64\.build\Release\Source\Math\\MathCUDA\MathCUDA.pdb /FS /Zi  /MD " -o C:\local\CNTK\CNTK\x64\.build\Release\Source\Math\\MathCUDA\GPUMatrix.cu.obj "C:\local\CNTK\CNTK\Source\Math\GPUMatrix.cu"
2>c:\local\cntk\cntk\source\sgdlib\simpledistgradaggregator.h(28): error C2220: warning treated as error - no 'object' file generated
2>c:\local\cntk\cntk\source\sgdlib\simpledistgradaggregator.h(28): warning C4100: 'deviceId': unreferenced formal parameter
2>c:\local\cntk\cntk\source\sgdlib\simpledistgradaggregator.h(28): note: while compiling class template member function 'Microsoft::MSR::CNTK::SimpleDistGradAggregator<ElemType>::SimpleDistGradAggregator(const Microsoft::MSR::CNTK::MPIWrapperPtr &,bool,int,int,::size_t)'
2>        with
2>        [
2>            ElemType=double
2>        ]
2>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\include\memory(1712): note: see reference to function template instantiation 'Microsoft::MSR::CNTK::SimpleDistGradAggregator<ElemType>::SimpleDistGradAggregator(const Microsoft::MSR::CNTK::MPIWrapperPtr &,bool,int,int,::size_t)' being compiled
2>        with
2>        [
2>            ElemType=double
2>        ]
2>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\include\type_traits(477): note: see reference to class template instantiation 'Microsoft::MSR::CNTK::SimpleDistGradAggregator<ElemType>' being compiled
2>        with
2>        [
2>            ElemType=double
2>        ]
2>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.11.25503\include\memory(1345): note: see reference to class template instantiation 'std::is_convertible<_Ty2 *,_Ty *>' being compiled
2>        with
2>        [
2>            _Ty2=Microsoft::MSR::CNTK::SimpleDistGradAggregator<double>,
2>            _Ty=Microsoft::MSR::CNTK::IDistGradAggregator<double>
2>        ]
2>c:\local\cntk\cntk\source\sgdlib\simpledistgradaggregatorhelper.cpp(80): note: see reference to function template instantiation 'std::shared_ptr<Microsoft::MSR::CNTK::IDistGradAggregator<double>> Microsoft::MSR::CNTK::GetSimpleDistGradAggregator<double>(const Microsoft::MSR::CNTK::MPIWrapperPtr &,bool,int,int,::size_t,bool)' being compiled
1>GPUMatrix.cu
1>c:\local\cntk\cntk\source\math\CntkBatchNormalization.cuh(49): error C2912: explicit specialization 'void Microsoft::MSR::CNTK::LoadValues<2,float,float>(const float *,float [])' is not a specialization of a function template
1>c:\local\cntk\cntk\source\math\CntkBatchNormalization.cuh(59): error C2912: explicit specialization 'void Microsoft::MSR::CNTK::LoadValues<4,float,float>(const float *,float [])' is not a specialization of a function template
1>c:\local\cntk\cntk\source\math\CntkBatchNormalization.cuh(90): error C2912: explicit specialization 'void Microsoft::MSR::CNTK::StoreValues<2,float,float>(const float [],float *)' is not a specialization of a function template
1>c:\local\cntk\cntk\source\math\CntkBatchNormalization.cuh(101): error C2912: explicit specialization 'void Microsoft::MSR::CNTK::StoreValues<4,float,float>(const float [],float *)' is not a specialization of a function template
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.0.targets(712,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" --use-local-env -Xcompiler /WX -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64" -x cu  -IC:\local\CNTK\CNTK\Source\Common\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -I"C:\local\cub-1.8.0" -I"c:\local\cudnn-10.0-v7.3.1\cuda\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include"   -lineinfo --keep --keep-dir C:\local\CNTK\CNTK\x64\.build\Release\Source\Math\\MathCUDA -maxrregcount=0  --machine 64 --compile -cudart static -Xcudafe "--diag_suppress=field_without_dll_interface" -Xcompiler "/wd 4819"   -use_fast_math -DNO_SYNC -DWIN32 -D_WINDOWS -D_USRDLL -DMATH_EXPORTS -DUSE_CUDNN -D_UNICODE -DUNICODE -DNDEBUG -D"CNTK_VERSION=\"2.7\"" -D"CNTK_VERSION_BANNER=\"2.7+\"" -D"CNTK_COMPONENT_VERSION=\"2.7\"" -DHAS_MPI=1 -DCUDA_NO_HALF -D__CUDA_NO_HALF_OPERATORS__ -Xcompiler "/EHsc /W4 /nologo /O2 /FdC:\local\CNTK\CNTK\x64\.build\Release\Source\Math\\MathCUDA\MathCUDA.pdb /FS /Zi  /MD " -o C:\local\CNTK\CNTK\x64\.build\Release\Source\Math\\MathCUDA\GPUMatrix.cu.obj "C:\local\CNTK\CNTK\Source\Math\GPUMatrix.cu"" exited with code 2.
1>Done building project "MathCUDA.vcxproj" -- FAILED.
3>------ Build started: Project: Math, Configuration: Release x64 ------
2>Done building project "SGDLib.vcxproj" -- FAILED.
3>Cntk.Common-2.7.lib(ExceptionWithCallStack.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
3>LINK : fatal error LNK1104: cannot open file 'Cntk.Math.Cuda-2.7.lib'
3>Done building project "Math.vcxproj" -- FAILED.
4>------ Build started: Project: CNTKv2LibraryDll, Configuration: Release x64 ------
5>------ Build started: Project: LibSVMBinaryReader, Configuration: Release x64 ------
6>------ Build started: Project: BinaryReader, Configuration: Release x64 ------
7>------ Build started: Project: HTKMLFReader, Configuration: Release x64 ------
8>------ Build started: Project: LMSequenceReader, Configuration: Release x64 ------
9>------ Build started: Project: LUSequenceReader, Configuration: Release x64 ------
10>------ Build started: Project: SparsePCReader, Configuration: Release x64 ------
11>------ Build started: Project: UCIFastReader, Configuration: Release x64 ------
8>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
8>Done building project "LMSequenceReader.vcxproj" -- FAILED.
12>------ Build started: Project: CNTKBinaryReader, Configuration: Release x64 ------
10>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
9>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
10>Done building project "SparsePCReader.vcxproj" -- FAILED.
13>------ Build started: Project: CNTKTextFormatReader, Configuration: Release x64 ------
9>Done building project "LUSequenceReader.vcxproj" -- FAILED.
14>------ Build started: Project: HTKDeserializers (Reader Plugins\HTKDeserializers), Configuration: Release x64 ------
5>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
6>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
5>Done building project "LibSVMBinaryReader.vcxproj" -- FAILED.
15>------ Build started: Project: ImageReader, Configuration: Release x64 ------
6>Done building project "BinaryReader.vcxproj" -- FAILED.
16>------ Build started: Project: CompositeDataReader, Configuration: Release x64 ------
7>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
7>Done building project "HTKMLFReader.vcxproj" -- FAILED.
17>------ Build started: Project: MathTests, Configuration: Release x64 ------
12>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
12>Done building project "CNTKBinaryReader.vcxproj" -- FAILED.
18>------ Build started: Project: DSSMReader, Configuration: Release x64 ------
13>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
13>Done building project "CNTKTextFormatReader.vcxproj" -- FAILED.
19>------ Build started: Project: MathPerformanceTests, Configuration: Release x64 ------
16>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
15>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
16>Done building project "CompositeDataReader.vcxproj" -- FAILED.
20>------ Build started: Project: CommandEval, Configuration: Release x64 ------
15>Done building project "ImageReader.vcxproj" -- FAILED.
21>------ Build started: Project: BrainScriptTests, Configuration: Release x64 ------
14>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
14>Done building project "HTKDeserializers.vcxproj" -- FAILED.
18>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
18>Done building project "DSSMReader.vcxproj" -- FAILED.
17>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
17>Done building project "MathTests.vcxproj" -- FAILED.
19>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
19>Done building project "MathPerformanceTests.vcxproj" -- FAILED.
20>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
20>Done building project "CommandEval.vcxproj" -- FAILED.
21>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
21>Done building project "BrainScriptTests.vcxproj" -- FAILED.
11>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
11>Done building project "UCIFastReader.vcxproj" -- FAILED.
22>------ Build started: Project: ReaderTests, Configuration: Release x64 ------
22>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
22>Done building project "ReaderTests.vcxproj" -- FAILED.
4>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
4>Done building project "CNTKv2LibraryDll.vcxproj" -- FAILED.
23>------ Build started: Project: CNTKLibraryCSBinding, Configuration: Release x64 ------
24>------ Build started: Project: CPPExtensibilityExamplesLibrary, Configuration: Release x64 ------
25>------ Skipped Build: Project: ImageRecognizerLib, Configuration: Release_UWP x64 ------
25>Project not selected to build for this solution configuration 
26>------ Build started: Project: CNTKLibraryCPPEvalExamplesTest, Configuration: Release x64 ------
27>------ Build started: Project: V2LibraryEndToEndTests, Configuration: Release x64 ------
28>------ Build started: Project: CPPExtensibilityExamples, Configuration: Release x64 ------
29>------ Build started: Project: CNTKLibraryJavaBinding, Configuration: Release x64 ------
30>------ Build started: Project: EvalDll, Configuration: Release x64 ------
31>------ Build started: Project: CNTK, Configuration: Release x64 ------
29>C:\local\CNTK\CNTK\bindings\java\Swig\CNTKLibraryJavaBinding.vcxproj(136,5): warning : The project requires the Java JDK to be installed. Please see https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Windows#optional-java for installation instructions.
29>Done building project "CNTKLibraryJavaBinding.vcxproj".
32>------ Build started: Project: NetworkTests, Configuration: Release x64 ------
23>LINK : fatal error LNK1181: cannot open input file 'Cntk.Core-2.7.lib'
24>LINK : fatal error LNK1181: cannot open input file 'Cntk.Core-2.7.lib'
23>Done building project "CNTKLibraryCSBinding.vcxproj" -- FAILED.
24>Done building project "CPPExtensibilityExamplesLibrary.vcxproj" -- FAILED.
33>------ Build started: Project: CNTKLibraryManagedDll, Configuration: Release x64 ------
28>LINK : fatal error LNK1181: cannot open input file 'Cntk.Core-2.7.lib'
28>Done building project "CPPExtensibilityExamples.vcxproj" -- FAILED.
30>LINK : fatal error LNK1181: cannot open input file 'Cntk.Math-2.7.lib'
30>Done building project "EvalDll.vcxproj" -- FAILED.
26>LINK : fatal error LNK1181: cannot open input file 'Cntk.Core-2.7.lib'
26>Done building project "CNTKLibraryCPPEvalExamplesTest.vcxproj" -- FAILED.
27>LINK : fatal error LNK1181: cannot open input file 'Cntk.Core-2.7.lib'
27>Done building project "V2LibraryEndToEndTests.vcxproj" -- FAILED.
31>LINK : fatal error LNK1181: cannot open input file 'Cntk.Core-2.7.lib'
31>Done building project "CNTK.vcxproj" -- FAILED.
34>------ Build started: Project: PythonBindings, Configuration: Release x64 ------
35>------ Build started: Project: EvalWrapper, Configuration: Release x64 ------
36>------ Build started: Project: EvalTests, Configuration: Release x64 ------
37>------ Build started: Project: V2LibraryTests (Tests\UnitTests\V2LibraryTests), Configuration: Release x64 ------
38>------ Build started: Project: CPPEvalClientTest, Configuration: Release x64 ------
39>------ Build started: Project: CPPEvalExtendedClientTest, Configuration: Release x64 ------
32>LINK : fatal error LNK1181: cannot open input file 'Cntk.Core-2.7.lib'
32>Done building project "NetworkTests.vcxproj" -- FAILED.
40>------ Skipped Build: Project: CNTKLibraryCPPUWPEvalExamplesTests, Configuration: Release_UWP x64 ------
40>Project not selected to build for this solution configuration 
41>------ Skipped Build: Project: ImageRecognitionAppCS, Configuration: Release_UWP x64 ------
41>Project not selected to build for this solution configuration 
42>------ Build started: Project: ProposalLayerLib, Configuration: Release x64 ------
33>CNTKLibraryManagedDll -> C:\local\CNTK\CNTK\x64\Release\Cntk.Core.Managed-2.7.dll
38>LINK : fatal error LNK1181: cannot open input file 'Cntk.Eval-2.7.lib'
38>Done building project "CPPEvalClientTest.vcxproj" -- FAILED.
39>LINK : fatal error LNK1181: cannot open input file 'Cntk.Eval-2.7.lib'
35>LINK : fatal error LNK1181: cannot open input file 'Cntk.Eval-2.7.lib'
39>Done building project "CPPEvalExtendedClientTest.vcxproj" -- FAILED.
35>Done building project "EvalWrapper.vcxproj" -- FAILED.
43>------ Build started: Project: ManagedEvalTests, Configuration: Release x64 ------
44>------ Build started: Project: CSEvalClientTest, Configuration: Release x64 ------
36>LINK : fatal error LNK1181: cannot open input file 'Cntk.Eval-2.7.lib'
36>Done building project "EvalTests.vcxproj" -- FAILED.
42>LINK : fatal error LNK1181: cannot open input file 'Cntk.Core-2.7.lib'
42>Done building project "ProposalLayerLib.vcxproj" -- FAILED.
37>LINK : fatal error LNK1181: cannot open input file 'Cntk.Core-2.7.lib'
37>Done building project "V2LibraryTests.vcxproj" -- FAILED.
34>**********************************************************************
34>** Visual Studio 2017 Developer Command Prompt v15.9.12
34>** Copyright (c) 2017 Microsoft Corporation
34>**********************************************************************
43>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Cntk.Eval.Wrapper-2.7". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
43>C:\local\CNTK\CNTK\Tests\UnitTests\ManagedEvalTests\EvalManagedTests.cs(467,46,467,68): error CS0246: The type or namespace name 'IEvaluateModelManagedF' could not be found (are you missing a using directive or an assembly reference?)
44>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Cntk.Eval.Wrapper-2.7". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
44>C:\local\CNTK\CNTK\Examples\Evaluation\LegacyEvalDll\CSEvalClient\Program.cs(147,45,147,58): error CS0246: The type or namespace name 'CNTKException' could not be found (are you missing a using directive or an assembly reference?)
44>C:\local\CNTK\CNTK\Examples\Evaluation\LegacyEvalDll\CSEvalClient\ModelEvaluator.cs(34,26,34,48): error CS0246: The type or namespace name 'IEvaluateModelManagedF' could not be found (are you missing a using directive or an assembly reference?)
45>------ Build started: Project: V2LibraryCSTests, Configuration: Release x64 ------
46>------ Build started: Project: CNTKLibraryCSTrainingTest, Configuration: Release x64 ------
47>------ Build started: Project: CNTKLibraryCSEvalExamplesTest, Configuration: Release x64 ------
45>V2LibraryCSTests -> C:\local\CNTK\CNTK\x64\Release\V2LibraryCSTests.dll
46>CNTKLibraryCSTrainingTest -> C:\local\CNTK\CNTK\x64\Release\CNTKLibraryCSTrainingTest.dll
47>CNTKLibraryCSEvalExamplesTest -> C:\local\CNTK\CNTK\x64\Release\CNTKLibraryCSEvalExamplesTest.dll
34>[vcvarsall.bat] Environment initialized for: 'x64'
34>Building for Python version '27', extra path is C:\local\Anaconda3-4.1.1\envs\cntk-py27
34>Using CNTK sources at 'C:\local\CNTK\CNTK\Source'
34>Using CNTK libs at 'C:\local\CNTK\CNTK\x64\Release'
34>Traceback (most recent call last):
34>  File ".\setup.py", line 184, in <module>
34>    shutil.copy(src_file, tgt_file)
34>  File "C:\local\Anaconda3-4.1.1\envs\cntk-py27\lib\shutil.py", line 119, in copy
34>    copyfile(src, dst)
34>  File "C:\local\Anaconda3-4.1.1\envs\cntk-py27\lib\shutil.py", line 82, in copyfile
34>    with open(src, 'rb') as fsrc:
34>IOError: [Errno 2] No such file or directory: 'C:\\local\\CNTK\\CNTK\\x64\\Release\\Cntk.Composite-2.7.dll'
34>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command ".\vsbuild.bat "C:\local\CNTK\CNTK\x64\Release\" "false" "true" "2.7" "2.7+" "2.7" "C:\local\swigwin-3.0.10" "false" "" "C:\local\Anaconda3-4.1.1\envs\cntk-py27" "" "C:\local\Anaconda3-4.1.1\envs\cntk-py35" "C:\local\Anaconda3-4.1.1\envs\cntk-py36"" exited with code 1.
34>Done building project "PythonBindings.vcxproj" -- FAILED.
========== Build: 5 succeeded, 39 failed, 12 up-to-date, 3 skipped ==========
```

**Comment by haryngod** [comment]
I have the same problem. Did you solve this?

**Comment by IvanFarkas** [comment]
I'll wait till they get **serious** about helping developers.

**Comment by delzac** [comment]
@IvanFarkas The maintainers have moved on already. No point griping about it.

**Comment by haryngod** [comment]
@IvanFarkas  What's your mean? Do they stop to maintain?

**Comment by thiagocrepaldi** [comment]
With a brand new machine, I have installed visual studio 2017 professional + cuda 10.0 (in this order), git and git and have followed https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-with-script-on-Windows and https://docs.microsoft.com/en-us/cognitive-toolkit/setup-cntk-on-windows#building-cntk and it worked. The only change that I needed to do was removing pyqt from the yaml files that create conda environments.

You build looks incomplete. Try deleting C:\local\CNTK\CNTK\x64 and build again. Remember cntk.sln must be open from an activated conda environment

**Comment by delzac** [comment]
@thiagocrepaldi Thanks for the reply, it was really helpful!! :)

**Comment by IvanFarkas** [comment]
Thx @thiagocrepaldi. I'll try it over the weekend.
