### ISSUE TITLE
Onnx export fails resnet50 Brainscript CrossEntropyWithSoftmax Unsupported node

### ISSUE THREAD

**Issue by pmfcdb** [microsoft/CNTK#3676]
Using cntk 2.7, pyhton 3.5

I tried to export a model that I trained with Brainscript (ResNet50_ImageNet1K.cntk) to ONNX with this code:

import cntk as C
model_path = "ResNet_50_train_CNTK.model"
z = C.Function.load(model_path, device=C.device.cpu())
z.save("ResNet_50_train_CNTK.onnx", format=C.ModelFormat.ONNX)

When I try to do this, I get the following RuntimeError:

About to throw exception 'Node 'CrossEntropyWithSoftmax: Output('z', [#, ], [2]), Input('labels', [#, ], [2]) -> Output('ce', [], [])': Unsupported node.'
Traceback (most recent call last):
  File "onnx_export.py", line 7, in <module>
    z.save("ResNet_50_CNTK.onnx", format=C.ModelFormat.ONNX)
  File "C:\Anaconda3\envs\CNTK_2_7\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Anaconda3\envs\CNTK_2_7\lib\site-packages\cntk\ops\functions.py", line 1559, in save
    return super(Function, self).save(filename, format.value, use_external_files_to_store_parameters)
  File "C:\Anaconda3\envs\CNTK_2_7\lib\site-packages\cntk\cntk_py.py", line 2082, in save
    return _cntk_py.Function_save(self, *args)
RuntimeError: Node 'CrossEntropyWithSoftmax: Output('z', [#, ], [2]), Input('labels', [#, ], [2]) -> Output('ce', [], [])': Unsupported node.

[CALL STACK]
    > std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  weak_from_this
    - CNTK::  XavierInitializer (x5)
    - CNTK::Function::  Save
    - PyInit__cntk_py (x2)
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)
    - PyEval_GetFuncDesc (x2)
    - PyEval_EvalFrameEx

**Comment by delzac** [comment]
You can not suppose to export cross entropy with softmax, that's a loss function.

When you are saving your model, save only your network outputs (i.e. everything before cross entropy with softmax)

**Comment by pmfcdb** [comment]
Ok, but how to do this in Brainscript?
 I'm using Brainscript (ResNet50_ImageNet1K.cntk) to train and generate the model.
PB

**Comment by delzac** [comment]
Sorry, i don't use brainscript so i can only offer a python equivalent code, hope it helps.

    a = C.input_variables((3, 224, 224))
    prediction = model(a)
    
    loss = C.cross_entropy_with_softmax(prediction, ground_truth_tensor)
    
    prediction.save(YOUR_FILEPATH)  # this is correct
    loss.save(...)  # this is wrong, and this is what you are doing

**Comment by JohnCraigPublic** [comment]
delzac - I have the same issue as pmfcdb.  This is very inconvenient.  Might it be the case that in a future ONNX they will add the ability to represent a SoftMax output?   Let's say it took me 5 days of crunching on my GPU to save my model in CNTK.  I only saved the model I would need at runtime, which includes SoftMax output.   Now, to move to ONNX, I have to re-compute (spend 5 days) the model and be sure to leave off the SoftMax?  I thought ONNX was our savior -- but you are saying that no existing classification network (they all end in SoftMax) can actually be output in ONNX format?  Yikes.

**Comment by delzac** [comment]
@JohnCraigPublic Its perfectly fine to save with Softmax Node, but what we are talking about is cross_entropy_with_softmax, that is a loss function that takes in 2 arguments, (1) network output (2) ground truth. I don't think you would have ground truth during inference right?

Just remove the cross_entropy_with_softmax node in your cntk model file (and add a softmax node if you like) and resave it as onnx and you are done.

**Comment by JohnCraigPublic** [comment]
There is a way to “remove the cross entropy with softmax node” from my existing CNTK model, without re computing the whole thing?

**Comment by delzac** [comment]
Of course! Load the model into cntk. Use C.logging.find_all_by_name(model, '') and you will get a list of all the nodes inside your model. Select the node that you want, do a C.combine([selected_node.owner]).

You can use this [transfer learning](https://github.com/microsoft/CNTK/blob/master/Examples/Image/TransferLearning/TransferLearning.py#L80) example as reference.

**Comment by JohnCraigPublic** [comment]
delzac - I might just need a bit more help.....   is this do-able from C++ rather than Python?

**Comment by delzac** [comment]
Yes, it can be done on C++ too. But i can't help you there since i don't use C++. The basic principle is the same, just select and save the network graphs before your cross_entropy_with_softmax node.

**Comment by pmfcdb** [comment]
Hi, I'm trying do convert the model saved in Brainscript without the cross_entropy_with_softmax. I'm using  the transfer learning example as reference as you said. The model input is a image 224x224x3 and the output is 0 or 1.

Can I use this code?
import cntk as C
from cntk.ops import combine, softmax
from cntk.logging.graph import find_by_name, get_node_outputs
from cntk.ops.functions import CloneMethod
from cntk import load_model, placeholder, Constant
from cntk.layers import Dense

_base_model_file = "ResNet_50.model"
_feature_node_name = "features"
_last_hidden_node_name = "z.x"
_image_height = 224
_image_width = 224
_num_channels = 3
new_output_node_name = "prediction"
freeze = False

input_features = C.input_variable((_num_channels, _image_height, _image_width))
base_model   = C.load_model(_base_model_file)
feature_node = find_by_name(base_model, _feature_node_name)
last_node    = find_by_name(base_model, _last_hidden_node_name)

##Clone the desired layers with fixed weights
cloned_layers = combine([last_node.owner]).clone(CloneMethod.freeze if freeze else CloneMethod.clone, {feature_node: placeholder(name='features')})

##Add new dense layer for class prediction
feat_norm  = input_features 
cloned_out = cloned_layers(feat_norm)
z          = Dense(2, activation=None, name=new_output_node_name) (cloned_out)
z.save("ResNet_50_CNTK.onnx", format=C.ModelFormat.ONNX)

**Comment by delzac** [comment]
It looks good. But why do you need to add another Dense layer at the end? You just need to remove the cross_entropy_softmax node, thats all. So you can stop at `cloned_layers = combine([last_node.owner])`

**Comment by JohnCraigPublic** [comment]
Similar to how pmfcdb added a Dense layer to his model before saving, I wanted to add a softmax to my model before saving.  But in all the CNTK doc on the Layer library, there is no mention of a softmax layer.  So how does one do it?   Or, is it the convention to compute the Softmax outside of the model inference?   If that's more typical, I wonder why - why not have the softmax be part of the model?

**Comment by JohnCraigPublic** [comment]
another question.  This python code is basically working, but I have 2 questions related:

base_model_filepath = "/home/john/CNTK/Model.model"
input_features = C.input_variable((1, 299, 299), name = "features")
base_model = C.load_model(base_model_filepath)
feature_node = find_by_name(base_model, "features")
last_node = find_by_name(base_model, "z")
cloned_layers = combine([last_node.owner]).clone(CloneMethod.clone, {feature_node: placeholder(name='features')})
cloned_out = cloned_layers(input_features)
cloned_out.save("/home/john/CNTK/Model.onnx", format=C.ModelFormat.ONNX)

The 2 questions come from looking at the resulting ONNX model using Netron:
1) In the resulting model the output node is called "z_Output" -- why?  I expected and wanted "z"
2) Netron shows the shape of the input as [1, 1, 299, 299] -- why?  I expected [1,299,299] or [299,299,1]  as it was in my original CNTK model.

**Comment by delzac** [comment]
@JohnCraigPublic softmax is a function and not a layer. You can get it with `C.softmax()`. By convention, in all deep learning framworks, cross_entropy will come with a convenience softmax function. I'm not sure why there's such a convention too.

Typically i'll use numpy to calculate softmax from the output of the model inference (where the last layer is a linear Dense layer).

As for your question on ONNX and Netron. When you save the model into ONNX, cntk's dynamic batch axis because an explicit static batch axis, which is why you see an extra singleton axis.

When you name your layer as 'z', you can refer to it like this `base_model.z` and get its weights like this `base_model.z.W` or `base_model.z.b` depending on how to name your Parameter inside the layer.

How did you get "z_Output", i can't seem to get it.
