### ISSUE TITLE
Import Error when install .whl generated from source code：what is '_cntk_py '?

### ISSUE THREAD

**Issue by NKCSRzChen** [microsoft/CNTK#3773]
Hello!
Env description: 
  Ubuntu 16.04 
  CUDA: 9.1 CUDNN:7.0
  pip version 19.3.1 python version 3.5.2
  cntk version:2.6/2.5/2.3
Issue:
  I use the following configure:
  ../../configure --cuda=yes --python=yes --with-cuda=/usr/local/cuda-9.1 --with-py-versions=35 --with-py35-path=/usr --with-mkl=/usr/local/mklml/mklml_lnx_2018.0.3.20180406 --with mkl-sequential=/usr/local/mklml/mklml_lnx_2018.0.3.20180406 --with-opencv=/usr --with-libzip=/usr --with-boost=/usr/local/boost-1.60.0 with-build-version=2.3
  And I got the cntk_gpu-2.3-cp35-cp35m-linux_x86_64.whl successfully.
  Then, I use pip to install cntk-gpu,  successully!
  However, when I want to try with python examples.
  python throw the following error:
  Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cntk
/usr/local/lib/python3.5/dist-packages/cntk/cntk_py_init.py:90: UserWarning: 

################################################ Missing optional dependency (    MKL     ) ################################################
   CNTK may crash if the component that depends on those dependencies is loaded.
   Visit https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Linux-Python#mkl for more information.
############################################################################################################################################

  warnings.warn(WARNING_MSG % ('    MKL     ', 'https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Linux-Python#mkl'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/cntk/__init__.py", line 27, in <module>
    from . import cntk_py
  File "/usr/local/lib/python3.5/dist-packages/cntk/cntk_py.py", line 13, in <module>
    from . import _cntk_py
ImportError: cannot import name '_cntk_py'

Any idea?

**Comment by delzac** [comment]
Which cntk version are you using? This only happens in the old cntk version and it has to do with pathing. Adding the right paths into your environmental variables would solve it. I believe there a few issues that deal with this, a search would find it.

Alternatively, i suggest you upgrade to the latest cntk as it has onnx support.

**Comment by NKCSRzChen** [comment]
Thanks for your  reply @delzac , I tried cntk2.6-gpu and cntk2.3-gpu while the same error occurs. 
Do you have any suggestion for setting the environmental variables? My envirmental variables in ~/.bashrc looks as follows:

"export PATH=/home/cntk/cntk/build/release/bin:$PATH
export PYTHONPATH=/usr/local/lib/python3.5/dist-packages:$PYTHONPATH"
Should I add any other paths?

**Comment by delzac** [comment]
Can you take a look at there closed [issues](https://github.com/microsoft/CNTK/issues?q=is%3Aissue+ImportError%3A+cannot+import+name+%27_cntk_py%27+is%3Aclosed) over here and see if it helps? There a lot of resource here. One of the reason might be some previously installed anaconda3 creating issues.

If it doesn't work let us know again.

**Comment by NKCSRzChen** [comment]
Yes, I think it is the path problem, when I copy 
![image](https://user-images.githubusercontent.com/44854448/68994483-6afd1200-08be-11ea-93c0-816fd5310896.png)
to
![image](https://user-images.githubusercontent.com/44854448/68994486-718b8980-08be-11ea-82dd-c2700218d7dc.png)

it works! thank you so much @delzac
