### ISSUE TITLE
Error running run_faster_rcnn.py

### ISSUE THREAD

**Issue by Annakj97** [microsoft/CNTK#3775]
- I tried to run the first Example on: https://github.com/microsoft/CNTK/tree/master/Examples/Image/Detection/FasterRCNN
- everything worked until i tried 'python run_faster_rcnn.py'
- Im working in a Ubuntu 18.04 virtuel machine (VMware)
- The CNTK enviroment was created like this: https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Linux-Python?tabs=cntkpy27
- MPI was installed with this command: sudo apt-get install openmpi-bin
- Any idea what went wrong?

### The Errormessage:
Traceback (most recent call last):
  File "run_faster_rcnn.py", line 9, in <module>
    import cntk
  File "/home/anna/.local/lib/python2.7/site-packages/cntk/__init__.py", line 27, in <module>
    from . import cntk_py
  File "/home/anna/.local/lib/python2.7/site-packages/cntk/cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "/home/anna/.local/lib/python2.7/site-packages/cntk/cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: libmpi_cxx.so.1: cannot open shared object file: No such file or directory

**Comment by haixpham** [comment]
OpenMPI 1.10 is expected. Apt-get may install v2.0, you should check it to make sure

**Comment by Annakj97** [comment]
Hi, thanks for the answer. I had v2.0 installed. Now I installed 1.10 like this: http://butka.me/linux/how-to-install-openmpi-on-ubuntu-14-04/
But again I have the exact same Errormessage.

**Comment by haixpham** [comment]
You have to add the path to libmpi in PATH or LD_LIBRARY_PATH in ./bashrc

**Comment by jieunko** [comment]
however, why would you run it in ubuntu when CNTK run perfectly fine in window..?
