### ISSUE TITLE
Errors when run the example code of "LSTM-based sequence classification"

### ISSUE THREAD

**Issue by hongjiedai** [Microsoft/CNTK#543]
Here is the error message I got:
# 

Traceback (most recent call last):
  File "seqcla.py", line 185, in <module>
    seqcla()
  File "seqcla.py", line 117, in seqcla
    L = lstm_layer(output_dim, cell_dim, sequence, input_dim)
  File "seqcla.py", line 44, in lstm_layer
    return Last(lstm_state_h)
  File "seqcla.py", line 32, in **init**
    self.rank = x.rank
AttributeError: 'ElementTimes' object has no attribute 'rank'
# 

I try to remove the statement     self.rank = x.rank.
But have another error:
# 

Traceback (most recent call last):
  File "seqcla2.py", line 185, in <module>
    seqcla()
  File "seqcla2.py", line 138, in seqcla
    labels, alias='y', dim=num_labels, format='Dense'))
  File "D:\Libraries\Anaconda2\lib\site-packages\cntk\context.py", line 654, in
train
    action_name = action_name)
  File "D:\Libraries\Anaconda2\lib\site-packages\cntk\context.py", line 394, in
_call_cntk
    stderr=subprocess.STDOUT)
  File "D:\Libraries\Anaconda2\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, _popenargs, *_kwargs)
  File "D:\Libraries\Anaconda2\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "D:\Libraries\Anaconda2\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 5] Access is denied
# 

How can I fix the above errors?

**Comment by hongjiedai** [comment]
I observed that it is due to my error setting for "CNTK_EXECUTABLE_PATH".
I only set it to the folder containing the executable file.

It now has another error:

nicodeEncodeError: 'ascii' codec can't encode characters in position 20740-2075
: ordinal not in range(128)

Try to figure out the reason why.

**Comment by mahilleb-msft** [comment]
Hi - this samples was still based on our old Python API published with CNTK v1.5, which has since been replaced by a full-featured Python API for CNTK 2.0. Unfortunately we don't ship nor support the old Python API anymore. Please checkout https://docs.microsoft.com/en-us/cognitive-toolkit/ and https://www.microsoft.com/en-us/cognitive-toolkit/features/model-gallery/ for documentation on CNTK 2.0 and samples. If you run into any problems, please open a new issue.
Best, Mark
