### ISSUE TITLE
CNTK Cpu Eval Doesn't Load Model

### ISSUE THREAD

**Issue by michael-golfi** [Microsoft/CNTK#618]
Hi,

I tried using Microsoft.Research.CNTK.CpuEval-acml version 1.5 EvalWrapper on nuget and it fails to load the model path I give it. I had to revert to a version 1.4 dll for it to work. 

When I execute:

``` csharp
        var model = Helpers.LoadModel(ModelPath, OutputLayerName);
        var pixelMeans = new float[Channels * ImageSize * ImageSize];
        var inputLayerName = GetFirstInputLayer(model);
        ...
        public static string GetFirstInputLayer(IEvaluateModelManagedF model)
        {
            var inDims = model.GetNodeDimensions(NodeGroup.nodeInput);
            return inDims.First().Key;
        }
```

I get the following exception:

``` csharp
An unhandled exception of type 'System.AccessViolationException' occurred in EvalWrapper.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

The same exact code works with version 1.4 of the dll. The exception is thrown on GetNodeDimensions. It seems like the model isn't loaded into memory properly.

**Comment by gaizkan** [comment]
Michael,
Are you still experiencing this exception in 1.5?
The modelPath property should be specified similarly to the following:

    string modelFilePath = @"C:\CNTK\Models\ResNet_18.model";
    model.CreateNetwork(string.Format("modelPath=\"{0}\"", modelFilePath), deviceId: -1);

Let me know.

Thanks,
Gaizka

**Comment by KolyaIvankov** [comment]
If the issue is still open: I am experiencing this problem right now. 

I have Visual Studio 2015 on Windows 10, the CNTK V 2.0 Beta-5 installed on my machine, use the latest stable NuGet package (1.7.3), but have also tried 2.0.0beta-5.

Right now I am trying to use model.CreateNetwork both by specifying modelFilePath as well as using the test description form this [example](https://github.com/Microsoft/CNTK/wiki/Nuget-Package-for-Evaluation). And still detting this exception.

What may I possibly do wrong. 

Thanks in advance,

Kolya

**Comment by zhouwangzw** [comment]
@KolyaIvankov  The current Nuget Package as well as the examples only works with CPU only device, as described in the [Wiki page ](https://github.com/Microsoft/CNTK/wiki/NuGet-Package#current-release). Could you please try to download the CPU binary drop and try to run the [CSEvalClient](https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CSEvalClient/CSEvalClient.csproj) project in[ examples](https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/EvalClients.sln)? And let me know if you have problems.

**Comment by KolyaIvankov** [comment]
@zhouwangzw Thanks for help. I've been thinking that training a CPU only model (with deviceId=-1 in the description) will suffice. However, the problem persists.

I have set up a CPU version of CNTK V2.0 Beta-5 on my machine (verified this by running examples with deviceId=auto and getting it run on CPU), upgraded my VS 2013 to Update 5 version and was able to run the CSEvalClient project on 01_OheHidden and 02_OneConv examples (commented out the rest to save time on building networks).

Then, I have reinstalled the CNTK beta5 NuGet package, attaching to the startup project in my solution, and tried to load model from the aforementioned example. Still getting the same exception.

I am using a VS 15 Community right now, so I guess I won't be able to debug and see what's happening in the CNTK code.

**Comment by zhouwangzw** [comment]
@KolyaIvankov  Have you trained your model using Python or BrainScript? If you were training the model using Python, it is not supported to load the model by using EvalBase interface in the Nuget Package. You may try with the EvalExtended interface there, as describe in #1050. We are currently working on C# Eval V2 API which supports evaluation of Python models. The new API will be available soon.
Sorry for the inconvenience and stay tuned for the new API.
Thanks.

**Comment by KolyaIvankov** [comment]
@zhouwangzw  I've been using BrainScript. 

But, as I have mentioned above, the same problem also occurs in VS 2015 in the example with the single-node model defined manually as a string:

`                string modelDefinition = @"precision = ""float""  
                                    traceLevel = 1 
                                    run=NDLNetworkBuilder
                                    NDLNetworkBuilder=[ 
                                    i1 = Input(1)
                                    o1 = Times(Constant(3), i1, tag=""output"") 
                                    FeatureNodes = (i1)
                                    ]";
`
and then applying:

`model.CreateNetwork(modelDefinition, deviceId: -1);`

I wish I could have helped figuring out the exact place where the bug occurs, but currently I lack means for that. As far as I can figure out, the problem seems to occur only in VS 2015 for now. 

Thank you very much for support!

**Comment by zhouwangzw** [comment]
@KolyaIvankov I tried with VS2015 using Nuget Package. Both CSEvalClient.sln as well as the single-node model definition you provide worked without problem. One thing you may want to pay attention to is that each config/setting in the model definition should be a separate line, like below: 
```
string modelDefinition = @"precision = ""float"" 
                                         traceLevel = 1 
                                         run=NDLNetworkBuilder
                                          NDLNetworkBuilder=[
                                           i1 = Input(1) 
                                           o1 = Times(Constant(3), i1, tag=""output"") 
                                           FeatureNodes = (i1)
                                            ]";
```
If you still have problem, could you please share the exception message you get?

Thanks,

**Comment by KolyaIvankov** [comment]
@zhouwangzw Ok, it seems that I have ignored the notice that the package works only with the projects aimed for x64 processors. After changing from Any CPU to x64 I don't have this issue any more. 

Thanks for patience!

**Comment by zhouwangzw** [comment]
@KolyaIvankov Glad to know that you found the cause. Yes, CNTK has to work on the X64 platform. 
I am closing the issue and feel free to reopen it if needed.

**Comment by pythonMasters** [comment]
I am trying CNTK Language example and able to run the windows application. But when i try to run through a web application in VS2015 and i am getting the below error.

   at CNTK.CNTKLibPINVOKE.Function_LoadModel__SWIG_0(String jarg1, HandleRef jarg2)
   at CNTK.Function.LoadModel(String modelFile, DeviceDescriptor computeDevice)
   at CNTKLibraryCSEvalExamples.CNTKLibraryManagedExamples.EvaluationSingleSequenceUsingOneHot(String input) in C:\Proj\Evaluation\CNTKLibraryCSEvalCPUOnlyExamples\CNTKLibraryCSEvalExamples.cs:line 345

can you please help to resolve this issue.

**Comment by zhouwangzw** [comment]
@pythonMasters The error looks like that some depenent dlls cannot be found by the Web application. Have you set the PATH in your web application, as described [here](https://github.com/Microsoft/CNTK/wiki/Evaluate-a-model-in-an-Azure-WebApi)? The page describes the usage of EvalDll in web application. The dlls are different for CNTKLibrary SDK, but the principle is the same. We will update the sample and page to use the CNTKLibrary SDK soon.

**Comment by pythonMasters** [comment]
Thanks this solution worked.

**Comment by shantha-Ekanayake** [comment]
@zhouwangzw, I am facing similar issue when i publish the application to windows 2012 R2 virtual server. In VS 2015 development mode application running perfectly with the global.asax correction, i have verified the global.asax and path correction also available after publishing to the server. what could be the issue ? I know this is related to path issue but all possible things that i am able to find i have tried but no luck.

**Comment by zhouwangzw** [comment]
CNTK requires 64-bit support, so the process hosting CNTK library should run in 64-bit mode.

**Comment by shantha-Ekanayake** [comment]
I have IIS 8.5 and default mode is 64 bit unless we tick the option to run in 32 bit mode. Is this the process what you have mentioned or some other process such worker process ? how do we make worker process to be run in 64bit and how do we check what is the current setting ?

**Comment by zhouwangzw** [comment]
You may want ot check IIS Manager -> Advanced Settings or C:\Windows\System32\inetsrv\config\applicationHost.config to ensure that IIS is in 64-bit mode. In addtion, please 
set the PATH in your web application, as described here. (The page describes the usage of EvalDll in web application. The dlls are different for CNTKLibrary SDK, but the principle is the same. We will update the sample and page to use the CNTKLibrary SDK soon).

**Comment by shantha-Ekanayake** [comment]
Thanks for the information above,

Above problem got resolved after copying all the CNTK files into /bin folder of the web site and i had different versions in my laptop and web server. Both this actions solved the above issue and it's nothing to do with 64 bit since it was already on 64 bit environment (IIS and build)

But have a different problem now.

System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at CNTK.UtilsPINVOKE.Function_LoadModel__SWIG_0(String jarg1, HandleRef jarg2)
   at CNTK.Function.LoadModel(String modelFile, DeviceDescriptor computeDevice)
   at WebApplication1.Default.EvaluationSingleSequenceUsingOneHot(String input)

It's giving this error now. Could you please help me resolving this issue.

**Comment by zhouwangzw** [comment]
@shantha-Ekanayake The error is most likely related to dependent native dlls that cannot be found. Have you updated the PATH to include the bin folder as described in the page https://github.com/Microsoft/CNTK/wiki/Evaluate-a-model-in-an-Azure-WebApi#lets-get-started:
 ◦The directory of the created binaries in our solution needs to get added to the  PATH  environment of the application. This is required since our project includes native DLLs, and those are only loaded if they are reachable in the standard search path. We added the following code in the  Application_Start()  method in  global.asax :
   string pathValue = Environment.GetEnvironmentVariable("PATH");
   string domainBaseDir = AppDomain.CurrentDomain.BaseDirectory;
   string cntkPath = domainBaseDir + @"bin\";
   pathValue += ";" + cntkPath;
   Environment.SetEnvironmentVariable("PATH", pathValue);

Thanks,
Zhou

**Comment by shantha-Ekanayake** [comment]
Thanks Zhou,
Path changes are already there in the global.asax file, Is the something to do with some version issue, same code is running in my visual studio debug mode without any error.

**Comment by zhouwangzw** [comment]
@shantha-Ekanayake Which CNTK version are you using? And could you please give me a list of files available in the /bin folder?

**Comment by shantha-Ekanayake** [comment]
![image](https://cloud.githubusercontent.com/assets/24494504/26241533/0c462de2-3c96-11e7-9bc2-2998c921cfff.png)
![image](https://cloud.githubusercontent.com/assets/24494504/26241619/5a89df08-3c96-11e7-8bef-a507a402bd9c.png)
![image](https://cloud.githubusercontent.com/assets/24494504/26241675/9c208318-3c96-11e7-8223-6ec211ebfa20.png)

Hi These are the files i have in my bin directory and i am using the 2.0 RC1 version in the web server and IIS 8.5 windows 2012 R2

**Comment by zhouwangzw** [comment]
@shantha-Ekanayake From the list, it seems that all files are available. Is Visual C++ Redistributable Package for Visual Studio 2015 also installed on the target machine?

**Comment by shantha-Ekanayake** [comment]
Yes, that is already there and i can run this application in Visual Studio without any issue in my local machine in IIS express.

**Comment by zhouwangzw** [comment]
@shantha-Ekanayake hmm. I believe that the problem is in loading native dlls. Would you please have the following check: 1) Print the PATH environment variable before calling Function.LoadModel(), e.g. 
     ```
string pathValue = Environment.GetEnvironmentVariable("PATH");
     Console.WriteLine("The PATH is " + pathValue);
```
2) Are the following files available in WS2012 RC2: vcruntime140.dll, msvcp140.dll? Usually they are in windows\system32.
3) Could you please use depends.exe to see whehter all dependenies of Cntk.Core.CSBinding-2.0rc1.dll are available? 

Thanks,

**Comment by muthukum** [comment]
Hi i have recently moved to latest cntk.core.managed-2.0 now i am getting the below error even in console application. I have created new project as well still the same.

CNTKLibraryManagedExamples.EvaluationSingleSequenceUsingOneHot(DeviceDescriptor.CPUDevice);

{"The type initializer for 'CNTK.CNTKLibPINVOKE' threw an exception."}

Inner Exception : {"Unable to load DLL 'Cntk.Core.CSBinding-2.0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}

**Comment by zhouwangzw** [comment]
@muthukum Were you using Nuget package to build your application? What is your Visual Studio version? VS2015 is required. 

Can you build and run the examples under Examples\Evaluation\CNTKLibraryEvalExamples.sln included in the 2.0 release package https://github.com/Microsoft/CNTK/releases/tag/v2.0? You can find information to run examples [here](https://docs.microsoft.com/en-us/cognitive-toolkit/CNTK-Eval-Examples#cntk-library-eval-cc-examples).
 
The error is because Cntk.Core.CSBinding-2.0.dll cannot be found or loaded. Is this dll and other CNTK dependent Dlls available in the output directory?

Thanks,

**Comment by muthukum** [comment]
Thanks zhouwangzw I have resolved the issue after comparing with the sample example given above. The issue is due to the below dll it was with extra character "d" in Cntk.Core.CSBinding-2.0d.dll after removing it started working fine.

**Comment by zhouwangzw** [comment]
@muthukum The 'd' in the dll name indicates that this dll is a debug build. The release build does not have 'd' in the name. So please use the same build flavor (either debug or release) for all dlls, otherwise you might see unexpected behavior.
Thanks,

**Comment by xgirones** [comment]
Is it possible to use the release build of the C++ CNTK evaluator in a debug configuration?  I would like to debug my project, but employ the release version of CNTK for the sake of speed.

**Comment by zhouwangzw** [comment]
@xgirones No, it is not correct to use the C++ release build in a debug configuration. You have to use release vs release, debug vs debug. For debug purpose, you can build your project using release configuration but turnning off optimization.

**Comment by xgirones** [comment]
Thanks. I will try it. Just curious, what is the reason for the incompatibility? The CRT maybe?

**Comment by zhouwangzw** [comment]
The CNTK C++ API is using STL which has undefined bahavior when mixing debug and release builds.

**Comment by xgirones** [comment]
Does this imply that there will be compatibility issues if I switch to another version of Visual Studio?

**Comment by zhouwangzw** [comment]
Usually yes, except both VS versions are binary compatible.

**Comment by xgirones** [comment]
I tried CNTK and I think it is a great product. However, in my opinion this limitation is an obstacle for most commercial projects willing to integrate CNTK. And what will happen when future versions of CNTK migrate to VS 2017? Projects integrating CNTK will be forced to migrate as well, which is not always feasible. 

Have you considered removing all external dependencies with STL and the runtime from the dll interface and make it self-contained?  The CNTK dll could export a single function that would return a pointer to a CNTK engine object declared as an abstract interface, which would act as a class factory. All classes declared in _CNTKLibrary.h_ would  be abstract, deriving from a base interface implementing reference counting (like _IUnknown_ in COM), and not depend on STL.

**Comment by zhouwangzw** [comment]
I fully understand it is not always easy/feasible to update your applications to the newest VS version. As STL is heavily used in the current API, I do not think that removing STL from API might happen in short term. But I will pass the message to the team for consideration. Actually, besides STL, we have also other external dependencies, e.g. Cuda/Cudnn, which are also bound to a particular VS version. 
If you cannot migrate all your projects to the lastest VS version, a workaround is to build an ABI compatible wrapper or a kind of IPC mechanism for your projects to interact with CNTK. In this case, you only need to rebuild a small part of your projects on the new VS version. It is not the ideal solution, but might help.

**Comment by xgirones** [comment]
Thanks for your answer. I have already considered writing a wrapper DLL for CNTK,  but as any non trivial project integrating CNTK will face this problem providing an across compiler compatible interface should be a priority.

Another point that I think would increase the popularity of CNTK would be enabling the OpenCV DNN module to load and evaluate CNTK models. They already support Caffe, Torch and TensorFlow:

[https://github.com/opencv/opencv/wiki/Deep-Learning-in-OpenCV](https://github.com/opencv/opencv/wiki/Deep-Learning-in-OpenCV)

This would solve my problem as I am already an OpenCV user. I queried the OpenCV support group about this possibility but they have not provided an answer so far.
