### ISSUE TITLE
core dump with simple2d example

### ISSUE THREAD

**Issue by fancyerii** [Microsoft/CNTK#880]
I installed open-mpi-2.0.1(document say using 1.10 later) in ubuntu 14.04 and run
~/cntk/Examples/Other/Simple2d/Data$ cntk configFile=../Config/Simple.cntk
it cause core dump.
And I use gdb to print full stack:
#0  0x00007ffff4b7c620 in mca_memory_linux_component () from /usr/lib/libmpi.so.1

No symbol table info available.
#1  0x00007ffff62cd7cd in ptmalloc_init () at arena.c:463

```
    di = {dli_fname = 0x7ffff7fd5ea0 "/lib/x86_64-linux-gnu/libc.so.6", dli_fbase = 0x7ffff624a000, dli_sname = 0x0, dli_saddr = 0x0}
    l = 0x7ffff7fd4000
    s = <optimized out>
    hook = <optimized out>
```
#2  0x00007ffff62cdb2e in ptmalloc_init () at hooks.c:29

No locals.
#3  malloc_hook_ini (sz=568, caller=<optimized out>) at hooks.c:31

No locals.
#4  0x00007ffff62b837d in __fopen_internal (filename=0x7ffff364287a "/proc/self/status", mode=0x7ffff3642864 "r", is32=1) at iofopen.c:73

```
    new_f = <optimized out>
```
#5  0x00007ffff363e108 in ?? () from /usr/lib/x86_64-linux-gnu/libnuma.so.1

No symbol table info available.
#6  0x00007ffff7dea0cd in call_init (l=0x7ffff7fd0000, argc=argc@entry=1, argv=argv@entry=0x7fffffffd788, env=env@entry=0x7fffffffd798)

```
at dl-init.c:64
    init_array = <optimized out>
```
#7  0x00007ffff7dea1f3 in call_init (env=<optimized out>, argv=<optimized out>, argc=<optimized out>, l=<optimized out>) at dl-init.c:36

No locals.
#8  _dl_init (main_map=0x7ffff7ffe1c8, argc=1, argv=0x7fffffffd788, env=0x7fffffffd798) at dl-init.c:126

```
    preinit_array = <optimized out>
    preinit_array_size = <optimized out>
    i = 18
```
#9  0x00007ffff7ddb30a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2

```
    _dl_rtld_libname2 = {name = 0x0, next = 0x0, dont_free = 0}
    start_time = 1285721232847
    _dl_rtld_libname = {name = 0x400238 "/lib64/ld-linux-x86-64.so.2", next = 0x7ffff7ffe010 <newname>, dont_free = 0}
    library_path = 0x7fffffffdd1f "/home/mc/soft/cntk/cntk/lib:/home/mc/soft/cntk/cntk/dependencies/lib:/usr/local/mpi/lib:/home/mc/torch/install/lib:/home/mc/torch/install/lib:/home/mc/soft/cntk/cntk/lib:/home/mc/soft/cntk/cntk/depend"...
    audit_list = 0x0
    relocate_time = 6380140
    any_debug = 0
    preloadlist = 0x0
    version_info = 0
    load_time = 1626021
    tls_init_tp_called = true
    _rtld_local_ro = {_dl_debug_mask = 0, _dl_osversion = 263187, _dl_platform = 0x7fffffffdb09 "x86_64", _dl_platformlen = 6,
      _dl_pagesize = 4096, _dl_inhibit_cache = 0, _dl_initial_searchlist = {r_list = 0x7ffff7fd0668, r_nlist = 21}, _dl_clktck = 100, 
      _dl_verbose = 0, _dl_debug_fd = 2, _dl_lazy = 1, _dl_bind_not = 0, _dl_dynamic_weak = 0, _dl_fpu_control = 895, 
      _dl_correct_cache_id = 771, _dl_hwcap = 3219913727, _dl_hwcap_mask = 0, _dl_auxv = 0x7fffffffd9c8, _dl_inhibit_rpath = 0x0, 
      _dl_origin_path = 0x0, _dl_use_load_bias = 18446744073709551615, _dl_profile = 0x0, _dl_profile_output = 0x7ffff7df54a0 "/var/tmp", 
      _dl_trace_prelink = 0x0, _dl_trace_prelink_map = 0x0, _dl_init_all_dirs = 0x7ffff7ff7a90, _dl_hp_timing_overhead = 18, 
      _dl_sysinfo_dso = 0x7ffff7ffa000, _dl_sysinfo_map = 0x7ffff7ffe760, _dl_hwcap2 = 0, 
      _dl_debug_printf = 0x7ffff7deb080 <_dl_debug_printf>, _dl_catch_error = 0x7ffff7de9f50 <_dl_catch_error>, 
      _dl_signal_error = 0x7ffff7de9d20 <_dl_signal_error>, _dl_mcount = 0x7ffff7dec2f0 <_dl_mcount>, 
      _dl_lookup_symbol_x = 0x7ffff7de4830 <_dl_lookup_symbol_x>, _dl_check_caller = 0x7ffff7ded740 <_dl_check_caller>, 
      _dl_open = 0x7ffff7dee2d0 <_dl_open>, _dl_close = 0x7ffff7df0420 <_dl_close>, 
      _dl_tls_get_addr_soft = 0x7ffff7ded340 <_dl_tls_get_addr_soft>, _dl_discover_osversion = 0x7ffff7df1800 <_dl_discover_osversion>, 
      _dl_audit = 0x0, _dl_naudit = 0}
    _dl_skip_args = 0
    __pointer_chk_guard_local = 10213190569300236568
    _rtld_global_ro = {_dl_debug_mask = 0, _dl_osversion = 263187, _dl_platform = 0x7fffffffdb09 "x86_64", _dl_platformlen = 6, 
      _dl_pagesize = 4096, _dl_inhibit_cache = 0, _dl_initial_searchlist = {r_list = 0x7ffff7fd0668, r_nlist = 21}, _dl_clktck = 100, 
      _dl_verbose = 0, _dl_debug_fd = 2, _dl_lazy = 1, _dl_bind_not = 0, _dl_dynamic_weak = 0, _dl_fpu_control = 895, 
      _dl_correct_cache_id = 771, _dl_hwcap = 3219913727, _dl_hwcap_mask = 0, _dl_auxv = 0x7fffffffd9c8, _dl_inhibit_rpath = 0x0, 
      _dl_origin_path = 0x0, _dl_use_load_bias = 18446744073709551615, _dl_profile = 0x0, _dl_profile_output = 0x7ffff7df54a0 "/var/tmp", 
      _dl_trace_prelink = 0x0, _dl_trace_prelink_map = 0x0, _dl_init_all_dirs = 0x7ffff7ff7a90, _dl_hp_timing_overhead = 18, 
      _dl_sysinfo_dso = 0x7ffff7ffa000, _dl_sysinfo_map = 0x7ffff7ffe760, _dl_hwcap2 = 0, 
      _dl_debug_printf = 0x7ffff7deb080 <_dl_debug_printf>, _dl_catch_error = 0x7ffff7de9f50 <_dl_catch_error>, 
      _dl_signal_error = 0x7ffff7de9d20 <_dl_signal_error>, _dl_mcount = 0x7ffff7dec2f0 <_dl_mcount>, 
      _dl_lookup_symbol_x = 0x7ffff7de4830 <_dl_lookup_symbol_x>, _dl_check_caller = 0x7ffff7ded740 <_dl_check_caller>, 
      _dl_open = 0x7ffff7dee2d0 <_dl_open>, _dl_close = 0x7ffff7df0420 <_dl_close>, 
      _dl_tls_get_addr_soft = 0x7ffff7ded340 <_dl_tls_get_addr_soft>, _dl_discover_osversion = 0x7ffff7df1800 <_dl_discover_osversion>, 
      _dl_audit = 0x0, _dl_naudit = 0}
    _dl_argv = 0x7fffffffd788
    _rtld_local = {_dl_ns = {{_ns_loaded = 0x7ffff7ffe1c8, _ns_nloaded = 22, _ns_main_searchlist = 0x7ffff7ffe480, 
          _ns_global_scope_alloc = 0, _ns_unique_sym_table = {lock = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, 
                  __nusers = 0, __kind = 1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
                __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 22 times>, __align = 0}}, entries = 0x7ffff7fcb000, 
            size = 127, n_elements = 65, free = 0x7ffff7df1c00 <free>}, _ns_debug = {r_version = 0, r_map = 0x0, r_brk = 0, 
            r_state = RT_CONSISTENT, r_ldbase = 0}}, {_ns_loaded = 0x0, _ns_nloaded = 0, _ns_main_searchlist = 0x0, 
          _ns_global_scope_alloc = 0, _ns_unique_sym_table = {lock = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, 
                  __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
                __size = '\000' <repeats 39 times>, __align = 0}}, entries = 0x0, size = 0, n_elements = 0, free = 0x0}, _ns_debug = {
            r_version = 0, r_map = 0x0, r_brk = 0, r_state = RT_CONSISTENT, r_ldbase = 0}} <repeats 15 times>}, _dl_nns = 1, 
```

**Comment by wolfma61** [comment]
no follow-up for a long time, please open a new issue if you experience this in a more recent CNTK installation
